= Eki Kando! By Humayun Ahmed
Translated from Bangla
:doctype: book
:toc: left
:toclevels: 2
:sectnums:
:icons: font
:source-highlighter: highlight.js
:description: Translated from Bangla (51 pages)


== Chapter 1

// Original page 1
[[page-1]]

Eki Kouro!

www.morchana.com

http://www.co.com/forum

Swaman Ham

s4suman.com

// Original page 3
[[page-3]]

& >


Con's Fones don't trust me.


His mother raised her eyes when she said something, right? Again?

Shut up. I don't want to hear anything. 05


Why don't you say 'buck'?


The mother of Taon says with a bitter throat, 084 C Jingala

That's it. That's why I don't want to hear. Reo obey


The time I read it, it's when I come. It's too boring. [ Map on page 16]

How's a bungle? Asking for reading?


A couple of times. Sometimes they mock me for reading.

'They laugh at you?


It's a pixOt. That day, what did you say?

// Original page 4
[[page-4]]

'The capital of Bhutan should be named!

// Original page 5
[[page-5]]

I said, "Thempoly." The crow says it's a name of Jozak. It's started

With that. What's with that — sweet. The capital of Bhutan should be named. Kimpo

It's starting with the kick. Ka is the best character because the crow starts with a kick. [ Map on page 16]


'He told you


Stevetby dad.


'Okay, now shut up and sit in front of me. I'm gonna give you one or two.

I will. Calm down. Hold still. What are you doing with the pencil?

You're going to eat that asshole. Why are the INA bet on the Pildele table? You are.

You're not playing soccer. You're sitting. Sit down. "


She was so polite. His father's receipt, his mother and little daughter

He called the sister. The little sister's name is gentle. He's a year and a half.

Could stand. Can be a little VGH, but you can't tell me. Tuk

Who he calls — Kun. Mandha is a happy girl with everything. Drinks. Disgusting about

He doesn't. I don't want to eat, I don't want to eat, and I don't run around all the way home. Sweet

He eats happy, then he goes on to smoke. Lowerer

No need to go to school but he wants to go to school too. In school like this

When you go, it's not black. Go to school

How?


The mother of Tair said you're not going to walk. Your father, Repa.

I'll get you back.


'Heat has to walk on a bicycle, mother. [ Map on page 16]


'No, it won't. Your father's gonna put you in a bicycle.


Muna boy is in pain. The worst is being made to suffer

It's about talking. A boy in class Bs, seven years old. Why he

You want to talk so much? And when you say, many think.

I think the crow comes and talk. A few days ago from home, Munar.

Father-in-law is here. His body will show the false. The doctor showed me. One.

A week. When she left, she hung her face and said, "Malma,

What's that say?


'You're talking to Kake

// Original page 6
[[page-6]]

Yes mother.


It's like that, Dad. Very interesting. In his pain, we

I'm sick of you.


I mean, Mom — as I said again

I believe it. Maybe ATA!


- Dad! Would you like to talk to him?

How? Does man understand who?


"Some can, please. A prophet of ours was Hazal Sulaiman —

He could understand the bird.


Muna got bored and said, Dad, no Tukko Prophet. He's a bad boy.

You don't listen to him. When all of this comes to talk, threats

Will do. '


No, no, what's the threat? Baby boy  If you're a child, you're a child.


It's not worth it. On the cheek

I'd like to slap you. No slap. His father, without rule, is in modern territory.

Boy will raise. This is the result of raising children in modern-day areas. [ Map on page 16]


He's sitting on his feet.


Mr. Rashid has just pulled a chair in front of Ratan. Myth

You've got it in your arms. Make sure to see the mouth from here.

I can't. Sometimes when she looked at him, she saw him.

You got it. Munar looks like a little for a boy. A kid.

For — court. No need. Don't make it up and talk.

There's nothing wrong. It doesn't seem very worried. He's her.

He's looking big at Dad.


He said, "Kun!


Stevetby dad. "


'What's the name of the crow who talks to you?


Ceyw has no name, Dad. The birds don't have names. People have names.


'What did he call you to do?

// Original page 7
[[page-7]]

'I call him a name. Says tuna. To:


" He talks only to you, doesn't talk to us — What is the reason?


"They like children. ♪ Like adults ♪


The  link is small. Why doesn't he like him?


They can't see him, Dad. This day told me, yours.

Who gave the little sister such a bad name? In addition to your name.

Should've kept it. That would be nice. The sister of Rupert.


'This is what the crow told you


FA?


'And what's ee


A little bit later, the guy asked English? This time, he said, "What's English?" [ Map on page 16]


'You speak English?

Tukh said with enthusiasm, I did. Spelling and saying — Google.


'Okay. Now you mind me saying TA


I'm listening very carefully, Dad.


'SP is not listening carefully. Come on. [ Map on page 16]


'The kick has told me, you know, you know, you know, you know, you'd just sit down and sit down, or you'd have to. If

Sometimes you have to sit and dance. Legs are ripe.

Blood movement is good. Legs are good. Like our wings, yours.

My feet. '


You look at JAR in a frustrated eyes. You laughed.

On the other hand, look at it and hide it. Look at his smile

No, he doesn't. Not today. Today, there's something that makes sense.

It will.


The receipt said, "Tenk, look at me." Listen to me. Small

He's a lot of talk. It's not too bad. But I admit him.

He's making it up. If someone makes that up

Everyone wants to know the truth then it's a problem. It's his habit.

There you go. You tell me, don't you use it?


Tukko said it would be a habit. When I grow up, I lie.

// Original page 8
[[page-8]]

Talk to me.


'There you are. So now you and the crow.

Don't tell me. You tell me you're getting used to me.


I don't have to practice, Dad. I don't make it up again.


Don't you think you're making a  oughton?


'No. That's what I really say.


The receipt said it was disappointed. Okay, you go. Come on.

He didn't.


The receipt stopped him

He said you could talk about anything other than a crow.


Can't I talk about a pixac?


Nope.


She gave her breath a little bit, okay? The receipt is worried rice

Eat. Muna is feeding the smile. He fell asleep at eight o'clock.  Send anyway

He has to feed at night in sleep.


She jumped to her mother and Fisher said, "My mother is a funny thing."

You know what? As you feed your little ones.

He feeds. They don't have hands. They eat with their lip.


My mother said, what's the point? Never talk about WS anymore.

BI


She breathed it little.

// Original page 9
[[page-9]]

THF and tuna show in a room.


Two different things. Mandha at night is in this room. Sleep.

Breaks and goes to mom's house. One of their homes and AJ cells

The door. The door is always open.


Muna wants to keep their rooms so beautiful. Sometimes it's possible

Nope. Once you get home, the arrow cries. How can both make room?

ARCS is very calm and good girl, but it's his skill to keep the house dirty.

Excellent. He's an A, that's a quiet piece of paper. He's on paper.

Gunes. Both songs and music are ridiculous. In song she's herself

Most impressed. Smile. Paper by Moona Several times every day

We have to move. Don't cut the paper, paint it. Images on walls. The walls are filled.

Photo. Their home was renewed a week ago. Telled

There's no more pictures on the wall.


Gogona comes to their homes to use mosquitos and photographes on the wall of Datesumor.

Images drawn. A picture of who. Not just pictures, under the picture, poetry pix


VECRILING IN THE CLACK CLOWS

The cow goes through the car.

There's a crow on both sides.


Suna used the mosquito. Kiss her cheek. It's now that they grow up

Don't give me a kiss. He still kissed her. He's a mosquito in Gazor

You said I'd turn off the lights, tuna?


== Chapter 2

// Original page 11
[[page-11]]

Gonna tell me.


'Don't be afraid.


note:


He turned off the moon and sat by the boy's bed. To his soft neck,

You got the picture on the wall?


'Yes. Isn't it nice, Mama? [ Map on page 16]


He threatened his son and he'd sleep.

You don't want to be upset by bed before sleeping. It's gonna be a morning.

He said it was good.


'How is it, Mom?


"C your heart is good. But what kind of poetry is this?


On a forest tree in Bhakh, V3


I was excited to see what happened to my mother.

You know, I was reading poetry, and the crows came and said, "What are you reading?


I told you, I'm reading Rodranthan's poem, don't bother now.


What do you tell her?


'Sor


- Okay.


'He said, is there any poetry about us?

wrote?


I said, he wrote. He's the worldbie. The world has everything.

The poem is written. He said, look at what he wrote about us.

He'd read it a bit. Then I made this poem. "


Are you happy at the game?


" Very happy. He said to laugh, "Oh, Well done.

The crow is sitting on a tree. We've been able to write so nice as to make it the world. Village-cob,

Couldn't be a country or a country. It's a highly highly respected SASL. [ Map on page 16]


Mua had a long breath. Remember, he said what to do with this boy.

// Original page 12
[[page-12]]

With?


She said, Mom, she was so happy to tell me that she was doing a job.

Do me one piece on the wall! Write it down. I am

I said Mom'd be angry. The walls have been renewed. Then him.

He said no, don't anger your mother. Let me explain to him. In fact.

It's not good to be angry with children. Mom, are you angry?


Nope.


'What can you explain to my father


'Let's try it or not. You sleep now. [ Map on page 16]


When he went to sleep, he spoke of Muna crow and who's who's who. I'm worried.

You told your neck, what about the boy? What does the crow do?

Can we get rid of it?

Kurt. He mustn't be so far. You could've forgotten.

There you go.


Munna said you thought you were talking to a doctor.

Need?


He asked me to pick up the receipt. It's not a disease.

The doctor will be treated. Young people take care. You'll be cut off after a while. Okay.

Is anyone really sitting in his window?


Did your faith finally become ? The crow.

Always sit down. Sit on the window, sit on the raling.


How are you doing? "


S-SAR. FA test. Aung received by 100. [ Map on page 16]


I don't think so. '


'I'm not worried. It's getting boring for a crow all day.


He sat down with the receipt. He works at the bank, but with that

Write. All his works are for children. Now a funny book.

It's a funny book.


10

// Original page 13
[[page-13]]

Little peo has come to the house of Tukh.


Very busy with little education. His M.S. test was on the back.

No time to breathe. He said when he entered home. Gosh, breath in your house

I'm here to get you.


It's so nice to be a little boy. To him,

Maybe such a girl is on another planet. But no more. And

It's beautiful. Just keep looking.


He looks like adults when he talks to adults

Talk to the kids and you're gonna need them. He came home for a while

Play with Tuke and the gentle. Tell Mod Helma, where Ra "Sleak Your Heart"

Bring it, I'll have some dolls. Come on, we'll marry Barbie.

Don't bring a piece of paper. With him a little piece of paper

Move. A smile, too. The game is over with a gentle smile

Then tell Tukko, come on, play with you. What are you playing? If that's what you're saying.

Say you're gonna play a thief and you're a thief.

Let's play something new. Worse than thieves —


A bandman. You're a thief, I'm a woman's cop.


A man who comes home wants to jump happily. The brain

Keep your joy and say, "How long will you stay?"


We'll stay as long as it takes. Then I'm going to have something on the Ava now

It's not read, it's a test from Pochish date.


'Where's Durum going?


We need to see a better place.


- What?


"It's fair. "


Tukun and Madalala brought the tiny popoo home. The little BP house.


191

// Original page 14
[[page-14]]

I'm gonna put it up and say you're making it a mess.


Tunk said, "Is Astable small?


"The horse is where it lives. You're gonna breathe in this dirty room.

I can keep an al-Ghush breath. '


Tach said, so good, lock it up


'What the hell is that?


'Cake image. " Wasn't it good?


It's okay. The wall size of the picture


AL


'What is that under the picture?


Touch?


It's been a great match for Globoita, too. Don't tell me.

It's just Rathethan?


We've written it together. '


It's great. Now Listen to Me — Let's go to the house

I can breathe. I've been stuck for a long time. In here.

Talk to WS BF


'Don't talk to her long, but


'Are you mad? The less you talk to the older. '


She went looking for Opla Moona. Muna Chawing, watching Ola, said you are

It's obvious. Won't you leave the house until BSA? Today

I got you!


He smiled and said I came to see your little children. After a few days

I don't like it.


It's good to see you later. You're always watching me.

It'd go crazy. I spent my fucking money on the wall.

He's got a picture of who. '


Why do you have a crow in this bird?


'Who talks to CH CHL these days?


It's a pixel. ;


MR

// Original page 15
[[page-15]]

'A crow sits next to his window and talk about it. [ Map on page 16]


- What fun!


Muna said in a bitter tone, "What have you seen?" At this age, to lie.

Teaching!


'I'm learning to guess. It's a lie. It's a different thing. You.

Don't say anything to him. '


I'm sure I'm fine. Imaginative imagination.

Not good. A crow, a crow. Houses are wearing pictures. With your mind

Listen, before you leave, you'll explain to Tukko.


Let me see. '


'Don't look, you'll understand. Even if you don't paint it on the wall.

Say it. "


It's a miracle.


The tea cup went up.


Tukun is trying to clean up the house. Of course! The paper.

Going. I don't like writing. On white paper

He does. That's what PT is supposed to give.

It's full of nice papers. She'll be happy.


He said to sit on tea cup, Twenty, whether or not.

Who do you talk to?


I do. '


What do you talk about with a bourbon?


'No fine. One day. It's a song.

Sing to CHIL


'Who do you say?


You're going to tell him. His little girl is married too. '


What did you call him — uncle?


I call him uncle. I'm asking for uncle. He said, don't tell me

You call my uncle. I like to hear if you call my uncle.


13

// Original page 16
[[page-16]]

Who do you talk to?

// Original page 17
[[page-17]]

"He's serious, he looks very concerned. "


You said it, bitch. Very cool. Often, what's happening to the country?

So it's going down.


She smiled and said that your father always said that. Yours.

Didn't you learn to hear him?


You may also. He's good at memory. When he hears that.

I told you a long time ago, February 14th.

I remember him. Tell me, what's my birthday?


I said I did.


He said it was a shock. It fell on Sunday. Holiday.

On Sunday, I like to walk around. I can come and understand.

I can't.


Come, you're welcome.


'I gave it to you. '


'You did good. I don't think he'll come in empty hands. Something must be.

Bring it. '


" I don't know, " she said, "but I don't know what to do. "


I think it's dead rats. Shit.

The mice love it. They're very expensive.


She wondered what to do with dead mice?


He said he'd eat. A man of yours takes so much interest

You give me one thing, and you throw it away.


Tachun is looking at little Fupur. He's trying to laugh

Keep it. He didn't. He laughed. " I'm so sorry, " she says.

She did. Both laugh. BS looks at them. And

Then something happened.

He called out from his neck in his cheeks, looking at Opa.


The smile said, "Here's your uncle."

I'm not saying anything.


She didn't say anything. The crow called again — Kaka.


15

// Original page 18
[[page-18]]

What did he say?


‘Why is SR laughing?


Tell him why I'm laughing.


I won't say anything. [ Map on page 16]


"Well, I'll tell you. I think I'll call her. When you

Uncle is my uncle, and I'll be older brother. Should I call brother?


C'mon call whatever you want.


Looked at the window, he said, hello brother, for a reason.

I'm laughing. It's good to say FA with you. You think that's Ern

Come back to my birthday. Don't come in empty hands. Bring me a present.


The crow says, Kaka.


He said you won't bring an army back. Come alone. Now

But go home. Sea


It flew with a crow. It's a miracle. Remember

It's getting angry. He has big eyes wet. Before we cried

That's what the eyes look like. Oh, he said he looked like that.

Why are you there? Are you mad at me?


One


'Why, what did I do?


You didn't believe me. That's why I'm angry. Whatever you say.

I believe that. Why don't you believe me?


- You want me to believe you.


[ Map on page 18]


'I'm not like other adults. I pay attention to children

And try to believe it. But I can't believe you:


'Why not?


listen to the birds.

I can't. A man's brain. Hey, man!

A little. The salt spoon. So little brain talking for birds

Possible


16

// Original page 19
[[page-19]]

He talks. Just a little bit of ant.


It's about teaching you. That's a bad word — 'Kumtum has come

Give me that. Not much. Besides, when the angels speak, we all are.

I can hear and understand. There's a crow talking and you mean only by yourself.

I can't. GR is nothing different. You're just one of us.

Your FU hands, ZI leg, you're bad eyes. Do you understand?


'I'm coming. '


"If you understand, smile at me. Get your teeth out

Smile. '


Don't laugh, seriously tell her, if I'm the little little crow

Trust me?


A little quiet and said Ghodi was real for you.

You'll have to think about it again. No

I can't believe anything. Trust me. Big problem.

The terrible problem. '


What's wrong?


Here, a man came and said that his shoes on the New Elephant Road in Dhaka.

A terrible thing to do with store. A tiger is out. He's got him.

She's bit him. Now, if you believe the guy's point, everyone's covered.

How about getting away? Is this okay?

'C, it'll be alright Are

ORT You're getting to know we're going to believe something.


I got it. '


That's why I don't believe you. It's your birthday.

Let's see what your crow brings. Then we're not again

I'll think about it. Now laugh at me.


It's getting angry. I don't want to laugh. Yet to make small sacrifice

She laughed.


Nooh


17

// Original page 20
[[page-20]]

8


Today's birthday.


Tukh thought it would be a great birthday. People are going home. Big

A cake will come. Seven candles will burn. He's a candle with Fazbar.

You want something in time. Whatever you want. This is the rules. See you

Nobody's coming for my birthday.


He's back from the office this afternoon and he's got empty. A gift.

The pack didn't appear in his hand. At once, tun went near his mother, saying:

Who's going to get my birthday cake?


He said no one's going. What did we tell you last birthday?

Seven years old. Then there will be no more. It's all about your father.

I love it, A  enjoyed it!


No one will come to the house of Creak?


- No one's coming. I didn't tell anyone to come. But if any of you does.

Come on, then. Like your little dinner will come.


You'll find a pixor. Isn't it Mom?


A gift gift from the BAT-Freak


'Cmool bought something for me'


I bought a present. Whether it's right to give you.

I don't understand. Your father is worried. If he thinks you are.

Maybe you'll pay.


How long will it take to end his thoughts?


I can tell you what the matter is.


You know, it was sad to get around. He doesn't like anything. Of course he is.


98


== Chapter 3

// Original page 21
[[page-21]]

Not yet. I don't know why I think I'll see you after nightfall.

They're full of houses. They didn't mention birthday, however.

Date. They've been here for a while. There's so many people.

Look at the last ES Dad.

Let's get it.


No one came after the evening. Not even small. But little Papu

He's calling.


"Hale. Baby, happy birthday. '


Tachkodo Kudo told his throat, "Tack you pl"


Couldn't raise your voice. He smiled, too

It's funny, isn't it?


Oh, come on.


Are we cut?


'Now it's not.


RECT looks real. Phone tears

Protection is not visible. We'd have a problem.


Look,


If you're not married, you can't help it.


'Why are you listening?


- What?


He said, "I wish I could get sick." To bed.

I could've worldised it. Nothing is happening. A day and night's studies

Here we go. Now I read Fluive Denamics — the worst thing. '


'Do you buy my gift?


'No, I didn't buy it. Can't leave home — What's the gift?

I'll buy you one time and go. "


Really?


'Good thing, did your crow bring a gift to you?


'I didn't come.


'What do you think will come to you?


38th.

// Original page 22
[[page-22]]

Hello, honey. YS is born!

// Original page 23
[[page-23]]

I don't know. [ Map on page 16]


' Call on El


'Okay. '


Tokun sat quietly in his home. I'm not in this room today. Her

It's getting cold. Eyes red. I'm constantly getting water with my nose. Mua with him

Go to the doctor. He's dressed hot.


The receipt came and called to her house. He said,

Calm down on the chair and sit down.


Tried.


Are you upset? What's so dry?


'I think it's cold. '


'Your birthday is A — is it not sad for this?


She didn't say anything. Shut up. He said that you are.

Didn't I tell you last time?


Yes.


There are many young children in Dhaka City who are here

Sleep under the open sky in the cold. One of them is hot.

We're not even here. It's not right to be a birthday. I'm yours.

I bought it with my birthday money to buy her hot clothes. I didn't do it.


Go on


You're saying yes but you're upset. To you today.

I'm sorry but I don't feel bad when I grow up. It'll be better.

Then you'll tell him what Dad did good in this country.

You should. '


'May I go?


No boss. I'm not finished. I'm a gift for you.

Buy — See if AT


Father gave me a present. What a beautiful gift!

A colorword. It's three brushes. I think it's so big.

There's nothing left on Earth. He bought it.


21

// Original page 24
[[page-24]]

Here.


listen up


'Yes. I like it. Very much. '


The receipt said you wouldn't get the box, Dad.

It's my GIF locker. When you want to draw the picture

I'll paint a painting in front of me.


Why dad?


Cm , because you're full of graffiti on your hands.

Do it. It lets you do it. Now you want to draw a picture?


[ Map on page 15]


"Well, I'll use the GIF


Tanton's parents took her to the doctor. Tuk alone

Just sit at home. She's not alone at home, she has her mother. He cooks in the kitchen.

He's doing it. I don't like that. Su Kumar Roy's book. Read

She tried.


Singinging

In the Colossian Forests

Wind Sean.

Scattered piece of shit.

Fly Van Bon WY Zing


Other times, this poem was so nice! It's going crazy.

The books are closed, and the crow comes by the window. SIA throat

He said happy birthday.


Tach said you are.


The crow says the GIF is gone?


Yes


I'm late. People don't like crowds. Age


S.

// Original page 25
[[page-25]]

That's it. It's a mess. The cake cut?


We didn't buy a dire trick.


'Why?


'Dad said it won't be birthday. From now on, it's a birthday for the poor.

Buying hot clothes OA


- Okay.


" He's a writer, he's sad to see the suffering of the poor. '


'What is this? Why do writers only care about the poor?

I hate it. I'm not a writer. I'm a crow. My own.

I hate it. Anyway, would you mind Avery?


I didn't do that.


- That's what they lied to. You're sitting in the dark and you're talking.

Not bad. You're laughing. [ Map on page 16]


She laughed.


The crow says you don't have much fun. Looks like they're laughing.

How about a story? Can I tell you a story if you want to hear?


Tell me.


There was a crow in a country. It's very happy to find a piece of meat.

Tree branch. Then a fox decided to fool the crow.

Take it.


I know this story. It's the Esp story. "


He told me the wrong story. Didn't tell the real story. The real story is you.

I'm listening. Then what is the matter — the fox said, "Son, brother!

Your voice! When you sing in kako in the morning, it's so nice.

No other bird can do that in Vorbi's anger. You are the only one.

You can. You don't sing a song to me. I'm dying for listening to music.

He's doing it. [ Map on page 16]


The crow caught the fox with the cleverness. He will sit and face

He'll fall down from the bone. The fox will eat that. So.

What did the crow do?


2

// Original page 26
[[page-26]]

Golli. Songs are 3


Jerusalem

The fox's a fool, Kaka.

You idiot, you fool, kaka.


You know this — it's the real story. It's a fake story. Your father.

So the writer man. Tell him to write the real story.


'Okay.


UR, your birthday should not come with an empty hand

Bringing gifts. I don't know what you'll like, Avery.


Did you bring it?


A Zhong kid.


What?


'RY


She wonders where I can't see anything.


You can't see that. Zheng is good.

Only birds see Zheng's baby. Ae's kid's going around.

They'll play, but nobody's watching. '


COON-ASS: - What fun!


It's a gypsy. Besides, Zheng's kids won't bite anyone — Nothing

He doesn't. Sometimes it just bothers. '


'Can you hand it over?


'No, you don't understand anything with your hands. [ Map on page 16]


'Five, fun CI


It's funny. "


'What's wrong with Zhong's baby?


Creakze. You don't have paper at home. Father Author

Human. Squirrel Gleak is constantly moving on paper. '


What's the child in Grenada?


'No. But sometimes they laugh. It's too slow.


28

// Original page 27
[[page-27]]

The IPD's shit.

// Original page 28
[[page-28]]

You'll know, A.

'Where is he now?


COON-ASS: COON-ASS: Hey.


'What's it like?


It's beautiful. Like a small horn. Big ears like rabbits. But VOI

No, four ears.


'Do you have a tail?


A.G.A.L., no tail.


What if I give him a paper?


'No. He's a boy in front of men, he never eats anything. When No One Is

Then he bled the paper and swallowed it."


What a surprise!


'You're happy to hear that.


I'm glad to see you. Thank you. '


The crow blew. He wants to hit the girl of Zheng

That's not possible. It doesn't look. In the dark throat,

Zheng's kid, I'm so happy. Very happy. Here's some paper.

Here. Eat when you're hungry. I'm gonna call my little aunt now.


' Hello little papu


Why are you sweating?


'It's a matter, little Papo. '


"It's been me. BS Vingamiz all morning.

I read it and thought I was wrong. I don't remember.

Nothing. I want to scream. What's your amazing thing?


'Kack came.


He's here, so he's got an empty hand or something?


You're in the Casablanca. [ Map on page 16]


Creak brings — dead mice, or chicken.


- The son of the Jung Zheng. '


Rb

// Original page 29
[[page-29]]

Did you say that to the kids of  understand?


Son of Hoong. '


'What is that?


"There are four long ears, like the ear of Shahgoesh. Goal, Wooler

Like that. '


Did you see?


'No, little peo. I can't see that. Zhong's baby is invisible."


Invisible!


Yes, invisible. You can't touch them. '


'How can four big ears


It's been said by the Creak. "


COON-ASS: Okay. [ Map on page 16]


Do you know what the kids of Casablanca eat?


Sorry


'Course. No more food. '


On the telephone, he keeps breathing, saying you're smart.

Boy. All class tests Fart-second Hoss. At this age, Suuan Roy is all

Sing poetry. How do you believe that Zhong's kid is something?

Is there someone you can't see? You can't touch him. And four of it.

Long ears like rabbits. Get out of your head. And the parents.

Don't say anything about Zheng's baby. I think you'll have to eat. I am

I got my phone.


I'm sorry. You're upset at your own room

She was surprised that one of her pieces of paper on her bed

Nothing. He must have eaten Zheng's kid.


The tunk went back to telephone.


Hello, Little Ones.


What happened?


You know what Zhong did?


I want to hear a word about Zheng's child


27

// Original page 30
[[page-30]]

Nope. Tell me something else. Anything to say?


Casablanca.


'Well, put your telephone down. Don't bother me anymore. Remember

Keep it. Read me something. Not yet. I'll probably get the third class. What do you want me

Got a class?


I don't want to. '


'So put down your phone. And listen to me carefully. That's it.

It's going — don't call again. '


All right. We'll find you.


Good-bye.


A small BP.


Put the telephone down, and the telephone is nearly once again

She did. He knows he'll be angry but he's called because he's real.

That's not said.


' Hello little ABP


Okay.


'Are you angry I called again? [ Map on page 16]


I did. Too angry. '


"I'll just say one word and put down the telephone. '


One word.


'The hoe's bitch. She ate the paper. '


What's he eaten?


TITS TITS TITS took a lot of paper on my bed. They eat

He did. Now there's no paper AR!


'Son tun — Zheng's kid didn't eat any paper. With the bourbon.

He did. Ask him. [ Map on page 16]


'Okay. '


Tukko didn't ask anything, because it's ringing. Her parents

He's here. Two o'clock to the front door.


He bought a cake on the way back


28 Watching the World


== Chapter 4

// Original page 31
[[page-31]]

You brought it. Not just cake, but eight candles.


After dinner, there was a fire. Mom said close your eyes

You want to be kind and light candles. A little light.

It'll be a good idea to take a light.


Tried to close the eye and said I was Zhong.

I can see the baby. The eyes looked and all the candles went out. Even more.

Big thing. The body looks soft.

Glass's ready. Eyes light, pink. Four long ears in the air.

What? Sea


The tkkun shook up and said, "Look at him!

I see it!


What are you saying?


Tokko said there's a Zung kid sitting there. He's listening. Look,

What a beautiful ear!


♪ When I said that ♪


You're so cute.


What's the matter with Zhong? [ Map on page 16]


'A invisible creature. No one can see this animal. Four of it.

Long ears. He's sitting in the chair. '


'Do you see?


'Yes.


I've been looking at him for a long time.

Then FACS said it was a crow. Now related to him —

Her child. What do you think?


Muna looked hard at them and said, "Where is your Zhong?"

Children? It's...


He's sitting in the Casablanca. '


Grab him.


Towach Zheng's baby. The kid didn't run away. More hands.

He jumped out with me. With a baby in the tung's arms

Incoming. Her parents, both eyes look big. Because they


Nothing.


29

// Original page 32
[[page-32]]

What happened to him?

// Original page 33
[[page-33]]

Tell me


Tanton's parents have brought tun to a child expert.

The gentleman's name is M. Alam. A very big doctor at a child hospital. It's serious.

Then he — he seems like He knows funny stories.


The father said, look at this kid.

Doctor.


What happened to him?


See if there's any problem with him. '


What are you talking about? What do you care, kid?


She said no.


'So what's wrong with you? Do you remember reading?


The following year, I was baptized. [ Map on page 16]


Munna said he had no problem out there, doctor. To study

Good. Smart. A lot of sports. It begins to say so — One.

The crow speaks to him.


The doctor smiled without saying Sona

Here. He said to laugh, for this little reason you brought him to me

You brought me? When I was a kid, I remember clearly — I

I spoke to a Teddy Bear. It doesn't matter.


I know it doesn't matter. Me or my wife

- We didn't care much but we had a new problem. He says.

He has a Zhong kid.


What?


Son of Hoong. An invisible creature. No one can see. Just him.


A

// Original page 34
[[page-34]]

He sees it. Well,


The doctor said, don't say that. What's the importance of it? Children.

There's a lot of fantasy. You know, it's gonna be all over. Yours.

No reason to worry.


The receipt said that there is no reason to worry. Ooh.

Now he's always been with Zheng's kid. She's having a bath. Clear

He's on it. Taking me to school. There's no way we can slow it down.

Here we come to you — My son brought his Zhong children.


Did the doctor smile, son?


She said yes.


Where is she?


'This is it, sitting on your table. "


The doctor looked at the table. I thought he was empty table.

A bit disappointed. Maybe you expected to see something. Doctor

Looked at him and said, "What does your Zung  eat?


Creaks eat.


Do you have any kind of paper?


FS A  mean newspaper A sign


'The money? '


It can do. I never gave him money.


'Okay, I put this interesting note. Let's see if he eats. '


Dr. Onet.


She said she wouldn't eat in front of you. If anybody's in front, they don't eat.

Eat.


Tukk said, eat tuna, eat.


Five hundred bucks. She said she wouldn't eat. We look

I'm here — don't eat for this.


The doctor said he wouldn't eat money?


She said, "We're all watching and not eating. Don't look


32

// Original page 35
[[page-35]]

He would've eaten it. He's too shy.


'What do you think he's got? [ Map on page 16]


MIS nature. Very SH?


'Is there?


'It's okay. They're not as white as us. They're light blue


B? [ Map on page 16]


Sometimes I put my teeth with my GR. '


Muna said, doctor, now you — when we see one

How does it feel when the boy is begging an invisible creature?


The doctor said without answering FAR said,

AD? Where's the money note?


That's it. ARP, put in the table.


She said, I think Zheng's kid ate the note. We

When I was looking at the other side, he was drunk.

He did.


The doctor said, ‘ Listen, kid, nobody eats anything. The note in the air.

He fell down from the table. GEL will find it.


The doctor was busy looking under the table It's amazing.

All the papers in the basket were on the floor. The parents wanted to find out.

They're looking. Not a note. The doctor said in his face, maybe the wind.

He's out of the window. That's it. Nothing more. She's her

I sent Gasston to find out. Getting something


The doctor said that I understood what happened — the note from the window

He's out. Someone's found someone. It's the only explanation.

If you don't mind, I'll tell you

Give me the money.


♪ Why don't you give me money ♪ Well, better, the existence of this invisible beast ♪

Do you believe?


'Fal?


'What happened to believe this beast?

// Original page 36
[[page-36]]

It didn't happen.


It's no problem with the pix. This guy doesn't think it's bigger.

Not talking. I think your son, H.G. Wells, is a pixinive of H. Wells.

Man fell. After reading it, the concept of an invisible beast went through his head.

Don't please. That's it. [ Map on page 16]


We're not giving up. '


He didn't even want to. These are some of the ways in which we can imitate Jehovah's love.

He's here, too. '


The doctor looked at him and said, "You're invisible.

Have you read the book?


Tochunkari's neck says Manz cannot disappear. disappear of Zhong

Children.


The doctor said it's okay.


He woke up. You tell Tukk, give him a shot.


She said, Galluum.


The doctor said, "Are you taking your Zhong's baby?"


I'm taking you there. '


Cruttine


The doctor's GEU went after the guys left, because it's kept on the table.

He doesn't have half a page. Looks like it's just been pulled out.

But this diary is important to him. Emergency address, telephone number.

The doctor was sitting on the serious face.


34

// Original page 37
[[page-37]]

6


The Opala test is over. Good to be a good experiment. He

The day after the test, one camera was at the house of Tukkior. Now he

Research the famous Zheng kid. I got the camera. of Jheng

Take photos of children and print photos. If there's anything in the picture. Photo taken

Dead. A single photo. Flashlight, Flashlight.

Except.


She said we'd see her in the picture.


He said we can't see. Something you don't see.

Not even on camera.


Why are you reading the photos?


I'll take care. "


Not only did she take the picture, but it did something more. The weight machine

The beast tried to weigh the weight. No weighing.


He said, "Now your son Zhong's got into the water of the middle child.

I'll hold it.


What's going to happen to the direst?


We'll see if it needs oxygen to survive. Take it.

Come on, we're fucked up.


No, it will hurt. '


"If you suffer, you will suffer. Then let him go. You got it. '


Dheng's baby is fucked up. Nothing happened. He said,

Well, what happens to him if I sit on your SEP?


'It doesn't matter. It's too late. When you get up, it's over again.


Let's take it to a clinic. I'll make the X. X-ray


Okay.

// Original page 38
[[page-38]]

She said we'll have your son in the water now.

// Original page 39
[[page-39]]

Let's see what's going on. '


It was done. He wrote a report after several tests. The report.

I had written it in English. The one he calls.

Newer scientific report. Sit down and get rid of your head.

Do it. You hurt everyone enough. No more.


What he wrote is,


Las

species


oo 8G


weight

The Bible does not say.

Alphabet and smell

Food.


oo 0698G Of


Photo

A short X test

oxygen takes


The tragedy is tolerance 3


Elements


Ur


Object Partition:


Sahh's kid.

A scientific report


Ding's baby.


Unknown. (For fully formatted text, see publication)

Bq


Nothing.


Sean.


Nothing.


( a) Aver's idea — Eats paper

Though it could not be proved.)


Nothing found.


The so-called beast does not receive oxygen. Water

Down, and the carbon-divided beast.

He's got a long time.

The beast's got some pressure too

Relax. Pulls like barbers

TSH CK because none of us can see it. [ ]

The forest is chemically chemical PRERT water, strong

He doesn't care about acids and Sigth.


It could go through an object. Him.

If you close it in the trunk, you're gonna get this truck.


37

// Original page 40
[[page-40]]

Test Result


Maybe we can go through it. Of cement.

Imagine.


This is a researcher considering the test results

The conclusion is that the invisible beast is one.

The pain of a teenager. No way.

Can't tolerate it. The boy is called as if he was.

His invisible beast, the so called Zhong's child.

He threw it away immediately. Her

It's too good for you and your family

I need it.


It was black. Did you read it?


note:


"For three days. I wish to free this torture within three days.

I told you what was found in scientific exams. '


'Aweat! '


'Why are you making me look like a bone? There's nothing to keep your face in a bone. '


He went to spit. Be quiet in your own room

Sit down. I don't want to play with Zheng's kid anymore. Just

You're doing it! Squigga is a little bigger time to talk to her

Cut. He's still learning to move, just a little walk.

He learned. You've learned to talk. Nothing but paper QU is still good

Can't. He left the paper. Zheng's baby is sitting in his arms. Sit down

He eats. The idea of a kid can be seen. That's it.


A can't tell others about this.


None


== Chapter 5

// Original page 41
[[page-41]]

It's a holiday. Never sleep at noon. He's so upset today

The bad thing that fell asleep in bed under cover — Sleeping creatures

Called —


'Oh, come on! Is it somebody sleeping in the afternoon? [ Map on page 16]


Tried up. The crow asked many questions together,


What's the matter with the direst?


Why are you upset?


Don't you cry?


What happened?


Toch said, "Gheng's baby" was researched by some.

Nothing.


'He threw it out? [ Map on page 16]


'Sy


What did she say?


'Lal, there can't be anything that just eats paper — And some more, ATP.


'This is what he said'


"5


'Sunkun, there are children in Zheng. Every government office does a bad one.

Zhong has children. What do you know? They eat useful files.

Don't hear the file often: why not? Children of Zheng

She ate. They're alive to eat government files. [ Map on page 16]


- Really?


'Yes.


There are children in Zheng , too, where Dalalalad lives. Her.

He ate the record. '


'No one says anything.


Oa

// Original page 42
[[page-42]]

'C, but happy bap


A little Fupur research, right?


'Conferer


He wrote on a paper. Can you read?


"It doesn't seem to be a good time to study at all. They're disturbing me. You're AG

I'm eo.


He fell. He heard serious things. When you finish reading, he says,

Begas. Research is nothing. Your little head is fat.


Cracker's no fat. Last year's engineering test fast

He's done.


It's just a stupid sign. They do not understand anything but reading books —

Only reading books and ft-second. Here's your legend.

He wrote such a beautiful poem about the crow —


In the month of the year, the crow sits on a tree. '


Has he ever been to Fart-second? He didn't. You're your little boy.

Say — Fupu, your head fat.


It's not possible to say that. He'll be very angry when he hears it. [ Map on page 16]


It's better to say that if it's possible. You don't have to hide the truth. What a freak.

I can't see girls. So he said he didn't have anything. Many things.

It's not visible. Theirs.

We have weights, but little weight. I can't be measured by a simple metal. He's from Zheng ,

The weight of a baby brought a beard with a beard. What?

You stupid girl — you! Go, go!

Come on. '


I got on my phone.


' Hello!


'CHKunk?


Cate


'Okay. I thought when I got Zheng's baby, the crow is gone.

He's done. He wasn't gone?


[ Map on page 15]


40

// Original page 43
[[page-43]]

'That's good. What did he say? [ Map on page 16]


'He said — your head fat. '


'My head fat? '


Yeah?


'And his head is too narrow?


'The little boy didn't say anything to his own head. About yours.

He said. Well,


'Why didn't you tell me my head fat?


You're saying. He said there's no point if he doesn't see it.

Not really. Don't touch me. But there's a line. '


'Of course it is. But an idiot.

There's work. You've got to get hit by him. I'm hit to make way.

Your Zhong kid doesn't do anything. Don't shock anyone. I wish everything had happened.

I'd know he ate the papers.


Why are you so angry with QA? [ Map on page 16]


'Rege is angry because I'm angry. You're the crow

Come on. Can't you tell me?


Shaw?


'Why not?'


'Cause he's not stupid. Birds are never stupid. Your head.

Really fat. What? [ Map on page 16]


He's listening to the little pingle. She's scared of tuna.

That's it?


'What are you doing?


'Sl, I'm slaming. I'm twenty four. Someone to me.

Heads up. He didn't. You said. I'm Kidb Ae dole


"I didn't say little Popu. The crow says. '


It's bullshit. These are your thoughts —


On small telephones, they cried like children. It's a heart.

Bad luck. He never thought it would happen. To find her own tears

It was. Only he knows what he loves for his little aunt. And someone knows.

Nope.


81

// Original page 44
[[page-44]]

& Edit


Zheng's kid must understand the situation. It's sad to see that tunas today.

He seems to understand. Because he's on foot. Tuk

He fell down. After a while, he'd come to bed and sit on his side.

That's it. Look at me. She said,


I'm sad today. "


Dhong's kid was deaf. As if he can understand.


It's sad for a lot of people. First Cause — Little Popu for Me

She cried. And the second reason, nobody believed me. My father thinks,

I'm out of my mind. Okay, am I crazy? '


Zheng's kid answered N. disbelievers. My ears. My ears listen to me.


How do I do that?


Zheng's kid didn't say anything. She cried. SATS doesn't cry. Large

That's it. When I grow up, I don't cry. Dheng's kid is sleeping

It's off. It jumped on the floor like a bar ball. Reading like a ball

A couple of times when they were taken out of the door. Almost.

Then she saw the pillow wearing her colour. Well done.

So, the AWGB! Of course you do.

Here we go. She didn't lock it off?


Tanon's got a little better. Beautiful on the wall with color.

If I get a picture, that mind might be completely good. One of Zheng's children.

Big photo. If anyone wants to see it — the picture will be shown.


In the evening, a huge picture of Tukun surrounded the wall. How beautiful.

Looks like Zheng's pink eyes, blue HTS TS long ears.


Sraka on the wall is surprised after evening

Look. He said to be quiet.


82.

// Original page 45
[[page-45]]

Stevetby dad. Isn't that beautiful?


Sue, it's beautiful. Is this your great Zhong kid?


'Ror


'Did you open the lock and find your color-ticking box?


Al Dad. Zheng's baby. '


He said the receipt didn't bring Zheng's baby. You yourself.

You got it. The key on the table. You've got the key open. You're together.

You committed many crimes. First crime — you opened my drawer. second

Crime — Images on Wall. The third crime — you lied. DEY

Crime — calling your little aunt a bitch.


"I didn't say, Dad. The crow says. "


'Kack didn't say anything. The crow can't say anything. You made it.

You said you blamed the crow. I don't want to punish the kids. But mine.

Looks like you should be punished. How about punishment?


"I don't know, Dad. '


What the hell are you? Are you scared?


I'm so scared when I'm trapped in the bathroom. '


'Yeah, so do! You'll be stuck in the bathroom. until

No, you'll be locked in the bathroom. '


The tears are coming. She cried so sad and said when to stop.

In the bathroom?


'This is it now. Come with me? "


'Will the lamp come out, the lights light?


'The end will come. '


Tukk just kept quiet and said, ee ee


'No, I shouldn't. But children should not be guilty of this crime. He

Because of that. Crime is punishment. The culprit is no big kid. I see.

Do you understand? [ Map on page 16]


'I'm coming. [ Map on page 16]


He put his son in the bathroom and shut the door. First thought


83

// Original page 46
[[page-46]]

Don't light it up. If the bathroom is dark, the punishment will be more painful. Right at the end

Take it. It's a bit scary AGA Farler.


The receipt went to her writing table. Very well with the boy.

We're in trouble. You don't know what to do. I was born in 1950.

That's why his own writing is not going on. 'So bad!

You're here with me. It was beautiful. Now and

Not moving.


The receipt was shocked at the writing table. No papers.

He looked at the table, looked on the floor. No, nothing. Sometimes.

He put the paper in Almir to save it from TM.

Keep it. Maybe he opened the book. No, write

No papers. Only that — not Almirra. That's great.

It was in books. Tomorrow was a bad time. You're reading the book at night. Now

Nothing. Not a book. Where are we going? What's the matter?


Mr. Rashid entered the kitchen and called for a tired throat, TA Muna.


Muna El.


He said, give me a cup of tea — Turn around.

Look back and see if you can see any change. Something terrible.

It happened.


Muna wonders where are the walls?


It appeared — There was no picture on the wall of the house — There's a frame, but there's no pictures.

In 5 minutes, everyone discovered — no papers at home.

A GR paper is not.


Muna ran and opened Stale's almara. St এসে within Almirr

Hold it. Land documents. Nothing. To separate family expenses

It was in the tin coach. No GroupWise. The whole house is empty.


He said, "Do you understand?


Muna scaredly said I can.


'What's your guess?


Munnabor says Zheng's kid ate.


Eighty.

// Original page 47
[[page-47]]

Should we punish them?

// Original page 48
[[page-48]]

"Let the phone call. Ask me to come. '


'What will he do?


hearall talking about what to do or what to do. Well,


Munna said where's Tukun?


He is being punished. [ Map on page 16]


What's the punishment?


I'll tell you what the punishment is. Now, you're gonna tell the fat man to come. ♪ Coming to MRA ♪

Tell me. My hands are shaking. What's wrong


She's alone in the bathroom. He's constantly crying. With the shirt.

Looked out. He wants to scream — Dad, what I have said all these days

I made it up. I won't. There's nothing you say. It's all lies.

All the FRG pix is getting serious. Because he knows what's happening is true.

I'm trying to lie


Make sure you look sweet!


It was awful. Looked at Zheng's kid, into the base.

He's sitting. He's clearly seen in the dark. What's he talking about? Very.

Light throat. Fisher is talking. It's so unclear.


'You can talk


Take it.


Why haven't you said that?


I don't like talking. It hurts. '


What are you talking about now?


'You only suffer for me because of this. Listen,

I've decided — I'm leaving AR obeyer


What did you say?


I left ARP


Why?


If I'm me, you'll have problems. What do you need?

The door is locked in the bathroom and it's full of rage in your house

// Original page 49
[[page-49]]

I ate. "


- What?


"The work is not right. Wrong. Zheng's child is never wrong.

I've made mistakes because of anger.

I'm going back everything I ate. Let's go YAP


- Stay back. A little. '


No, no. I'll go. '


Zheng's baby has left crying. He's a kid.

I'm going to cry.


There's a fraud on the door of the bathroom.


She's scared, who?


Me, I'm a rat. They're really trying to keep you in the bathroom.

I'm sorry. I came to dare you. '


- Thank you. I'm trapped in the bathroom.


Zheng's kid says he's going to see what's going on. Listen, I'm right.

I've done it, and I'll never come to you again. Your problem for me.

Here we go. Isn't it?


Here we go.


I think you tell your father that you've been hurt all this time.

You made it up, and you'll say A, it's your problem.


I'll tell you. '


The truth will be told — what is the way people believe in lies.

People are strange creatures. '


The bathroom lights.


The receipt's voice was heard.


Canadian


'Are you scared too? '


Ausole dad. '


He opened the bathroom door and took the baby in his arms. Mother by Dad


84.

// Original page 50
[[page-50]]

He's waiting. My mom's got a little boy. Mother behind them. Minister's mother

In arms


It blew up and said everything I've been saying,

Dad. I'll never make you a new one again.


You should look at your wife. Muna Taal Culture

Turn.


She looked at him and said, "Rao little Fupu!"

That's crazy. Never again.


I cried and cried. I'm sorry. of Opala

It's a tear in my eyes. He hesitates to say, "Kun, maybe you are.

That's right. Maybe Zheng's child has something to eat. Maybe.

We're wrong. 4


You're not wrong. It's all I made.


They're all in the bedroom. He saw receipts.

It's okay. It's all in Alimir's book. The photos of the wall have returned —

Just a picture is wrong. This is down there.


From looking back on the long-term photo

He said we haven't been traveling for a long time. In the house,

Prisoner. Looks like that's why we all got a bit upset —

How about the banding together to the sea?


She said it's better, Dad.


GEN?


Then it's been a long time. How strange their house was to change — Just

The photo went there. This photo is often taken by Mr. Rashid.

You're worried. Look at the picture what he thinks.

Don't tell anyone. Nobody even wants to know. This world is so weird! The Earth.

Don't ask for all the secrets.


== Chapter 6

// Original page 51
[[page-51]]

Eki Kouro!

www.morchana.com

http://www.co.com/forum

Swaman Ham

s4suman.com

Creed With

On Aust $19.95D

http://www.cp-ions.com/orgkkkkk
