= ˆgGNi Ici evwo
DcbÅvm
:doctype: book
:toc: left
:toclevels: 2
:sectnums:
:icons: font
:source-highlighter: highlight.js
:description: Translated from Bangla (23 pages)


== Chapter 1

// Original page 1
[[page-1]]

DcbÅvm

nygvqƒb AvnGg`

ˆgGNi Ici evwo

Avwg gviv ˆMwQ, bvwK gviv hvwœQ@‰LGbv eySGZ cviwQ bv| gGb nq, gviv ˆMwQ| g†Z AeÕ©v ˆ^GK AGjŒwKKfvGe hviv ˆeuGP IGV, ZvG`i

g†ZzÅ-AwfæZv nq| ‰i bvg ‰bwWB (wbqvi ˆW^ ‰ÝwcwiGq´Ö)| evsjvq ‘g†ZzÅ-AwfæZv’| Zviv mevB ˆ`GL, jÁ¼v ‰K myoGãi ˆfZi w`Gq

Zviv hvGœQ| myoGãi ˆkl gv^vq ˆPvLauvavGbv AvGjv| ‰B AvGjvi PzÁ¼GKi gGZv AvKlÆYx ÞgZv| KwVb AvKlÆGY AG®¬i gGZv AvGjvi w`GK

‰wMGq ˆhGZ nq|

Avwg ˆKvGbv myoã ˆ`LwQ bv| myoGãi gv^vq AvGjvI bv| ZGe wbGRGK ˆ`LGZ cvwœQ| RxweZ AeÕ©vq ˆKvGbv gvbyGliB (Avqbvi mvgGb

Qvov) wbGRGK ˆ`Lvi Dcvq ˆbB| Avwg ˆhGnZz wbGRGK ˆ`LwQ, KvGRB aGi wbGZ cvwi, Avwg gviv ˆMwQ| wbGRGK ˆ`GL Avgvi gvqv

jvMGQ| nvmcvZvGji ˆKweGb Wvb w`GK cvk wdGi Avwg ÷Gq AvwQ| bvGK AwÝGRGbi bj| euv nvGZ KÅvGbvjv jvMvGbv| KÅvGbvjv w`Gq

iGî×i wkivq mÅvjvBb hvGœQ| mÅvjvBGbi mGã AÅvw´ŸevGqvwUK| bvwfi wbGP ‰KUv dzGUv Kiv nGqGQ| ˆKb KGiGQ, ˆK RvGb|

ˆgvevBj ˆdvGbi kõ nGœQ| Avwg ˆhw`K wdGi ÷Gq AvwQ, kõUv AvmGQ Zvi DGÎŸv w`K ˆ^GK| i‚webvi ˆgvevBj ˆdvb| Avwg gv^v bv

NywiGqB i‚webvGK ˆ`Ljvg| ˆivMxi AÅvGUbGWG´Ÿi wWfvGb ˆm ÷Gq AvGQ| wWfvbUv ˆQvU| Zvi ‰KUv cv weQvbvi evBGi| AbÅ cv

ˆMvUvGbv| ˆePvwi evwjk Qvov NygvGœQ|

i‚webv NyGgi gGaÅB ejj, ˆK?

Icvk ˆ^GK ejj, Avwg RyuB| fvBqv ˆKgb AvGQ?

fvGjv AvGQ| ˆZvgvi fvBqv fvGjv|

fvBqv wK NygvGœQ?

NygvGœQ, NygvGœQ| ivwL, ˆKgb? AvB jvf BD|

i‚webv ˆUwjGdvb nvGZ NywgGq coj| NywgGq hvIqvi AvMgynƒGZÆ ejj, cÉwZevi ivZ wZbUvq ˆUwjGdvb| w`Gb Kx Kwim? dvK BD weP!

i‚webvi ˆUwjGdvGbi K^vevZÆv ÷Gb KGqKUv wRwbm Õ·Ó¡ nGjv| g†Z gvbyl ˆUwjGdvGbi Icvk ˆ^GK ˆh K^v eGj, Zvi K^v Õ·Ó¡ ÷bGZ

cvq | ˆKD gGb gGb ˆKvGbv K^v ejGj Zv-I ÷bGZ cvq| ‰ RbÅB ‘dvK BD weP’ ‰Z cwiÓ•vi ÷GbwQ|

‰Z ivGZ RyuB bvGgi ˆK ˆUwjGdvb Kij? wPbGZ cviwQ bv ˆZv!

bZzb cwiGeGk wbGRGK AfÅÕ¦ Kivi ˆPÓ¡v KiwQ| RxweZ AeÕ©vq Avgvi PvicvGki c†w^ex ˆhgb wQj, ‰Lb ˆZgb ˆbB| wKQy àYMZ

cwieZÆb nGqGQ| AvGjv AGbK ˆKvgj nGq ˆMGQ| ˆjG´Ö nvjKv ˆRwj jvwMGq Qwe ZzjGj Qwe ˆhgb ˆKvgj ˆ`Lvq, ˆZgb| i‚webv ˆh

wWfvGb ÷Gq AvGQ, Zvi wKbviv ˆKvgj| BsGiwRGZ mnR KGi ewj@ˆbv kvcÆ ‰GRm|

Uzc KGi kõ nGjv| i‚webvi nvGZ aiv ˆgvevBj ˆdvb ˆgGSGZ cGo ˆMGQ| ˆhLvGb cGoGQ, Zvi KvGQB ivwk wePvGii ‰KUv eB|

eBGqi bvg mvb mvBb| ˆjwLKv wj´£v àWgÅvb| NygvGZ hvIqvi AvGM cv `ywjGq `ywjGq i‚webv ‰B eB cowQj ‰es ejwQj, AvøhÆ, me

wgGj hvGœQ| Kx wjGLGQ cGo ˆkvbve?

Avwg ejjvg, bv|

Avgvi eyGK ZLb cÉPí Pvc| wbtk¼vGm KÓ¡ nGœQ| `yUv Kvb e®¬| ˆµÏb AGbK IcGi DVGj Kvb ˆhgb e®¬ nq, ˆZgb| Avwg Nb Nb

ˆXuvK wMGj KvGbi Ze`v fve KvUvGbvi ˆPÓ¡v KiwQ, ‰B mgq ivwkdGji K^v ÷bGZ BGœQ KGi bv|

Avgvi ‘bv’ ˆKvGbv KvGR w`j bv| i‚webv coGZ ÷i‚ Kij, ‘wjeËvbm jvf wccj, evU ˆ` ˆnBU jvRÆ ò×vDW&m&|’ ‰B ÷bQ?

÷bwQ|

Avgiv gvbyl cQ±` KiGjI RbZv cQ±` Kwi bv| AviI ˆkvGbv, wjeËv BR Aj jvf AÅv´£ weDwU AÅv´£ myBUGbm AÅv´£ jvBU| coGZ

coGZ i‚webv wmMvGiU aivj| ‰gwbGZB wbtk¼vm wbGZ cviwQ bv, Zvi Ici wmMvGiGUi KUz M®¬| Avwg KÑv¯¦ Mjvq ejjvg, wmMvGiU

ˆdGjv|

i‚webv ejj, `yUv Uvb w`Gq ˆdGj ˆ`e|

UqGjGU PGj hvI, UqGjGU `iRv e®¬ KGi wmMvGiU UvGbv|

i‚webv eB nvGZ UqGjGU XzGK ˆMj| Avwg ejjvg, `iRvUv e®¬ KGiv, wµÏR|

i‚webv ejj, cvie bv|

wKQyÞY ci Zvi nvwmi kõ ÷bjvg| ivwkdGji eBGq ‰gb Kx ˆjLv ^vKGZ cvGi ˆh ˆm wLjwLj kõ KGi nvmGQ! UqGjU ˆ^GK

wmMvGiGUi `yMÆ®¬ AvmGQ, ‰i mGã hyî× nGqGQ wdbvBGji M®¬| UqGjGUi ˆewmGbi ‰KUv Kj bÓ¡, mvivÞY wUcwUc KGi cvwb cGo| cvwb

covi kõUv AvGM KwVbfvGe KvGb jvMZ| gGb nGZv, bL w`Gq ˆKD eÐÅvKGevGWÆ AuvPovGœQ|

‰Lb AeÕ©v wf®²| ˆewmGbi Kj w`Gq cvwb coGQ, Avwg Zvi kõ cvwœQ| kõUv AvgvGK cxwoZ KiGQ bv, eis ÷bGZ fvGjv jvMGQ| ˆhb

cvwbi ˆduvUv covi kõUvq jyKvGbv MÍ¸ AvGQ| MÍ¸Uv Kx fveGZB gGb coj| MÍ¸Uvi bvg ‘dzo~r’| cvwbi ˆduvUv coGQ Avi dzo~r kõ nGœQ|

Lye ˆQvUGejvq evev MÍ¸ KiGQb, Avwg Zvi mvgGb `yB nuvUz ˆMGo KzKzGii gGZv eGm AvwQ| gy™¬ nGq MÍ¸ ÷bwQ@

‰K ˆ`Gk wQj nvRvi nvRvi, jÞ jÞ, ˆKvwU ˆKvwU cvwL| cvwLi h¯¨Yvq AwÕ©i nGq ivRv ejGjb, ‘me cvwL RvGj e±`x KGiv| cÉKví

Rvj evbvI|’ ivRvi üKzGg cÉKví Rvj evbvGbv nGjv| Rvj w`Gq me cvwL AvUGK ˆdjv nGjv| RvGji ‰K ˆKvbvq ‰KUv wQ`Ë wQj, ‰Uv

ˆKD jÞ KGiwb| wQ`Ë w`Gq ‰KUv njy` cvwL dzo~r KGi ˆei nGq ˆMj|

‰B eGj evev MÍ¸ ^vgvGZB Avwg ejjvg, Zvici?

// Original page 2
[[page-2]]

evev ejGjb, dzo~r|

Avwg ejjvg, dzo~r Kx?

evev ejGjb, dzo~r KGi AvGiKUv cvwL PGj ˆMGQ|

Avwg ejjvg, Zvici?

evev ejGjb, dzo~r|

Zvici Kx?

dzo~r|

Avwg ˆek wKQyÞY AGcÞv KGi ejjvg, Zvici?

evev ejGjb, dzo~r|

Avwg ejjvg, meàGjv cvwL KLb ˆei nGe?

evev ejGjb, ˆhw`b ZzB gviv hvwe, ˆmw`b| Zvi AvGM bv

Avwg gviv ˆMwQ|

evevi K^vbymvGi me cvwL Rvj ˆ^GK ˆei nGqGQ| ZGe ZvG`i dzo~r KGi Iovi kõ ˆiGL ˆMGQ| UqGjGUi Kj dzo~r dzo~r KGiB

hvGœQ| kõUv wgwÓ¡ jvMGQ| MvGQi cvZv ˆ^GK wkkwki covi gGZv| AvGjv ˆhgb ˆKvgj nGq ˆMGQ, kõI ˆKvgj nGqGQ| hZ mgq hvGe,

ZZB gGb nq ˆKvgj nGe|

AvGjv I kõ@`yGUvB Bw±`ÉqMÉvnÅ| g†Z gvbyGli Bw±`Éq ˆKv^vq? AvGjv KxfvGe ˆ`LwQ? kõB ev KxfvGe ÷bwQ? Avgvi Avjv`v AwÕ¦Z½I

ˆbB| Avwg ‰K RvqMv ˆ^GK AvGiK RvqMvq hvwœQ bv| RxweZ AeÕ©vq f„Z-ˆcÉGZi Qwe i‚webvi mGã ˆ`GLwQ|nii Qwe Zvi Lye cQ±`|`Å

üBc AÅv´£ `Å ˆdÑk, IGgb, dÌvBGW `Å ^viwUb&^&@‰me QweGZ f„Z-ˆcÉGZi Avjv`v AwÕ¦Z½ AvGQ| Zviv ‰K RvqMv ˆ^GK AvGiK RvqMvq

ˆhGZ cvGi| ZvG`i MvGq Kvco ^vGK| b™² f„Z-ˆcðx Klgbv ˆ`wLwb|

‰Lb eySGZ cviwQ, ‰B AskàGjv wVK bv| hvi ˆKvGbv AwÕ¦Z½ ˆbB, Zvi RvgvKvco civiI wKQy ˆbB|

cvGki weQvbvq LPgP kõ nGœQ| i‚webv DGV eGmGQ| ˆPvL WjGQ| ˆgGSGZ cGo ^vKv ˆgvevBj ˆdvbGmU DwVGq wbGq nvB ZzGj Kx

ˆhb ˆ`Lj| mgq ˆ`Lj| eo KGi nvB ZzGj NygvGZ wMGqI ˆMj bv; UqGjGUi w`GK iIbv nGjv| nvGZ wmMvGiGUi cÅvGKU|

wmMvGiGUi M®¬ cvwœQ| cÉ^gevi ˆhgb ZxeË ˆjGMwQj, ‰Lb ˆZgb jvMGQ bv; eis fvGjv jvMGQ| i‚webv wbGRi gGb K^v ejGQ| Zvi

‰Kv ‰Kv K^v ejvi evwZK AvGQ| ˆm ejGQ, MvavUvi KvGb gjv ˆ`Iqv `iKvi| Mvavi evœPv Mvav| ˆPŒóàwÓ¡ Mvav|

i‚webv weGkl KvDGK Mvav ejGQ, bvwK wbGRi gGb ‰gwb K^v ejGQ? ‰Lb eySGZ cviwQ, i‚webv Mvav ejGQ KvG`iGK| KvG`i

AvgvG`i evmvi ˆKqviGUKvi| ˆm mÁ¿eZ ˆPvi, ZGe Mvav bv| Mvaviv ˆPvi nGZ cvGi bv|

g†Z gvbyl AGbÅi gGbi K^v aiGZ cviGe, ‰Uv Rvbv wQj bv| ˆUwjcÅvw^ wbGq AGbK K^v nq| AvGgwiKvi ‰K BDwbfvwmÆwUGZ ˆZv

ˆUwjcÅvw^ wbGq MGelYvi RbÅ Avjv`v wWcvUÆGg´ŸB AvGQ| MGelYvi djvdj kƒbÅ| Zviv ejGZ evaÅ nGqGQ@gvbyGli ˆUwjcÅvw^K ÞgZv

ˆbB| ‰Lb eySGZ cviwQ, ˆUwjcÅvw^ g†ZzÅi cGii eÅvcvi|

`iRv LyGj ‰KRb bvmÆ XzGKGQ| ˆm ˆPvLgyL KzuPGK ejj, ˆK wmMvGiU LvGœQ?

ev^i‚g ˆ^GK i‚webv ejj, Avwg LvwœQ|

ˆKweGb wmMvGiU ˆLGZ cviGeb bv|

ˆKweGb ˆZv LvwœQ bv| UqGjGU LvwœQ|

UqGjGUI ˆLGZ cviGeb bv| wmMvGiU ˆLGZ nGj nmwcUvGji evBGi wMGq ˆLGZ nGe|

i‚webv ejj, ivZ wZbUv cuqZvwÍÏGk Avwg nvmcvZvGji evBGi ˆKv^vq hve! à´£viv aGi wbGq wMGq AvgvGK hw` ˆic KGi, ZLb Dcvq

Kx nGe?

‰B bvmÆ AvRB cÉ^g wWDwUGZ ‰GmGQ, i‚webvi K^v ejvi fwãi mGã ˆm cwiwPZ bq| bvmÆ LvwbKUv nKPwKGq ˆMj| Avwg jvBUvi

R¾vjvGbvi kõ ÷bjvg| ci ci `yUv wmMvGiU i‚webv Lvq bv| w«¼Zxq wmMvGiU ˆm aivj bvmÆGK ivwMGq ˆ`Iqvi RbÅ| i‚webv Mjv DuwPGq

ejj, wmÕ¡vi, ‰K KvR Ki‚b, Avgvi wei‚G«¬ ‰KUv KgGµÏBb KGi w`b|

bvmÆ gyL kî× KGi Avgvi weQvbvi w`GK ‰wMGq ‰Gjv| KÅvGbvjv ˆ`Lj, mÅvjvBGbi wUDe ˆbGoGPGo ˆ`GL nVvr wPrKvi Kij, gÅvWvg,

ˆivMx gGb nq gviv ˆMGQ!

i‚webv ‰B AvZÆwPrKvGii ˆKvGbv Reve w`j bv| bvmÆ Avevi ejj, gÅvWvg, Avmyb| ˆivMx gGb nq gviv ˆMGQ|

i‚webv ejj, gGb nq gGb nq ejGQb ˆKb? wWDwU Wvî×viGK ˆWGK Avbyb| Wvî×vi ˆ`GL ejyK|

bvmÆ `Ë‚Z Ni ˆQGo ˆei nGZ wMGq `iRvq evwo ˆLj| UqGjU ˆ^GK i‚webv ejj, KÅvjvm ˆjwW! `iRv-Rvbvjv ˆfGO ˆdjGQ|

Avwg wKQyUv Õ¼wÕ¦ cvwœQ| Avgvi AeÕ©v ‰Lb mevB RvbGe| AbÅ iKg DGîRbv, AbÅ iKg KgÆKví ÷i‚ nGe|

i‚webv Avgvi mvgGb `uvwoGq AvGQ| Avwg ZvGK ˆ`GL gGb gGb AGbKevi ejv ‰KwU evKÅ AveviI ejjvg, ‰KRb Zi‚Yx ‰Z my±`i

nq KxfvGe!

‰B AwZ i…ceZxi mGã Avgvi weGq wVK KGib eo gvgv nvweeyi ingvb| gMevRvGi Zuvi ‰KUv dvGgÆwm AvGQ| dvGgÆwmi mGã ˆgvevBj

ˆdvGbi eÅemv| ‰B dvGgÆwmGZ i‚webv ‰K m®¬ÅvGejvq ‰Gm ejj, KzwoUv Kov NyGgi Ilya w`b ˆZv|

eo gvgv ejGjb, ‰ZàGjv NyGgi Ilya w`Gq Kx KiGeb?

i‚webv ejj, myBmvBW Kie| KzwoUvq nGe bv?

‰ZàGjv NyGgi Ilya w`GZ cvie bv|

‰KUv w`GZ cviGeb? ‰KUv w`b| KzwoUv dvGgÆwmGZ hve, mevi KvQ ˆ^GK ‰KUv KGi wKbe| cwikÉg ˆewk nGe, Kx Avi Kiv? IqvKÆ

di ˆW^| KvGRi wewbgGq g†ZzÅ| Avcwb ‰gb AevK nGq ZvwKGq AvGQb ˆKb? bvwK ‰KUv NyGgi IlyaI wewò× KiGeb bv|

// Original page 3
[[page-3]]

eo gvgv ‰KUv UÅveGjU w`Gjb| i‚webv UÅveGjU gyGL w`Gq Zuvi mvgGbB cvwb Qvov wMGj ˆdjj| UÅveGjGUi `vg w`Gq ˆMj bv| i‚webv

ciw`b wbR ˆ^GKB ‰j UÅveGjGUi `vg w`GZ|

eo gvgv ˆhGKvGbv gvbyGli mGã AwZ`Ë‚Z NwbÓ¤Zv KiGZ cvGib| i‚webvi mGã NwbÓ¤Zv nGZ Zuvi ˆgvGUB mgq jvMj bv| gvGSgGaÅB

ˆm gvgvi dvGgÆwmGZ mvb™ÏvGm ˆPvL ˆXGK eGm ^vKZ|

Avgvi mGã i‚webvi gvgvi dvGgÆwmGZB cÉ^g ˆ`Lv| cÉ^g ˆ`LvGZ eyGK avØvi gGZv jvMj| KvD´ŸvGii ˆcQGb njy` cwi eGm AvGQ|

Avwg ^GZvgGZv ˆLGq `uvwoGq AvwQ| i‚webv ejj, Kx jvMGe, ejyb? Zvi cÉGk² Avgvi ^GZvgGZv fve KvUj bv, eis AviI evoj| Avwg

ˆMwQ gvgvi ˆLuvGR| gvgv dvGgÆwmGZ ˆbB| ‰B njy` cwiGK Kx eje? eo gvgvi ˆLuvGR ‰GmwQ? ‘eo gvgv’ ejGj wK ‰B ˆgGqwU wPbGe?

bvwK eo gvgvi bvg eje? Avgvi gv^vi ˆfZi ‰ZB RU cvwKGq ˆMGQ ˆh wKQyGZB eo gvgvi bvg gGb KiGZ cvijvg bv|

i‚webv ejj, ˆKvGbv KvR Qvov dvGgÆwmi mvgGb nuv KGi `uvwoGq ^vKGeb bv| my±`ix ˆgGq ˆ`LGjB ZvwKGq ^vKvi wKQy ˆbB| ‰B eGj

i‚webv nvB Zzjj| nvB ZzjGj c†w^exi me gvbylGKB KzrwmZ ˆ`Lvq| ‰B ˆgGqwUi ˆejvq gGb nGjv, Zvi nvB ˆZvjvI ‰KwU bv±`wbK `†kÅ|

‰B njy` cwii mGã eo gvgv Avgvi weGqi eÅeÕ©v KxfvGe KiGjb, ˆmUv fvGjvgGZv Rvwb bv| weGqi K^vevZÆv AGbK `ƒi ‰GMvGbvi ci

i‚webvi mGã PvBwbR ˆiÕ¡zGiG´Ÿ ˆLGZ ˆMjvg| i‚webv myÅGc PzgyK w`Gq ˆVuvU euvwKGq fzi‚ KzuPGK AGbKÞY myÅGci evwUi w`GK ZvwKGq ˆ^GK

ejj, myÅGc ˆZjvGcvKvi M®¬ cvGœQb?

Avwg ejjvg, bv|

PU KGi bv eGj ˆdjGjb? ˆZjvGcvKvi MvGqi M®¬ ˆKgb, ˆmUv RvGbb?

bv

i‚webv nvB ZzjGZ ZzjGZ ejj, hw` mwZÅ mwZÅ Avcbvi mGã Avgvi weGq nq, ZvnGj ˆZjvGcvKv aGi Zvi MvGqi M®¬ AvcbvGK

ˆkuvKve|

AvœQv|

Avcbvi mGã Avgvi weGq nIqvi mÁ¿vebv LyeB Kg| AGbGKi mGãB Avgvi weGqi K^v nGqGQ| KGqKevi ‰bGMRGg´Ÿ chÆ¯¦ nGq

ˆMGQ, wK¯§ weGq nqwb| AvwgI ZvG`i AvswU ˆdiZ w`Bwb| ‰Lb ˆh AvswU cGi AvwQ, ˆmUv ‰bGMRGgG´Ÿi AvswU| AvswUi cv^iUv nxivi|

KZ eo nxiv, ˆ`GLGQb?

üu |

Avmj nxiv bv| bKj nxiv| AvGgwiKvb Wvqg´£| AvøhÆ, Avcwb ˆZv ˆ`wL ˆZjvGcvKvi M®¬Iqvjv myÅc ˆLGq ˆkl KGi ˆdGjGQb|

AvGiK evwU LvGeb? AvgviUv ˆLGq ˆdjyb|

bv

LvGeb bv ˆKb? Avwg gyL w`GqwQ ˆmB RbÅ? Avcbvi wK gGb nGœQ ˆh, Avgvi kixGii RxevYy Avcbvi kixGi XzGK hvGe?

Avwg Pzc KGi iBjvg| i‚webv ejj, ‰KRb Õ¼vgx Zvi Õ¨xGK hLb MÉnY KGi, Zvi RxevYymnB MÉnY KGi| AvgvGK weGq KiGZ PvBGj,

AvgvGK RxevYymnB MÉnY KiGZ nGe| ivwR AvGQb?

nuÅv, ivwR AvwQ|

ZvnGj Avgvi gyL ˆ`Iqv myÅcUv ˆLGq ˆdjyb| cyGivUv ˆLGZ nGe bv| KGqK PvgP ˆLGjB nGe|

Avwg myÅGci PvgGP gyL w`jvg| nVvr i‚webvi w`GK ˆPvL coGZB ˆ`wL, ˆm A«¿zZ `†wÓ¡GZ AvgvGK ˆ`LGQ| ‰gb A«¿zZ `†wÓ¡GZ Avgiv

mvaviYZ ‰KRb AvGiKRGbi w`GK ZvKvB bv|

‰B gynƒGZÆ i‚webv Avgvi mvgGb| Zvi ˆPvGL ˆmB cyGivGbv A«¿zZ `†wÓ¡| wKQyUv ˆKŒZ„nj, wKQyUv weÕÃq, AGbKLvwb ˆe`bv|i‚webv Avgvi

KcvGj nvZ ivLj| ˆmB nvZ kxZj, bv Dú@eySGZ cvijvg bv| g†Z gvbyGli nqGZv ev Õ·kÆvbyf„wZ ˆbB| eÅvcviUv Avgvi KvGQ cwiÓ•vi

nGœQ bv| g†Z gvbyl hw` ˆ`LGZ cvGi, hw` ÷bGZ cvGi, ZvnGj Õ·kÆvbyf„wZ Zvi ˆKb ^vKGe bv? Avwg ˆZv M®¬I cvwœQ| KcvGji Ici ivLv

Zvi nvZ ˆ^GK wmMvGiGUi M®¬ AvmGQ|

i‚webv weoweo KGi ejj, Mvax bvmÆ| eGj Kx, gGb nq gviv ˆMGQ| gvbylUv Avivg KGi NygvGœQ| ‰B bvmÆUvGK Kvco LyGj cvQvq jvwï

w`Gq nvmcvZvj ˆ^GK ˆei KGi ˆ`Iqv `iKvi|

i‚webvi K^v ˆkl nIqvi AvGMB bvmÆ Wvî×vi wbGq XzKj| Wvî×vi Avgvi bvwo aij| ZvGK ˆZgb wePwjZ gGb nGjv bv| ˆm ˆPvGLi

cvZv LyGj ˆPvGLi gwYGZ UPÆ ˆdjj| ˆPvGL UPÆ aiGj Avgiv AvGjv Qvov wKQyB ˆ`wL bv| wK¯§ Avgvi ˆ`LGZ mgmÅv nGœQ bv| bvGmÆi fxZ

gyL ˆ`LwQ, i‚webvi ˆKŒZ„njx gyL ˆ`LwQ, Wvî×vGii wbweÆKvi gyL ˆ`LwQ|

Wvî×vi Avgvi weQvbvi cvGk eGm wQj| ˆm DGV `uvovj| AÅvcÉGbi cGKU ˆ^GK ˆÕ¡G^vGÕ•vc ˆei KGi Avevi ˆiGL w`j| LvwbKUv

BZÕ¦Z fwã KGi ejj, gÅvWvg, ˆcGk´Ÿ gviv ˆMGQ|

Wvî×vi gGb nq i‚webvi KvQ ˆ^GK AvZÆwPrKvi Avkv KGiwQj| ˆm iKg wKQy bv ˆ`GL Wvî×vi wewÕÃZ|

i‚webv wmMvGiGUi cÅvGKU nvGZ wbGZ wbGZ ejj, AvgvGK wmMvGiU aivGZ nGe|

Wvî×vi ejj, aivb, wmMvGiU aivb| Amyweav ˆbB|

i‚webv ejj, Ii ˆPvGLi cvZvUv e®¬ KGi w`b| ZvGK ˆ`GL gGb nGœQ, Avgvi w`GK ZvwKGq AvGQ|

bvmÆ ˆPvGLi cvZv e®¬ Kij bv, ZGe Pv`i w`Gq AvgvGK cyGivcywi ˆXGK w`j| ‰GZ Avgvi ˆ`LGZ Amyweav nGœQ bv| mewKQy AvGMi

gGZvB ˆ`LwQ| ‰i A^Æ, Avwg ˆ`Lvi RbÅ Avgvi kixi eÅenvi KiwQ bv| i‚webv wmMvGiU awiGq KvkGZ KvkGZ ejj, UvBg KZ ˆ`Lyb ˆZv

Wvî×vi mvGne? KLb gviv ˆMGQ, mevB RvbGZ PvBGe|

wZbUv QqPwÍÏk wgwbU|

i‚webv ejj, KZÞY AvGM gviv ˆMGQ eGj Avcbvi aviYv?

Wvî×vi ejj, ˆewk AvGM bv| AÍ¸ AvGM|

i‚webv ejj, ‰gb ˆKvGbv mÁ¿vebv wK AvGQ, ˆm Pv`i mwiGq DGV eGm cvwb ˆLGZ PvBGe?

// Original page 4
[[page-4]]

Wvî×vi-bvmÆ gyL PvIqv-PvIwq KiGQ| i‚webv ejj, Avcbviv PGj hvb, AvgvGK ‰KUz ‰Kv ^vKGZ w`b|

Wvî×vi ejj, ˆWWewW mwiGq ˆbIqvi eÅeÕ©v Kwi|

i‚webv ejj, bv|

bvmÆ ejj, Avgiv PGj ˆMGj Avcwb fq cvGeb|

i‚webv ejj, fq cve ˆKb? RxweZ gvbylGK fq cvIqvi eÅvcvi AvGQ| g†Z gvbylGK fq cvIqvi wKQy ˆbB| ˆm hw` ˆRGM DGV eGj,

‰K ™Ïvm cvwb Lve, Avwg Lye Õ¼vfvweK Mjvq eje@Vv´£v cvwb ˆ`e, bv bigvj?

Wvî×vi ejj, Avcbvi AvñxqÕ¼Rb KvDGK Lei ˆ`e?

i‚webv ejj, Lei AvwgB ˆ`e| Avcbviv ˆW^ mvwUÆwdGKGUi eÅeÕ©v Ki‚b|

Wvî×vi I bvmÆ PGj hvIqvi ci ci i‚webv Avgvi gyGLi Ici ˆ^GK Pv`i mwiGq w`j| cvwbi ˆevZj ˆ^GK cvwb ˆLj| weiî× Mjvq

ejj, ‰LGbv mÅvjvBb hvGœQ| ‰Bme LyGj bvB ˆKb! Mvav bvmÆ, Mvav Wvî×vi!

i‚webv ˆgvevBj wbGq Zvi weQvbvq Avav ˆkvqv nGq eGmGQ| Zvi nvGZ wmMvGiGUi cÅvGKU| bZzb ‰KUv wÕ¡K AvOzGji cvGk aiv|

‰LGbv R¾vjvGbv nqwb|

nÅvGjv| KvG`i KvG`i? Avgvi Mjv ÷Gb eySGZ cviQ bv, Avwg ˆK? LvgvLv ˆK ˆK KiQ| ˆZvgvi ˆgvevBGj ˆZv Avgvi bvg IVvi

K^v| bvg DGVGQ wKbv ˆ`GLv|

gÅvWvg, DGVGQ|

Avwg `yRGbi K^vevZÆvB cwiÓ•vi ÷bwQ| KvG`Gii Mjv ÷Gb gGb nGœQ, Zvi Nyg ‰LGbv KvGUwb|

KvG`i, gb w`Gq ÷bQ?

wR, gÅvWvg|

ˆZvgvi mÅvi gviv ˆMGQb|

Kx meÆbvk! B®²v wjÍÏvwn Iqv B®²v BjvBGn ivwRDb| KLb gviv ˆMGQb?

KLb gviv ˆMGQb, ‰Uv BÁ·GUÆ´Ÿ bv| gviv ˆMGQb, ‰Uv BÁ·GUÆ´Ÿ| Zzwg Mvwo cvVvI, Avwg evmvq wdie| nU kvIqvi ˆbe|

mevBGK Lei w`e, gÅvWvg?

‰Z ivGZ KvDGK Lei ˆ`Iqvi wKQy ˆbB| mevB NygvGœQ| mKvj mvGo AvUUvi ci Lei ˆ`Iqv ÷i‚ KiGe|

wR, AvœQv, gÅvWvg|

mevB evmvq Avmvi RbÅ eÅÕ¦ nGe| ZvG`i ejGe, ˆWWewW evmvq ˆbB|

nvmcvZvGj AvGQ eje?

bv ejGe Kei nGe ˆZvgvi mÅvGii evevi KeGii cvGk| ˆWWewW wbGq Mvwo iIbv nGq ˆMGQ|

AGbGKB ˆhGZ PvBGe|

hviv ˆhGZ PvBGe, Zviv wbR eÅeÕ©vq hvGe| eyGSQ?

cwjb AvcyGK wK Lei ˆ`e?

cwjb NygvGœQ bv?

wR|

cwjb Lye Õ¼vfvweK ˆgGq bv, ‰Uv Zzwg RvGbv|

Nyg fvwOGq ZvGK `ytmsev` ˆ`Iqvi Kx AvGQ? ‰ iKg ‰KUv Lei ÷bGj ˆm Kx KiGe, ˆmUv ZzwgI RvGbv bv, AvwgI Rvwb bv| mKvj

bqUvi mgq Zzwg iweGK ˆUwjGdvb KiGe| ˆm bqUvi AvGM IGV bv| ˆWWewW wbGq MÉvGgi evwo hvIqv, `vdGbi eÅeÕ©v Kivi `vwqZ½ Zvi|

Avwg ‰Lb Avgvi ˆgvevBj Ad KGi w`wœQ| WÈvBfvi ‰LbB cvVvI|

wR, gÅvWvg|

Kuv`Q bvwK? Kuv`vi wKQy bvB| R¯ÃvGj giGZ nq| Zzwg giGe, Avwg gie| ˆZvgvi cyiv ˆMvÓ¤x giGe, Avgvi cyiv ˆMvÓ¤x giGe| wVK bv?

wR, gÅvWvg|

Avgvi ˆkvevi NGii ‰wm ˆQGo NiUv Vv´£v KGi ivGLv| evmvq wdGi Avwg wKQyÞY ˆiÕ¡ ˆbe|

wR, gÅvWvg|


i‚webv mÁ·ƒYÆ b™² nGq Kvco e`jvGœQ| Avwg ‰KRb g†Z gvbyl, Zvi cGiI AvZGâ AwÕ©i| `iRv jK Kiv bv| ˆhGKvGbv mgq ˆh-ˆKD

ˆKweGb XzKGZ cvGi| Avwg ˆPvL e®¬ Kivi ˆPÓ¡v Kijvg, ˆPvL e®¬ Kiv ˆMj bv| me Avgvi ˆPvGLi mvgGbB NUGQ| RxweZ AeÕ©vq ˆKvGbv

wKQy ˆ`LGZ bv PvBGj ˆPvL e®¬ KiZvg, ‰Lb Zv mÁ¿e bv? mewKQyB AvgvGK ˆ`LGZ nGe?

ˆKweGbi `iRv LyGj bvmÆ XzKj| euvPv ˆMGQ, ‰i gGaÅ i‚webvi Kvco e`jvGbv nGq ˆMGQ| ˆWÈm e`jvGbvi KvRUv ˆm AZÅ¯¦ `Ë‚Z KiGZ

cvGi |

bvmÆ ejj, gÅvWvg Avcwb wK PGj hvGœQb?

üu |

ˆWWewW wbGq hvGeb bv?

i‚webv ejj, bv| Avcbviv ˆiGL w`b|

bvmÆ nZvk ˆPvGL ZvKvGœQ| ZvGK nZvk AeÕ©vq ˆiGL i‚webv ˆei nGq ˆMj| Avgvi ejGZ BœQv KiGQ, wmÕ¡vi! Avgvi Õ¨xi eÅenvGi

Avcwb gb Lvivc KiGeb bv| ˆm ‰ iKgB| ˆWWewW ˆm ˆdGj ˆiGL hvGe bv| h^vmgGq wbGq hvGe| ˆm evmvq hvGœQ| nU kvIqvi wbGq

wKQyÞY ‰wm i‚Gg wekÉvg KiGe| Zvici me eÅeÕ©v nGe|

// Original page 5
[[page-5]]

Avwg ejGZ PvwœQ, wK¯§ ejGZ cviwQ bv| ‰Uv ˆZv wVK bv| AvgvGK K^v ˆkvbvi kwî× ˆ`Iqv nGqGQ, K^v ejvi kwî× ˆKb ˆ`Iqv nGe

bv?

ˆKweGb AviI `yRb XzGKGQ| ‰iv IqvWÆeq ev ‰ iKg wKQy| nvGZi KÅvGbvjv ˆ^GK bj mwiGq, ˆeW ˆUGb wbGq hvGœQ| ˆKv^vq wbGœQ,

ˆK RvGb| Avwg nVvr AwÕ©i ˆeva Kijvg, ˆeGWi mGã mGã AvwgI wK hve? bv wK AvgvGK ‰ NGiB ^vKGZ nGe| Avgvi Avjv`v ˆKvGbv

kixi ^vKGj, nvZ-cv ^vKGj Avgvi ˆWWewW ˆhLvGb hvGœQ, ˆmLvGb ˆnuGU ˆnuGU PGj ˆhZvg| Avgvi ˆZv kixi ˆbB| hv AvGQ Zv Lye mÁ¿e

ˆPZbv| ˆPZbv wK ‰K RvqMv ˆ^GK AvGiK RvqMvq ˆhGZ cvGi? bvwK Avgvi ˆPZbv ‰B NGiB mxgve«¬| ‰LvGb hv nGe, ÷ay Zv-B Avwg

Rvbe | evBGii wKQy Rvbe bv, ‰Uv ˆZv wVK bv! ˆfwi AvbGdqvi|

hv fq KGiwQjvg Zv-B, Avwg ˆKweb-NGi AvUKv cGo AvwQ| IqvWÆeq `yRb Ni cwiÓ•vi KiGQ| gc w`Gq gyQGQ| NGi ˆÕ·É KiGQ|

ev^i‚g ayGœQ| g†ZzÅ wK A÷wP welq? ˆhLvGb ˆKD gviv hvq, ˆmB RvqMv wK A÷wP nGq hvq?

IqvWÆeq `yRb wbGRG`i gGaÅ K^v ejGQ| `yRGbi MjvB PbgGb| K^v eGjI Avb±` cvGœQ| K^vi welqeÕ§ nGjv, ZvG`i mÅvGii ‰K

wfwWI ˆgvevBGj Qvov nGqGQ| wfwWIUv Lye Õ·Ó¡ bq, ZGe ZvG`i mÅviGK ˆevSv hvq| wK¯§ ˆgGqUvGK ˆPbv hvq bv| bvGmÆi ˆcvkvK civ

ˆgGq| ‰KeviI Zvi ˆPnviv ˆ`Lv hvqwb|

‰KRb ejj, wfwWI wVKgGZv KiGZ cvGi bvB| cÉ^GgB `yRGbi ˆPnviv ˆ`LvGbv DwPZ wQj| evwKUv cGi ˆ`LvGj PjZ|

w«¼ZxqRb ejj, KÅvGgivI wVKgGZv aiGZ cvGi bvB| nvZ KuvcGQ|

ˆgGqUv fÅv fÅv KGi KvbGQ| Kx RbÅ, ‰Uv ˆZv eySjvg bv| cÉ^Gg ˆZv nvwmlywk wQj|

nvwmlywk eySjv ˆKgGb, gyL ˆZv ˆ`L bvB?

nvwmi kõ ÷bjvg bv?

gGb nq cÉ^GgI KvbGQ| gyL bv ˆ`Lv ˆMGj nvwmi kõ, Kv±`Gbi kõ me ‰K iKg|

‰Uv Kx ejjv?

nuÅv| ‰Kevi Avgvi cyjvi Kv±`b ÷Bbv ˆ`ŒGo wMqv ˆ`wL, ˆm nvmGZGQ|

RwUj K^v ejjv ˆZv| nvwm Avi Kv±`Gbi kõ ‰KB|

Zviv gƒj AvGjvPbv ˆ^GK mGi ˆMGQ| nvwm-Kv®²vi kõ AÅvbvjvBwmm nGœQ|

AvøGhÆi eÅvcvi, Avwg ZvG`i mÅvGii wfwWI ˆ`Lvi RbÅ AvMÉn ˆeva KiwQ| wfwWI ˆ`GL ˆgGqUv nvmGQ bv Kuv`GQ, ˆmUv Rvbvi ˆPÓ¡v|

g†ZzÅi ciI wK ˆhŒbGPZbv ˆ^GK hvq? wbøqB ^vGK| bv ^vKGj ˆbvsiv wfwWI ˆ`Lvi BGœQ nGZv bv| ˆKvGbv hywî×GZB g†ZzÅi cGii

ˆhŒbGPZbvi welqUv MÉnY Kiv hvGœQ bv| cyi‚l hyeZx Zi‚Yxi cÉwZ kvixwiK AvKlÆY ˆeva KGi, Zvi KviY cÉK‡wZ Pvq gvbeRvwZi AwÕ¦Z½

wUGK ^vKzK, Zviv eskweÕ¦vi Ki‚K|

‰KRb g†Z cyi‚l ˆKvGbv g†Z Zi‚Yxi cÉwZ ˆhŒb AvKlÆY ˆeva KiGe bv| KviY, ZvG`i eskweÕ¦vGii wKQy ˆbB| kixiB ˆbB, eskweÕ¦vi

AGbK cGii eÅvcvi|

IqvWÆeq `yRb PGj ˆMGQ| Avwg ˆKwebNGi AvUKv cGo AvwQ| Avgvi kixi ˆKv^vq Rvwb bv| i‚webv ˆKv^vq Kx KiGQ, Zv-I Rvwb bv|

g†ZzÅi ci AwZ AGPbv ‰K RMGZ Avwg XzGK cGowQ| cÉ^g weG`k ögGYi mGã ‰i wKQyUv wgj AvGQ| weG`GkI evwoNi AvGQ, gvbyl

AvGQ; wK¯§ meB wKQyUv Avjv`v| IG`i fvlv Avjv`v, wbqgbxwZ Avjv`v| ivÕ¦vNvU meB AGPbv|

weG`k ögGY ‰KRb MvBW Lye cÉGqvRb| ˆh mewKQyi mGã cwiPq KwiGq ˆ`Ge| ivÕ¦vNvU ˆPbvGe| `kÆbxq RvqMv ˆ`LvGe| ciKvGjI

AvgvG`i ‰KRb MvBW `iKvi| Avwg ˆZv RvbZvg, g†ZzÅi mgq g†Z AvñxqÕ¼RGbiv Pviw`GK wfo KGi| ZvG`i cÉavb ˆPÓ¡v AcwiwPZ fzeGb

g†GZi hvòv mnR KGi ˆ`Iqv|

Avgvi meGPGq ˆQvU dzdz KÅvbmvGi gviv wMGqwQGjb| ZxeË eÅ^vq w`bivZ c÷i gGZv ˆMvOvGZb| eÅ^v KgvGbvi ˆKvGbv Ilyacò Zuvi

RbÅ KvR KiwQj bv| Zuvi KÓ¡ eYÆbvi AZxZ| g†ZzÅi N¥Ÿv LvGbK AvGM nVvr Zuvi me eÅ^vGe`bv PGj ˆMj| Zuvi gyL AvbG±` Sjgj KGi

DVj | Avwg Avi eo gvgv ZLb Zuvi NGi| dzdz eo gvgvi w`GK ZvwKGq ejGjb, Avgvi wPrKvGi AwZÓ¤ nGq mevB AvgvGK ˆQGo wMGqGQ,

ˆKD Avgvi NGi DuwKI ˆ`q bv| ÷ay Avcwb w`Gbi ci w`b AvmGQb, N¥Ÿvi ci N¥Ÿv eGm ˆ^GKGQb, Avgvi KÓ¡ ˆ`GL ˆPvGLi cvwb

ˆdGjGQb| Avcbvi mGã ‰B cvMjUv AvmGQ| cvMjv ˆ`Œo w`Gq hv, Avgvi RbÅ ‰KUv jwj AvBmwò×g wKGb Avb| jvj iGOi Avbwe|

(ˆQvU dzdz AvgvGK me mgq cvMjv WvKGZb|)

jvj iGOi jwj AvBmwò×g wKGb ‰Gm ˆ`wL cwiwÕ©wZ mÁ·ƒYÆ wf®²| gvbylfwZÆ Ni| ˆK ‰KRb DuPz Õ¼Gi KvGjgv coGQb| ˆQvU dzdz evg

KvZ nGq ÷Gq AvGQb| wZwb ˆPvL eo eo KGi ‰w`K-Iw`K ˆ`LGQb| nVvr weÕÃGq Awff„Z nIqvi gGZv KGi ejGjb, AvÁÃvwR AvmGQb|

AvÁÃvwR AvgvGi wbGZ AvmGQb|

KvGjgv cvV e®¬ nGq ˆMj| mevi `†wÓ¡ dzdzi w`GK| dzdz ‰Kw`GK ZvwKGq AvMÉn wbGq RvbGZ PvBGjb, AvÁÃvwR, ‰Kv AvmGQb? Avi

ˆKD AvGm bvB?

dzdzi g†Z AvÁÃvwR nqGZv Reve w`Gjb, Avgiv ˆmB Reve ÷bGZ cvijvg bv| dzdz ejGjb, nuÅv, ‰Lb mevBGi ˆ`LGZwQ| nuÅv AvÁÃvwR,

ZvG`i mvjvg w`GZ fzGj ˆMwQ| Avmmvjvgy AvjvBKzg|

nVvr dzdz AvZwâZ Mjvq ejGjb, AvÁÃvwR, ‰B ˆgGqUv ˆK? Avgvi fq jvMGZGQ, Avgvi fq jvMGZGQ| ‰Uv ˆK?

eo gvgv ejGjb, ˆRvGe`vGi Kvev kwiGdi w`GK gyL KGi ÷qvGq `vI|

mevB KvGjgv cvV KGiv, eGjv, jv Bjvnv BÍÏvÍÏvü gynvÁÃv`yi ivmyjyÍÏvn|


ˆQvU dzdzGK wbGZ mevB ‰GmwQj| Zuvi AcwiwPZ ‰KRb gwnjvI ‰GmwQGjb| AvgvGK wbGZ ˆKD AvGmwb| g†ZGK c^ ˆ`wLGq ˆbIqvi

RbÅ gGb nq ˆKD AvGm bv| meUvB AmyÕ© gvbyGli KÍ¸bv| Avwg ˆKweGbi ˆgGSGZ wZbUv ˆZjvGcvKv Qvov wKQy ˆ`LwQ bv| ‰KUvi MvGqi is KzrwmZ mv`v| i‚webv ‰B ˆZjvGcvKvUv ˆ`LGj jvd w`Gq weQvbvq DGV coZ| Zvi gGZ, ‰B c†w^exi meGPGq KzrwmZ, meGPGq ˆbvsiv,

meGPGq RNbÅ, meGPGq fqsKi cÉvYxi bvg ˆZjvGcvKv|

// Original page 6
[[page-6]]

i‚webvi aviYv, g†ZzÅi ci ˆm AekÅB ˆ`vRGL hvGe| Zvi ˆ`vRGL ˆKvGbv Avāb ^vKGe bv| AmsLÅ ˆZjvGcvKv wKjwej KiGe| wKQy

ˆZjvGcvKv ^vKGe mv`v iGOi| ‰B ˆZjvGcvKviv Zvi Mv ˆeGq DVGZ ^vKGe|

Avwg ˆgGSi ˆZjvGcvKvi w`GK ZvwKGq ^vKGZ ^vKGZB nVvr ˆ`wL eviv±`vq PGj ‰GmwQ| jÁ¼v eviv±`v ˆPvGLi mvgGb fvmGQ| ˆKweb

ˆ^GK Kx KGi eviv±`vq PGj ‰GmwQ, Zv Rvwb bv|

eviv±`v duvKv| IqvwKUwK nvGZ ‰KRb cywjk AwdmviGK ˆ`LwQ| Bwb nvmcvZvGji Wvî×vGii mGã K^v ejGZ ejGZ ‰GMvGœQb|

AvøGhÆi eÅvcvi, cywjk Awdmvi K^v ejGQb AvgvGK wbGq|

ˆWWewW wiGjwUfG`i nvGZ UÇv´Ödvi Kiv nqwb ˆZv?

‰LGbv bv|

ˆW^ wiGcvGUÆ Avcbviv Kx wjLGQb?

ˆWW wiGcvUÆ ‰LGbv ŠZwi nqwb|

Avwg ˆW^ wiGcvGUÆi Kwc wbGq hve| ˆWWewWi myiZnvj nGe| Avgiv mvmGcÙ KiwQ Vv´£v gv^vq Lyb Kiv nGqGQ|

eGjb Kx? mvmGcÙ ˆK?

‰LGbv Rvwb bv| Z`¯¦ nGœQ|

cywjk Awdmvi Avgvi ˆKweGbi `iRvi mvgGb `uvovGjb| ˆKweb bÁ¼i 321| `iRvq Avgvi bvg ˆjLv, W. BdGZLvi‚j Bmjvg|

g†Z gvbyGliv wbtk¼vm ˆdGj bv| KviY, evZvm ˆ^GK ZvG`i AwÝGRb ˆbIqvi wKQy ˆbB| Zvi ciI wbGRi bvGgi w`GK ZvwKGq Avwg

ˆQvë wbtk¼vm ˆdjvi gGZv Kijvg| Avwg ‰KwU wek¼we`ÅvjGqi dwjZ c`v^Æwe`Åvi AÅvGmvwmGqU cÉGdmi| Avwg ‰B c†w^exGZ wQjvg, ‰Lb

ˆbB| nvmcvZvGji ˆKweGbi `iRvq bvgUv ÷ay SzjGQ|

c†w^exGZ Avwg SvGgjvgyî× wQjvg| g†ZzÅi ci bvbv SvGgjvq RovwœQ| ‰Lb RvbwQ, ˆKD AvgvGK Lyb KGiGQ| myiZnvj nGe| ‰KRb

Wvî×vi bvGK i‚gvj ˆPGc Avgvi b™² kixGii cvGk `uvwoGq ^vKGeb| ˆWvg KvUvKvwU KiGe| cvKÕ©jxi Lv`Å ˆKŒUvq ˆei KGi cixÞvi RbÅ

cvVvGe|

cwòKvi wbøqB wbDR nGe| cwòKvIqvjviv ‰B aiGbi LeGii RbÅ AGcÞv KGi ^vGK| cÉwZw`b LeGii dGjvAvc Qvcv nq| cuvP

ˆ^GK Qq w`Gbi gv^vq Lei Qvcv e®¬| mevB mewKQy fzGj hvq|

cywjk Awdmvi ˆKweGbi `iRv LyGj NGi DuwK w`Gjb| ˆPvLgyL KzuPGK ejGjb, NGi wmMvGiGUi M®¬| wmMvGiU ˆK ˆLZ?

ˆcGkG´Ÿi Õ¨x| ZvGK AGbKevi wbGla Kiv nGqwQj| gwnjv DMÉ Õ¼fvGei, KviI K^vB ˆkvGbb bv|

wZwb ˆKv^vq?

ejGZ cviwQ bv| ˆfviGejv KvDGK wKQy bv RvwbGq PGj ˆMGQb|

Zvi bÁ¼i wK AvGQ? Avwg K^v eje|

ˆWGÕ• wbøqB AvGQ| Avmyb, bÁ¼i ˆei KGi w`wœQ|

Avwg ‰B ˆKweGb AvwQ| Avcwb ˆUwjGdvb bÁ¼iUv wbGq Avmyb| AvgvGK ‰K Kvc eÐÅvK Kwd ˆ`Iqv wK mÁ¿e nGe?

Avwg ˆKvGbv cywjk AwdmviGK KvQ ˆ^GK ˆ`wLwb| Avgvi AvñxqÕ¼RGbi gGaÅI cywjk mvwfÆGm ˆKD ˆbB| i‚webvi ‰K PvPvGZv fvB

AvGQ, cywjGki ‰AvBwR| ‰KeviB wZwb AvgvG`i evmvq ‰GmwQGjb| Avav N¥Ÿvi gGZv wQGjb, ˆmB Avav N¥Ÿv wZwb ò×gvMZ ˆgvevBj

ˆdvGb K^v eGjGQb| ‰Z weiî× gyGL Avwg KvDGK K^v ejGZ ˆ`wLwb|

‰B cywjk AwdmviGKI gGb nGjv weiî×| ÷ay weiî× bv, A‹ahÆ| cÉ^Gg wWfvGbi Ici emj| wKQyÞGYi gGaÅB wWfvb ˆQGo ev^i‚Ggi

`iRv LyGj DuwK w`j| ˆmLvb ˆ^GK wdGi ‰Gm ˆivMxi weQvbvi cvGki ˆUweGj ivLv IlyGai ˆevZj nvGZ wbGq ÷uKGZ jvMj|

wRwbm ÷uKvi evwZK Zvi gGaÅ cÉej eGj gGb nGœQ| ˆm mewKQyB ÷uKGQ| KÑGmU LyGj ˆm i‚webvi wKQy ˆcvkvK Szj¯¦ ˆcj|

ˆcvkvKàGjv ÷uKj| ˆivMxi IlyGai ˆUweGji WÈqvi AGbK UvbvUvwb KGi Lyjj| ˆmLvGb i‚webvi wmMvGiGUi cÅvGKU I jvBUvi| ˆm

wmMvGiGUi cÅvGKU ÷uKj| cÅvGKU LyGj wmMvGiU ˆei KGi wmMvGiU ÷uKj| jvBUviUv KGqKevi R¾vwjGq-wbwfGq jvBUvi ÷uKj|

AÅvwiGRvbv ˆÕ¡U BDwbfvwmÆwUGZ Avwg hLb wc‰BPwW Kwi, ZLb KjGÁ¼v bvGgi ‰KUv wUwf wmwiqvj ˆ`LZvg| KjGÁ¼v nGjv wmwiqvGji

bvqK | ˆm wewf®² nZÅvKvGíi Z`¯¦ KGi| wcUvi dK bvGgi ‰KRb AwfGbZv KjGÁ¼v PwiGò Awfbq KGiwQGjb| AmvaviY Awfbq| ZuviI

÷uKvi evwZK wQj| Z`¯¦ KiGZ wMGq hv ˆ`LGZb, Zv-B ÷uKGZb| ˆewki fvM mgq wRGf jvwMGqI ˆ`LGZb| ‰KUv `†GkÅ wZwb mvmGcGÙi

evwoGZ wMGq ˆmG´Ÿi ‰KUv wkwk ˆcGjb| h^vixwZ ÷uGK ˆ`LGjb| wRGf LvwbKUv jvwMGq ‰w`K-Iw`K ZvwKGq wbGRi Rvgvq LvwbKUv ˆÕ·É

KiGjb | ˆkl chÆ¯¦ ‰B ˆmG´Ÿi wkwk AvmvwgGK aiGZ f„wgKv ivLj|

weG`Gk covGkvbvi RwUj mgqUvq KjGÁ¼v wmwiqvj AvgvGK AZÅ¯¦ Avb±` w`GqGQ| ˆ`navix gvbyGli AGbK AvbG±`i eÅeÕ©vB c†w^exGZ

AvGQ| bvUK-wmGbgv-eB-Mvb-wPòKjv-msMxZ@ciKvGj ‰gb eÅeÕ©v wK AvGQ? ev AvmGjB wK AvGQ? Avb±` ‰es DGîRbvq Aaxi nGq

KjGÁ¼vi gGZv ˆKvGbv wmwiqvj ˆ`Lvi eÅeÕ©v wK AvGQ? g†ZG`i wmGbgv ˆ`Lvi RbÅ QweNi AvGQ? jvBGeËwi AvGQ?


Kwd wbGq ‰KRb IqvWÆeq XzGKGQ| Zvi nvGZ ‰KUzKiv KvMR| gGb nq i‚webvi ˆUwjGdvb bÁ¼i| cywjk Awdmvi Kwdi gM nvGZ wbGjb|

hv ˆfGewQjvg, Zv-B| wZwb KwdGZ PzgyK w`Gq bvbvfvGe M®¬ ÷uKGjb| Zvi fve ˆ`GL gGb nGœQ M®¬ cQ±` nqwb| wZwb gM bvwgGq ˆiGL

ˆUwjGdvb bÁ¼i ˆjLv KvMRwU nvGZ wbGjb| bvGKi mvgGb aGi KvMGRiI M®¬ wbGjb| Avwg Avbw±`Z, wKQyÞGYi gGaÅB i‚webvi wgwÓ¡ Mjv

÷bGZ cve| g†ZzÅi ciI ‰B myweavUv nGqGQ@ˆKD ˆUwjGdvb KiGj `yw`GKi K^vB ˆkvbv hvq|

wgGmm i‚webv K^v ejGQb?

BGqm|

ˆKgb AvGQb, gÅvWvg?

fvGjv| ü Avi BD?

Avgvi bvg Lwjj| Lwjjyi ingvb| Avwg BdGZLvi mÅvGii WvBGiÙ Qvò| mÅviGK Lye fvGjvgGZv wPbZvg|

// Original page 7
[[page-7]]

Avcbvi mÅviGK wPbGZb, fvGjv KiGZb| ‰Lb Avwg eÅÕ¦, ˆUwjGdvb ivLwQ|

wµÏR, gÅvWvg, wµÏR| QvòveÕ©vq Lye wecG` cGo Avwg mÅvGii KvQ ˆ^GK wZb nvRvi UvKv avi KGiwQjvg| UvKvUv ˆdiZ ˆ`Iqv nq

bvB | Avcbvi KvGQ ˆdiZ w`GZ PvwœQ|

ˆdiZ w`GZ nGe bv| IGK evB |

LU kõ nGjv| i‚webv ˆUwjGdvb ˆiGL w`GqGQ| cywjk Awdmvi Lwjj ‰evi Kwdi KvGc PzgyK w`j| wZbevi PzgyK, cÉwZeviB Zvi

ˆPvLgyL KzuPGK ˆMj| ˆm AveviI ˆUwjGdvb Kij| Avgvi aviYv wQj, i‚webv ˆUwjGdvb aiGe bv| ˆUwjGdvb aij|

gÅvWvg, Avwg Lwjj ejwQ| BdGZLvi mÅvGii WvBGiÙ Õ¡zGW´Ÿ|

‰KUz AvGM K^v nGqGQ| Avevi ˆKb ˆUwjGdvb KiGjb? Õ¡zwcW!

gÅvWvg, ivM KiGeb bv| Avgvi mGã Avcbvi K^v ejGZB nGe| Avcbvi AbÅ weKÍ¸ bvB|

K^v ejGZB nGe ˆKb?

mÅvGii g†ZzÅGZ ‰KwU AcNvZ gvgjv nGZ hvGœQ| ‰KUv ˆUwjGdvGb cywjkGK Zvi g†ZzÅmsev` RvbvGbv nGqGQ ‰es ejv nGqGQ, ‰wU

‰KwU cwiKwÍ¸Z nZÅvKví|

ˆK nZÅv KGiGQ?

‰LGbv Rvwb bv| Avgvi Ici `vwqZ½ cGoGQ Z`¯¦ KGi ˆei Kivi|

Z`¯¦ Ki‚b| AvgvGK weiî× KiGQb ˆKb! nvReÅv´£ gviv ˆMGQ, Avwg AvcGmU|

gÅvWvg, AvcbvGK ˆZgb AvcGmU gGb nGœQ bv|

AvcGmU ˆ`LvGZ nGj AvgvGK Kx KiGZ nGe? ˆfD ˆfD KGi Kuv`GZ nGe?

AwZ wcÉqRGbi g†ZzÅGZ mevB `ytwLZ nq, ˆPvGLi cvwb ˆdGj| ˆKD ˆewk, ˆKD Kg| ZGe ˆKDB ˆWWewW nvmcvZvGj ˆdGj evwoGZ

PGj hvq bv|

Avcbvi wK aviYv, Avwg Lyb KGi ˆWWewW ˆdGj evmvq jywKGq AvwQ?

gÅvWvg, Avgvi ˆm iKg aviYv bq|

ZvnGj ˆUwjGdvb ivLyb, AvgvGK weiî× KiGeb bv|

AvœQv gÅvWvg, ˆUwjGdvb ivLjvg| ˆkvGKi mgq weiî× Kivi RbÅ Av¯¦wiKfvGe `ytwLZ|

Lwjj ˆUwjGdvb ˆiGL AveviI Vv´£v KwdGZ àGb àGb wZbevi PzgyK w`j| Zvi wZbevi Kwdi KvGc PzgyK ˆ`Iqv ˆ`GLB eyGSwQ ˆh

AveviI ˆUwjGdvb KiGe| KjGÁ¼vi mGã ‰B cywjk AwdmvGii wgj AvGQ| KjGÁ¼v mvmGcÙGK AwZ webxZfvGe weiî× KiZ| ‰KB cÉk²

wZb-Pvievi KGi jävq bZ nGq ejZ, wQt wQt, ‰B cÉk² ˆZv AvcbvGK AvGMI KGiwQ| Avevi Kijvg| Avgvi AvmGj gv^vi wVK bvB|

nÅvGjv, gÅvWvg, Avwg Lwjj|

Avcwb ˆZv eGjGQb Avi weiî× KiGeb bv| ˆKb ˆUwjGdvb KiGjb?

ˆQvU ‰KUv cÉk² wQj, gÅvWvg| ‰B cÉGk²i Dîi ˆcGj Avi Kie bv| ZGe gqbvZ`G¯¦i wiGcvUÆ Lvivc nGj cÉk² Kie|

gqbvZ`¯¦ gvGb?

myiZnvj nGjv gqbvZ`¯¦| BsGiwRGZ eGj ˆcvÕ¡gGUÆg| mÅvGii wfGmiv cixÞv Kiv nGe|

ˆmUv KLb Kiv nGe?

AvR w`Gbi gGaÅB Kiv nGe| ˆmUv KLb, Zv ˆZv Rvwb bv| Wvî×viiv KiGeb| ‰Lb gÅvWvg Avcbvi cÉk²Uv wK Kie?

nuÅv, Ki‚b ‰es AvgvGK `qv KGi gywî× w`b|

gÅvWvg, ˆKweGb Ilyacò ˆhLvGb ivLv nq, ˆmLvGb ‰KUv wmMvGiGUi cÅvGKU Avi ‰KUv jvBUvi ˆcGqwQ| wmMvGiGUi cÅvGKUUv wK

Avcbvi?

nuÅv, Avgvi|

Avi jvBUvi? jvBUviUvI wK Avcbvi?

wmMvGiGUi cÅvGKU hvi jvBUvi ZviB ^vKGe, ‰UvB ˆZv jwRKÅvj|

gÅvWvg, AGbK mgq jvBUvi AGbÅi KvQ ˆ^GK avi Kiv nq|

jvBUvGi wK ˆKvGbv mgmÅv?

jvBUvGi ˆKvGbv mgmÅv bq| wmMvGiGUi cÅvGKGU mgmÅv|

Kx mgmÅv?

Avcbvi wmMvGiGUi cÅvGKGU mvZUv wmMvGiU wQj|

‰GZ ˆKvGbv mgmÅv? ‰gb ˆKvGbv AvBb wK AvGQ ˆh ˆeGRvo msLÅvi wmMvGiU ^vKGZ cviGe bv, wKsev cÉvBg bÁ¼i msLÅvi wmMvGiU

^vKGZ cviGe bv?

gÅvWvg, ‰gb ˆKvGbv AvBb bvB| ZGe mvZUv wmMvGiGUi gGaÅ wZbUv Avjv`v| wZbUv wmMvGiGUi ˆfZi MuvRv fiv|

eySjvg|

MuvRv fiv wmMvGiU Avcwb ˆKvGïGK msMÉn KGib, ‰Uv Avgvi Rvbv `iKvi|

Avcwb LvGeb? wZbUv MuvRvi wmMvGiU wbGq hvb|

gÅvWvg, AvgvGK wbGq iwmKZv Kivi cÉGqvRb bvB| Avwg ˆZgb iwmK gvbylI bB| MuvRvi wmMvGiU Avcwb ˆKvGïGK msMÉn KGib, Zv

Avgvi Rvbv cÉGqvRb ‰B RbÅ ˆh Avcwb gv`GKi ˆKvb Pò×wUi mGã hyî×, Zv Rvbv| MuvRv Qvov AbÅ ˆKvGbv WÈvM wK ˆbb? Bqvev, wÕ·W,

ˆnGivBb|

Avwg wbGR ˆ^GK AvcbvGK wKQyB eje bv| BD Õ¡zwcW! dvB´£ BU AvDU|

// Original page 8
[[page-8]]

i‚webv ˆUwjGdvb jvBb ˆKGU w`GqGQ| Lwjj Vv´£v Kwdi Kvc Avevi nvGZ wbGqGQ| ‰evi PzgyK w`j `yevi| ‰i A^Æ nqGZv i‚webvGK

ˆm Avi ˆUwjGdvb KiGe bv| LwjjGK Avbw±`Z gGb nGœQ ‰es ˆm eo ˆKvGbv AvbG±`i RbÅ AGcÞv KiGQ| ‘eo Avb±`’Uv Kx nGZ cvGi?

nVvr KGiB Zvi ‘eo Avb±`’ Avgvi KvGQ Õ·Ó¡ nGq ˆMj| ˆm Kx fveGQ, eySGZ cviwQ| Zvi cwiKÍ¸bv eySGZ cviwQ| Zvi gv^vi

ˆfZi Še`yÅwZK So nGœQ| gwÕ¦GÓ•i ‰K Ask ˆ^GK mxgvnxb msLÅvi BGjKUÇb AbÅ AsGk hvGœQ, Avevi wdGi AvmGQ| AwZ Þz`Ë me

Še`yÅwZK wefe ŠZwi nGœQ| Þz`Ë wK¯§ Õ·Ó¡| ‰i A^Æ Kx, Zv eySGZ cviwQ| BGjKUÇGbi AÅvw´ŸGgUGi cwRUÇb ŠZwi nGœQ, wbGgGlB wgwjGq

hvGœQ| gwÕ¦Ó• cÉPzi AwÝGRb MÉnY KGi Zv RvbZvg, ˆmLvGb mvgvbÅ cwigvGY IRb (O3) ŠZwi nq, Zv RvbZvg bv|

Lwjj Kx fveGQ, Zv ‰Lb Avgvi KvGQ Õ·Ó¡| eo ˆh AvbG±`i RbÅ ˆm AGcÞv KiGQ, ˆmB Avb±` g†ZzÅwelqK| nZÅvKvixGK ˆm

duvwmGZ SzjvGe, ‰B Avb±`|

‰i AvGM ˆm AvUUv LyGbi gvgjv Z`¯¦ KGiGQ| ‰B AvURGbi gGaÅ mvZRGbi duvwmi üKzg nGqGQ| cuvPRGbi duvwm nGq ˆMGQ|

`yRGbi ‰LGbv nqwb| Zviv duvwmi RbÅ AGcÞv KiGQ| ˆh ‰KRGbi duvwmi üKzg nqwb, ˆm ˆeKmyi Lvjvm ˆcGq ˆMGQ| Zvi bvg wRjvwb|

Lwjj wbwøZ, wRjvwb ˆRvov LyGbi ˆnvZv| cÉgvGYi AfvGe Qvov ˆcGq ˆMGQ| ‰B fqsKi Acivax AveviI Lyb KiGe| Lwjj ZvGK

jÞ ivLGQ| ˆm AveviI aiv LvGe| duvwmi nvZ ˆ^GK wRjvwbi gywî× ˆbB|

Avgvi g†ZzÅi welqUv wbGq ˆm ˆh AvRB Z`G¯¦ ˆbGgGQ, Zv bq| Pvi w`b AvGMB Z`G¯¦ ˆbGgGQ| Avwg nvmcvZvGj fwZÆ nIqvi ci

ˆ^GKB ˆm jÞ ivLGQ| ˆLuvRLei ÷i‚ KGiGQ| Zvi ˆPvL AvbG±` PKPK KiGQ, AviI ‰KRbGK ˆm duvwmGZ SzjvGZ cviGe| ˆmB

AvGiKRGbi bvg i‚webv|

LwjGji gv^vi ˆfZi duvwmi `†kÅ| i‚webvGK duvwmGZ ˆSvjvGbv nGœQ| RÍÏv` i‚webvi gyL KvGjv Kvco w`Gq ˆXGK w`j| i‚webv ejGQ,

‘bv, bv, bv|’ duvwmi `†kÅ ˆ`Lvi RbÅ DcwÕ©Z ˆRjvi mvGne nvGZi i‚gvj ˆdGj w`Gjb| ‰UvB wmMbÅvj| i‚webv duvwmGZ SzjGQ| Zvi

AvjZvciv dmÆv cv `yjGQ|

AvøhÆ, ‰Lb LwjGji gv^vq KweZv NyiGQ| BsGiwR KweZv bq, evsjv KweZv| ‘AvU eQi AvGMi ‰Kw`b’| cÉ^g ˆ^GK bq, nVvr

‰GKKUv jvBb|

‘ˆKvGbvw`b RvwMGe bv Avi!’

ˆm ‰B KweZvwU BsGiwR AbyevG`i ˆPÓ¡v KiGQ| Abyev` cQ±`gGZv nGœQ bv eGj ˆm wbGRi Ici ˆiGM hvGœQ| ‘ˆKvGbvw`b RvwMGe bv

Avi’@wk DBj ˆbfvi IGqK Avc| ‘jvkKvUv NGi ÷Gq Nygvq ‰evi’@‘bvI wk BR wÕÏwcs Ab `Å gMÆ ˆUe&j&|’

Lwjj Avgvi Qvò wQj| wK¯§ ZvGK wPbGZ cviwQ bv| RyuB bvGgi ˆh ˆgGqUv ivZ wZbUvq ˆUwjGdvb KGiwQj, ZvGK wPbGZ cvwiwb|

RxweZ AeÕ©vi wKQy ÕÃ†wZ wK bÓ¡ nGq ˆMGQ?


2.

jvkKvUv NGii cwjw^b weQvGbv ˆbvsiv ˆUweGj Avgvi kixi wPr nGq AvGQ| MvGq ˆKvGbv Kvco ˆbB| ˆUwej ˆ^GK wdbvBGji KwVb M®¬

AvmGQ| NGii Rvbvjv AvGQ| Rvbvjvq njy` iGOi c`Æv SzjGQ| c`Æv ˆbvsiv| ˆmLvGb wKQy eo eo bxj iGOi gvwQ eGm AvGQ| gvwQàGjv

wKQyÞY eGm ^vGK Avevi IovDwo KGi c`Ævi Ici eGm| NGii PviUv ˆ`qvGji ‰KUvq PzbKvg Kiv nGqGQ| ˆmLvGb ˆKD ˆbvsiv K^v

wjGLGQ| ˆbvsiv K^vUv@‘‰BLvGb giv jvGki ˆcv`... nq’| ˆh K^vUv wjGLGQ, ˆm wbGRGK A®¬KvGi ivLGZ PvBGQ bv| gnr evYxi wbGPB

ˆm wjGLGQ@BwZ Rwmg| Zvi wbGP ˆgvevBj ˆdvGbi bÁ¼i|

NGi wbøqB Amnbxq Mig| gyGL i‚gvj ˆPGc `uvovGbv Wvî×vi `i`i KGi NvgGQ| Wvî×vGii ˆPnviv my±`i| ˆdÌçKvU `vwo| ˆPvGL

ˆmvbvwj Pkgv| Wvî×vi gvGS gvGS gv^v DuPz KGi wmwjsdÅvGbi w`GK ZvKvGœQ| wmwjsdÅvb kõ KGi NyiGQ, ZGe ˆKvGbv evZvm cvIqv hvGœQ

bv

ˆUweGji KvGQ KuvwP I Qywi nvGZ ˆWvg `uvwoGq AvGQ| ˆWvGgi Mv Lvwj| ˆNvi K‡úeGYÆi ˆeuGU gvbyl| Zvi mviv kixGi Nb ˆjvg|

wbG`ÆGki AGcÞv| Wvî×vi ejGjb, ˆcUUv ˆKGU ÷ay Õ¡gvK ˆei KGiv| wfGmiv nGe|

ˆWvg ejj, dzmdzm-KwjRv wbKvje bv?

ejjvg ˆZv, ÷ay Õ¡gvK| ‰Z K^v eGjv ˆKb? KvR ˆkl KGiv| MiGg gviv hvwœQ|

ˆWvg ˆcU KvUvi e`Gj, dÅvGbi myBP Ad KGi w`j| Wvî×vi wÞµ¦ Mjvq ejj, dÅvb e®¬ Kijv ˆKb?

dÅvb PjGj Kvg KiGZ cvwi bv|

BqvwKÆ KGiv? dÅvb PjGj KvR KiGZ cvGiv bv|

dÅvb Pvjvqv w`GZwQ@KvUvKvwU AvdGb KGib| Avwg KvUe bv| Avi Avgvi mGã wgRvR KiGeb bv| Kvjy ˆWvg wgRvGRi avi avGi bv|

KvR KiGe bv?

bv hvb, ‘wiGcvUÆ’ KGib| Avgvi PvKwi Lvb| ˆ`wL, AvcGb KZ eo PvKwi LvGbIqvjv|

ˆWvg `iRvi w`GK ‰GMvGœQ| Wvî×vi fxZ Mjvq ejj, wVK AvGQ| dÅvb e®¬ KGiB KvR KGiv| AÍ¸GZ ˆPGZ hvI ˆKb?

Pj¯¦ dÅvb e®¬ nGqGQ| gvwQiv c`Æv ˆQGo Avgvi gyGLi PvicvGk IovDwo KiGQ| KLb bvgGe eySGZ cviGQ bv|

hZB mgq hvGœQ, Avgvi kxZ evoGQ| kxGZ kixi KuvcGQ bv, Avgvi kixi eGj wKQy ˆbB| kxGZi Abyf„wZ evoGQ|‰GKKevi Vv´£v

evZvm AvGm, ˆmB evZvm wKQyÞY Õ©vqx nq, Zvici evZvm nVvr ˆ^Gg hvq| kxZ gGb nq ‰B evZvm wbGq AvmGQ| Vv´£v evovi nvi wK

‰Ýcvbwkqvj? ZvnGj ‰KUv mgq AvmGe hLb Avgiv ‰ÝGcvGbbwkqvj ˆiLvi KuvGa PGj Avme| ˆmB mgq kxZ Amnbxq chÆvGq evoGZ

÷i‚ KiGe|

Kvjy ˆWvg KvUvKvwU ÷i‚ KGiGQ| Avgvi ˆ`LGZ BGœQ KiGQ bv| wK¯§ Dcvq ˆbB, ˆ`LGZ nGœQ| `†wÓ¡ AbÅw`GK ˆdivGbvi eÅeÕ©v ‰

RMGZ ˆbB| gvwQ ˆhgb Pviw`K ˆ`LGZ cvq, AvwgI cvwœQ|

// Original page 9
[[page-9]]

Wvî×vi ˆPvL e®¬ KGi Rvbvjvi njy` c`Ævi w`GK ZvwKGq wQj, ˆm nVvr ˆPvL ˆgGj ‰KcjGKi RbÅ keG`Gni w`GK ZvwKGq QyGU `iRv

w`Gq ˆei nGq ˆMj| Wvî×vi ˆcGU nvZ w`Gq jvkKvUv NGii eviv±`vq eGm ewg KiGQ| Avnv, ˆePviv!

Kx ˆhb nGqGQ| gynƒGZÆi RbÅ Avgvi `†wÓ¡ AÕ·Ó¡ nGq Avevi Õ·Ó¡ nGqGQ| Avwg AevK nGq ˆ`wL eo gvgvi dvGgÆwm| ‰Bgvò dvGgÆwm

ˆLvjv nGqGQ| evœPv ‰KUv ˆQGj ˆgGSGZ cvwb wQwUGq SuvU w`GœQ| eo gvgv KvD´ŸvGi eGm AvGQb| wZwb ejGjb, cwòKv ‰LGbv AvGm bvB?

KvGRi ˆQGjUv ejj, AvmGj ˆZv AvgvG`i mvgGbB ^vKZ| cwòKv wK Avwg evwo wbqv hvB?

eo gvgv ejGjb, ‰KUv mnR cÉk² KGiwQ, mnR Dîi w`we| me mgq PÅvUvs PÅvUvs| hv, ˆZvi PvKwi bU|

KvGRi ˆQGj ejj, bU nBGj bU| ˆm Ni SuvU ˆ`Iqv ˆkl KGi ejj, Pv Avbe?

Avb |

`ya-Pv, bv is-Pv?

eo gvgv weiî× Mjvq ejGjb, Avwg ˆh is-Pv LvB ZzB Rvwbm| cÉwZw`b is-Pv ‰Gb w`m| ˆKb wRGæm Kiwj, is-Pv, bv `ya-Pv?

cÉwZw`b is-Pv LvBGjI AvBR `ya-Pv LvIGbi BœQv nBGZ cvGi, ‰B RbÅ wRMvBwQ|

ˆZvi PvKwi bU, ˆeZb wbGq PGj hv|

AvcGbi Pv-Uv w`qv Zvici hvB|

KvGRi ˆQGj Ni ˆ^GK ˆei nIqvi ciciB ˆUwjGdvb evRv ÷i‚ Kij| Avwg eySGZ cviwQ, KvG`i ˆUwjGdvb KGiGQ| ˆm Avgvi

g†ZzÅmsev` w`GZ ÷i‚ KGiGQ| ‰Uv Zvi cÉ^g ˆUwjGdvb| RxweZ gvbyGli ˆKvGbv ˆUwjcÅvw^K ÞgZv ˆbB, g†ZG`i AvGQ| mevi AvGQ wK bv

Rvwb bv, A¯¦Z Avgvi AvGQ| Avwg eo gvgv I KvG`Gii ˆUwjGdvGbi K^vevZÆvq gb w`jvg| nZfÁ¼ eo gvgv ejGjb, KLb gviv ˆMGQ?

ˆkl ivGZ|

ˆWWewW wK nvmcvZvGj?

ˆR¾ bv| ˆ`Gki evwoi w`GK iIbv nGqGQ|

KLb iIbv nGqGQ?

mKvj mvZUvq|

Avwg wKQyB Rvbjvg bv, ˆWWewW ˆ`Gki evwoGZ iIbv nGq ˆMGQ?

i‚webv ˆKv^vq?

Dwb ˆiGÕ¡ AvGQb|

ˆiGÕ¡ AvGQb gvGb Kx?

ˆkveviNGi `iRv e®¬ KGi AvGQb|

i‚webvGK ˆUwjGdvb `vI|

KÅvgGb w`e? `iRv e®¬|

`iRv fvO| Kzovj w`Gq `iRv ˆKGU ˆdj|

Kx ejGQb?

nvivgRv`v Vmv, KvGb ÷bm bv? Kzovj w`Gq `iRv KvU|

‰B eGjB wZwb PU KGi DGV `uvovGjb, cÉvq mGã mGãB eyGK nvZ w`Gq KvD´ŸvGii ˆcQGb cGo ˆMGjb| nvUÆ AÅvUvK nGqGQ wbøqB|

AÕ·Ó¡ ˆMuv ˆMuv kõ nGœQ| AZÅ¯¦ wecäbK AeÕ©v| Avwg ÷ay ˆ`LwQ, mvnvhÅ KiGZ cviwQ bv| Avwg AeRvfÆvi|

ˆKvqv´Ÿvg wdwRKGmi KÑvGm QvòG`i AeRvfÆvi Kx, Zv AGbKevi cwoGqwQ| AeRvfÆvi nGœQ ‰gb ‰KRb, hvi DcwÕ©wZ Qvov ˆKvGbv

NUbv NUGe bv| wKsev NUbv NUGe wK bv, Zv AeRvfÆvGii Ici wbfÆi KiGe| gGb KGiv, AvKvGk cƒYÆP±`É| PG±`Éi cvGkB eo ‰K Lí ˆgN|

ˆKvqv´Ÿvg ˆgKvwbKm ejGQ, AvKvGki Puv` ‰KB mGã ˆgGN XvKv ‰es ˆgNgyî×| ‰KRb AeRvfÆvi hLb PuvG`i w`GK ZvKvGe, ZLbB ÷ay

wbaÆvwiZ nGe Puv` ˆgNgyî×, bv ˆgGN XvKv|

cÉ^g w`b hLb ‰B eî×‡Zv Kwi, ZLb ‰K Qvòx fGq fGq ejj, mÅvi, cyGiv eÅvcviUv fzqv eGj gGb nGœQ| Avwg ejjvg, ˆKvqv´Ÿvg

wdwRKm nGœQ mÁ¿vebvi RMr| ˆmLvGb ‰B c†w^ex, MÉn, bÞò, MÅvjvwÝiI fzqv nIqvi mÁ¿vebv AvGQ| mÁ¿vebv ˆh ‰GKevGiB ˆbB, Zv bq|

Avwg ‰Lb ˆKvqv´Ÿvg ˆgKvwbKGmi AeRvfÆvi| AvkcvGki me KgÆKví ˆm ÷ay ˆ`LGe| KgÆKvGí Ask wbGZ cviGe bv| eo gvgv

ˆgGSGZ KvZ nGq cGo AvGQb| covi mgq KvGVi ˆPqvGi evwo ˆLGq Zvi ^yZwb ˆKGU ˆMGQ| ˆmLvb ˆ^GK iî× coGQ| ‰ZÞY ˆMuv ˆMuv

kõ KiwQGjb, ‰Lb ˆmB kõI ˆbB| ZuvGK `Ë‚Z nvmcvZvGj ˆbIqv `iKvi| ˆK ˆbGe? Avwg ˆKvqv´Ÿvg ˆgKvwbKGmi AeRvfÆvi| Avgvi

KvR ÷ay ˆ`Lv|

KvGRi ˆQGjUv wdGiGQ| Zvi nvGZ PvGqi Kvc| eMGj LeGii KvMR| ‰B LeGii KvMR ˆm wKGb ‰GbGQ| ˆQGjUv eo gvgvi Õ¼fve

Lye fvGjvgGZv RvGb| eo gvgv PvGqi KvGc PzgyK bv w`Gq LeGii KvMR coGZ cvGib bv|

KvD´ŸvGi PvGqi Kvc I LeGii KvMR ˆiGL ˆm ejj, ˆMj KB! eGjB ˆm SuvUv wbGq dvGgÆwmi ˆcQGb PGj ˆMj| ˆmLvGb ˆQvU ‰KUv

Ni AvGQ| gvGS gvGS ‰B NGi ÷Gq gvgv wekÉvg ˆbb, KvGRi ˆQGjUv ZLb gvgvi cv wUGc ˆ`q|

dvGgÆwmi ˆcQGb Ni SuvU ˆ`Iqv nGœQ, Zvi kõ cvwœQ| ˆh SuvU w`GœQ, ˆm ‰LGbv Avgvi ˆPvGLi AvovGj| ‘ˆPvGLi Avovj' K^vUv wVK

nGjv bv| ˆPvL ˆbB, ZLb Avevi ˆPvGLi Avovj Kx?

cyGivGbv ÕÃ†wZ KxfvGe KxfvGe ˆhb ˆ^GK hvq| Avgiv ‰LGbv ewj, evÍ¼Uv `c KGi wdDR nGq ˆMj| AwZ cÉvPxbKvGj cÉ`xc R¾jZ|

cÉ`xc ˆbfvi mgq `c KGi kõ nGZv| ˆmB ‘`c’ kõ ‰LGbv AvgvG`i ÕÃ†wZGZ AvGQ| Avgiv ejwQ, evÍ¼Uv `c KGi wbGf ˆMGQ|

RxweZ gvbyGli ÕÃ†wZ msiwÞZ ^vGK gwÕ¦GÓ•| ‰KRb g†GZi ÕÃ†wZ KxfvGe msiwÞZ nq? Avgvi ÕÃ†wZ ‰Lb ˆKv^vq Rgv?

KvGRi ˆQGjUv Ni SuvU w`Gq wdGi ‰GmGQ| ˆm AveviI ejj, gvbylUv ˆMj KB? Pv Vv´£v nBGZGQ|

dvGgÆwmi cwòKv wbGq ˆjvK ‰GmGQ| ˆm evBGi ˆ^GK cwòKv QyGo ˆdjGZB KvGRi ˆQGjwU ejj, ‰Z ˆejv KBiv KvMR w`Gj Avgivi

cyGl bv| mÅvGii mØvjGejv KvMR jvGM| AvBR ^vBKv KvMR eb| bM` cqmvq KvMR Lwi` Kie|

// Original page 10
[[page-10]]

gvgvi KvGRi ˆQGjUv KvMR fuvR KGi KvD´ŸvGi ivLGZ ˆMGQ, ‰KUz DuwK w`GjB ˆm Zvi mÅviGK ˆ`LGZ cvGe| gGb nGœQ, ˆm DuwK

ˆ`Ge| gvgv wK gviv ˆMGQb? ˆKvqv´Ÿvg mƒGò gvgv ‰Lb kÉqwWsMvGii weovj| ‰KB mGã RxweZ ‰es g†Z| KvGRi ˆQGj DuwK ˆ`Iqvgvò

welqwUi gxgvsmv nGe| gvgv ˆKvGbv ‰KwU wiGqwjwU MÉnY KiGeb| nq g†Z wiGqwjwU A^ev RxweZ wiGqwjwU|

KvGRi ˆQGjUv cwòKv fuvR KGi ˆiGL PvGqi Kvc wbGq PGj ˆMj| gGb nq, PvGqi ˆ`vKvGb Kvc ˆdiZ w`GZ ˆMGQ|

AvœQv, Avwg wK Avcbv-Avcwb gvgvi ˆkdv dvGgÆwmGZ PGj ‰GmwQ, bvwK ˆKD AvgvGK ‰LvGb wbGq ‰GmGQ? AvgvGK wKQy ˆevSvGbvi

ˆPÓ¡v KiGQ| ˆmB ‘ˆKD’Uv ˆK? Av wWfvBb AeRvfvÆi@cweò `kÆK; whwb mewKQyB ˆ`GLb| gGMÆi Rvbvjvq eGm ^vKv gvwQ ˆ`GLb,

keG`Gni bvwofzuwo KvUv ˆ`GLb, Avevi ˆkdv dvGgÆwmi gvwjGKi KzuKwo-gyKwo nGq cGo ^vKv ˆ`GLb| ÷ay ˆh ˆ`GLb Zv bv, AbÅGKI

ˆ`Lvb| Avwg ‰B `†kÅwU ˆ`LGZ PvBwQ bv, wK¯§ AvgvGK ˆ`LGZ nGœQ|

KÑvGmi ‰K eî×‡Zvq eGjwQjvg, ‘‰KRb gvbyGli cGÞ ‰KB mGã `yB RvqMvq ^vKv mÁ¿e bq, wK¯§ BGjKUÇb ˆh ^vKGZ cvGi Zv AGâi

gvaÅGg ˆZvgvG`i ˆevSvGbv nGqGQ| ˆZvgvi kixGii ‰KwU BGjKUÇb Puv` ev gãj MÉGn cvIqvi mÁ¿vebv wK¯§ AvGQ|’ QvòG`i ‰KRb kõ

KGi ˆnGmB wbGRGK mvgGj wbGq wmwiqvm nGq ˆMj| Avwg Zvi w`GK ZvwKGq ejjvg, ‘AvaywbK c`v^Æwe`Åv `Ë‚Z eÐÅvK gÅvwRGKi w`GK

hvGœQ| ‰Lb cÅvivjvj IqvGÎ£Æi K^v ejv nGœQ, gvwÎŸfvGmÆi K^v ejv nGœQ| ˆZvgvi bvg Kx?’

ˆm fxZ Mjvq ejj, mygb|

Avwg ejjvg, mygb! wVK ˆZvgvi gGZv ‰KRb, Zvi bvgI mygb, ˆm ‰B gynƒGZÆ AbÅ ‰KwU RMGZ Avgvi gGZv ˆ`LGZ ‰KRGbi w`GK

ZvwKGq AvGQ| ‰KUvB ÷ay cÉGf`@Zzwg ‰LvGb Pkgv cGiQ, ˆmLvGb nqGZv ˆZvgvi ˆPvGL Pkgv ˆbB| `yBUv wiGqwjwU@‰KUvq ˆZvgvi

ˆPvL fvGjv, AbÅUvq ˆPvL Lvivc| ˆZvgvi Amxg msLÅvi wiGqwjwU wbGq AmxgmsLÅK RMr engvb| wek¼vm nGœQ?

eySGZ cviwQ bv, mÅvi| gv^v NyivGœQ|

Avwg KZÞY ÕÃ†wZi ˆfZi XzGK wQjvg Rvwb bv| nVvr ÕÃ†wZ ˆ^GK ˆei njvg, ‰Lb Avi Avwg eo gvgvi ˆkdv dvGgÆwmGZ ˆbB|

AvgvG`i MÉvGgi evwo KjgvKv±`vq| `ƒGi ˆKv^vI gvBwKs nGœQ| AÕ·Ó¡fvGe gvBwKsGqi kõ ÷bGZ cvwœQ:

‰KwU weGkl ˆNvlYv@KjgvKv±`vi K‡Zx m¯¦vb, wek¼we`ÅvjGqi ‘cÉGePi’ BdGZLvi Bmjvg mvGne BG¯¦Kvj digvGqGPb| B®²v wjÍÏvGn

Iqv B®²v BjvBGn ivwRDb| A`Å ev` ˆRvni Zuvi bvgvGR RvbvRv C`Muv gvGV AbywÓ¤Z nBGe| Avcbviv `Gj `Gj ˆhvM`vb Ki‚b|

‰KwU weGkl ˆNvlYv@KjgvKv±`vi K‡Zx m¯¦vb...


gvGqi KeGii cvGk Avgvi RbÅ Kei ˆLuvov nGœQ| RyÁÃvNGii gyqvwäb Kei ˆLuvov Z`viK KiGQb| Bbvi Mjvi Õ¼i wgwÓ¡| wZwb nvZ ˆbGo

ˆbGo Kei ˆLuvov welGq K^v ejGQb| ˆMviGLv`K AevK nGq Zuvi K^v ÷bGQ| gyqvwäb ejGQb, Kei `yB cÉKvGii nq| wm±`yK Kei Avi

ˆevM`vw` Kei| ˆZvgiv ÷ay cvGiv wm±`yK Kei| AvdGmvm! ˆkvGbv, KeGii MfxiZv ‰gb nGe, ˆhb gy`ÆvGK hLb wR±`v Kiv nGe, ˆm ˆhb

emGZ cvGi| gvbGKi ˆbGKGii cÉGk²i Reve ZvGK eGm w`GZ nGe, ‰UvB weavb| gvbGKi ˆbGKGii cÉ^g cÉk² wK Zzwg RvGbv?

ˆR bv, üRyi|

cÉ^g cÉk² eoB A«¿zZ| cÉ^g cÉk², ‘Zzwg cyi‚l, bv bvix?’

eGjb Kx! Avwg ÷bwQ, ‘ˆZvgvi agÆ Kx?’ ‘ˆZvgvi bex ˆK?’

‰B me cÉk²I Kiv nGe| ZGe cÉ^g cÉk² ‘Zzwg cyi‚l, bv bvix’| ‰B cÉk² Kivi A^Æ Kx RvGbv|

ˆR, bv|

‰B cÉk² ˆ^GK ˆevSv hvq, gvbGKi ˆbGKi g†Z eÅwî×i welGq wKQyB RvGb bv|

AvPvbK nBjvg|

AvPvbK nIqvi wKQyB bvB| me mgq ˆLqvj ivLev, Zzwg cyi‚l| gvbGKi cÉk² Kij, Zzwg cyi‚l, bv bvix| gvbGKi ˆbGKGii

ˆPnvivmyiZ ˆ`GL ˆZvgvi KBjRv ˆMj ÷KvGq| Zzwg fzjekZ ejjv, Avwg bvix| ZvnGjB aiv LvBQ| ÷i‚ nBe ^vbvi gvBi|

^vbvi gvBi Kx?

Avmvwg aBiv wbqv cywjk ^vbvZ ˆh gvBi ˆ`q, Zvi bvg ^vbvi gvBi|

‰B gyqvwäb mvGne eo gvgvi NwbÓ¤ e®¬z| eo gvgv AvgvG`i evwoGZ ^vKGZb| evev ZvGK gv`Ëvmvq fwZÆ KwiGq ˆ`b| gyqvwäGbi mGã

eo gvgvi gv`Ëvmvq cwiPq| K^vq K^vq eo gvgv ZvGK eGjb eyievK| gyqvwäb (Zvi bvg gybwm iBm) mGã mGã ejGjb, ZzwgI eyievK|

eyyevK, eyyevK, eyyevK|

eo gvgvi LeiUv Avwg Zvi e®¬zGK ejGZ cviwQ bv| RxweZ gvbyGli ‰B ÞgZv AvGQ| g†GZi ˆbB|

‰KmGã AGbKàGjv cvwL WvKGQ| eo gvgv wK gviv ˆMGQb? eo gvgvi g†ZzÅGZ cÉPzi cvwL WvKvi K^v| gvgv nGjb cÞxe®¬z| Zvi

‰KUvB ˆbkv, eGb-RãGj dGji MvQ jvMvGbv| cvwLG`i LvIqvi RbÅ dj| cÉwZeQi ŠekvL gvGm wgwb UÇvKfwZÆ djMvGQi Pviv wbGq wZwb

eGb ˆXvGKb|

MvRxcyGii kvj eGb Zvi jvMvGbv wjPzMvGQi cvKv wjPz ˆ`LGZ ‰Kevi Avwg Zvi mGã eGb XzGKwQjvg| AGbK ˆLuvRvLyuwR KGiI gvgv

wjPzMvQ ˆei KiGZ cvGibwb|

eGb-RãGj dGji MvQ jvMvGbv wbGqI gybwm iBGmi mGã gvgvi SMov| gybwm iBm ejGZb, dGji MvQ Zzwg jvMvI gvbyGli RbÅ

jvMve| c÷cvwLi LvG`Åi eÅeÕ©v AvÍÏvncvK KGib| wcucovi ˆKvGbv LvG`Åi Afve nq bv| gvbyGli nq| gvbylGK wZwb ævb-eyw«¬ w`GqGQb

eGj gvbylGK wbGRi Lv`Å msMÉn KiGZ nq|

gvgv weiî× nGq ejGZb, me dj gvbyl ˆLGq ˆdjGj cvwLiv Kx LvGe? eyyevK|

ZzwgI eyievK| c÷e®¬z mvRGQ|

Pzc

Zzwg Pzc |


== Chapter 2

// Original page 11
[[page-11]]

gvBGKi ˆNvlYv ÷Gb ^vjv nvGZ dwKi-wgmwKb AvmGZ ÷i‚ KGiGQ| ZvG`i ˆPvGLgyGL Avb±`| `yUv Mi‚ RGen& Kiv nGe| jvk `vdGbi

ci dwKi-wgmwKb LvIqvGbv nGe|

dwKi-wgmwKbG`i RbÅ ‰KUv Mi‚, f`ËG`i RbÅ AvGiKUv Mi‚| hviv Mi‚ Lvb bv ZvG`i RbÅ Lvwmi gvsm|

Avgvi g†ZzÅi KviGY ˆh wZbwU AGeva cÉvYx gviv hvGœQ, ZvG`i ˆ`Ljvg| `yUv Mi‚B gnvbG±` Nvm ˆLGq hvGœQ| QvMjUv wKQy LvGœQ bv|

g†ZzÅi ci ‰B cÉvYxG`i wK Avjv`v ˆKvGbv RMr AvGQ? ZvG`i wK Avñv AvGQ?

Avgvi BGœQ KiGQ MÉvGgi evwoGZ ˆhGZ| AGbK w`b ‰B evwo ˆ`wL bv| evwoi ˆcQGbi meyR kÅvIjv XvKv cyKziUv A«¿zZ| ‰B cyKzGi

cÉKví `yUv MRvi gvQ AvGQ| gvGSgGaÅ MRvi gvQ aivi ˆPÓ¡v PvjvGbv nq| Klgbv aiv hvq bv| AGbGKi aviYv, ‰B `yUv gvQ bv, wRb|

gvGQi i…c aGi cyKzGi evm KGi|

‰B cyKzGii AviI inmÅ AvGQ| nVvr nVvr cyKzi fwZÆ nGq hvq c«ÂdzGj| ZLb eySGZ nGe, AvgvG`i evwoi KviI g†ZzÅ nGe| ˆQvU PvPv

hLb gviv ˆMGjb, ZLb c«ÂdzGj cyKzi fwZÆ nGq wMGqwQj| Avgvi eo fvB hLb RvgMvGQi WvGj `wo SzwjGq duvm wbGjb, ZLGbv cyKzi

fwZÆ wQj c«ÂdzGj| `v`vRvb ZLb ˆeuGP, wZwb üKzg w`Gjb, me c«Â wkKo wQuGo ZzGj Avb| ‰KUv c«ÂI ˆhb bv ^vGK| Avgvi g†ZzÅGZ wK

Avevi c«ÂdzGj cyKzi fwZÆ nGqGQ? ‰Kevi hw` ˆ`LGZ cviZvg! Lye ˆ`LGZ BGœQ KiGQ|

BGœQ KiGjI evwoGZ ˆhGZ cviwQ bv| g†GZi ˆKvGbv BœQv-AwbœQv ˆbB| AGbÅi BœQvB Zvi BœQv| ˆmB AbÅUv ˆK?


Avgvi ˆWWewW AvmGQ bv, ‰B Lei gGb nq ˆcuŒGQ ˆMGQ| ˆMviGLv`K ‰es gyqvGäb PGj ˆMGQb| AGbGKB PGj hvGœQ, ÷ay dwKi-

wgmwKbG`i `j hvGœQ bv| Zviv nZvk, Kx KiGe eySGZ cviGQ bv| ‰G`i wjWviGkÉYxi ‰KRb Þzº¬ Mjvq ejGQ, Lei w`qv AvBbÅv wK

dvBRjvwg?

wjWvGii K^vq mevBGK mvq w`GZ nq| evwK dwKi-wgmwKbiv Zv-B KiGQ| mvq w`GœQ| wjWvi ejj, AvBR Lvbv w`Ge bv gvbjvg,

KGe w`Ge ˆmUv ˆZv ejv jvMGe|

wjWvGii cvGki Rb ejj, AekÅB AekÅB| cÉGqvRGb evwo-Ni fvOPzi nGe| ‰gb e`G`vqv w`e àwÓ¡myóv gBiv mvd nGq hvGe|

gwnjv dwKi ejj, bÅvhÅ K^v eGjGQb| AwZ bÅvhÅ|

wjWvi ejj, bÅvhÅ wK eGjb? ‰B K^v bÅvGhÅi IcGi w`qv hvq| ˆKvGbv ˆLuvRLei bv w`qv AvGqvRb hviv KiGQ ZvivGi gvBi ˆ`Iqv

``iKvi|

mgGeZ AvIqvR, AekÅB| AekÅB|

AvGqvRK Kviv ˆevSv hvGœQ bv| ‰i gGaÅ ˆek wKQy Mvwo XvKv ˆ^GK PGj ‰GmGQ| ‰KUv gvBGò×vevm fwZÆ KGi Avgvi wek¼we`ÅvjGqi

wKQy KwjM PGj ‰GmGQ| `xNÆ c^ögGY Zviv KÑv¯¦| dwKi-wgmwKbG`i gGZvB ÞzavZÆ| ZvivI dzGWi Kx eÅeÕ©v wbGq wbGRG`i gGaÅ K^v

ejvewj KiGQ| ZvG`iGKI wKQyUv wÞµ¦ gGb nGœQ| Þzav me gvbylGK ‰K KvZvGi ˆdGj| g†ZzÅi cGii RMGZ Þzav ˆbB| ˆmLvGb ‰B

KviGYB nqGZv mevBGK ‰K KvZvGi ˆdjv hvGe bv|

e†wÓ¡ ÷i‚ nGqGQ| AvgvG`i AçGji weLÅvZ Szg e†wÓ¡| wKQyÞGYi gGaÅB ˆLuvov KeGi cvwb RGg ˆMj| ˆek wKQy eÅvO cvwbGZ SuvcvSuvwc

KGi Avb±` cÉKvk KiGQ| AcÉZÅvwkZfvGeB ZvG`i RbÅ cvwbi eÅeÕ©v nGqGQ, ZvG`i Avbw±`Z nIqviB K^v|

knGii Szg e†wÓ¡ Avi MÉvGgi Szg e†wÓ¡ Avjv`v| knGi Szg e†wÓ¡ gvGbB `yGfÆvM| ivÕ¦vq ‰KnuvUz cvwb| ZxeË hvbRU, `ƒwlZ welvî× cvwbGZ cv

WzweGq c^Pvixi evwo ˆdiv| MÉvGgi Szg e†wÓ¡ gvGb we÷«¬ Avb±`|

AGbK w`b AvGM evwoi cyKziNvGU eGm AvwQ, ÷i‚ nGjv Szg e†wÓ¡| `xwNi cvwbGZ e†wÓ¡ coGQ, ey`&ey` DVGQ@ˆ`GL gGb nGœQ cyKziUv

AvbG±` LjLj KGi nvmGQ| evZvGm MvGQi Wvjcvjv `yjGQ, gGb nGœQ e†wÓ¡i AvbG±` Zviv bvPGZ ÷i‚ KGiGQ|

e†wÓ¡ ÷i‚ nGqwQj weGKGj| Avwg wVK Kijvg, e†wÓ¡ bv ^vgv chÆ¯¦ NvGU eGm ^vKe| e†wÓ¡ ^vgj ‰kvi AvRvGbi ci| ZLb ‰K A«¿zZ

`†GkÅi mƒPbv nGjv@nvRvi nvRvi ˆRvbvK ˆcvKv ˆei nGq ‰j| Zviv mevB ‰Kò nGq ‰KUv eGji gGZv evbvGœQ, Avevi gynƒGZÆi gGaÅ ej

ˆfGO Pviw`GK QwoGq coGQ| Avevi ej ŠZwi KiGQ| ‰Kmgq Zviv Avgvi Pviw`GK NyiGZ jvMj, ˆmB NyivI wewPò| wKQyÞY KÑKIqvBR,

Avevi wKQyÞY AÅvw´Ÿ-KÑKIqvBR| Avgvi gGb nGjv, ‰B ˆRvbvwKiv AvgvGK wKQy ejvi ˆPÓ¡v KiGQ, ejGZ cviGQ bv| wbÁ²GkÉYxi

KxUcZGãi mGã AvgvG`i gvbwmK ˆhvMvGhvGMi ˆKvGbv eÅeÕ©v cÉK‡wZ ivGLwb|

wLËÓ¡vb agÆhvRK ˆjGgwUÇ ‰Kevi cÉv^Æbv ˆkl KGi Zuvi ˆjLvi ˆUweGj eGm wQGjb| ˆePviv gvbwmKfvGe wechÆÕ¦| KviY, ˆmw`b m®¬Åvq

wZwb gnvb c`v^Æwe` AvBbÕ¡vBGbi agK ˆLGqGQb| 1927 mvGji K^v| eËvGmjGmi mjGf KbdvGiG´Ö ‰B agÆhvRK AvBbÕ¡vBGbi w^Iwi

Ae wiGjwUwfwUi Ici ‰KwU iPbv cvV KGib| ˆhGnZz AvBbÕ¡vBb Õ¼qs ˆmB mfvq DcwÕ©Z, ˆjGgwUÇi AvMÉGni mxgv wQj bv|

ˆjGgwUÇ Zuvi iPbvq ˆ`Lvb ˆh AvBbÕ¡vBGbi w^Iwi Ae wiGjwUwfwUi mgvavb `vwe KGi gnvwek¼ cÉmiYkxj| meÆw`GK Zv QwoGq coGe|

AvBbÕ¡vBb agK w`Gq eGjb, Aâ w`Gq mewKQy wePvi KiGe bv| AG®¬i gGZv Aâ AbymiY KiGj ˆh c`v^Æwe`Åv ˆZvgiv ˆei KiGe, Zv

nGjv ˆN®²vKi (AÅvGevwgGbe&j& wdwRÝ)|

ˆjGgwUÇ Zuvi WvGqwiGZ wjLGjb, Avwg gvbwmKfvGe cyGivcywi wechÆÕ¦ AeÕ©vq ˆjLvi ˆUweGj eGm wQjvg| ZLb ‰KUv gkv ‰Gm Avgvi

KvGbi KvGQ àbàb KiGZ jvMj| Zvi KvR AvgvGK weiî× Kiv, wK¯§ Avwg weiî× nwœQjvg bv| Avgvi gGb nwœQj, ˆm AvgvGK mv¯¦¾bvi K^v

ejGQ| Avwg K^vàGjv eySGZ cviwQ bv| ˆm ÷ay ˆh AvgvGK mv¯¦¾bv w`wœQj Zv bv, AvgvGK KvR PvwjGq ˆhGZI eGjwQj| Zvi `yeQi ciB AÅvGÕ¡ÈvGbvgvi nvej mvGne gvD´Ÿ DBjmb AeRviGfUwii c†w^exi meGPGq ÞgZvai `yiweb w`Gq cixÞv-wbixÞv KGi

ˆNvlYv KGib, me MÅvjvwÝi wgwÍ•IGq MÅvjvwÝ ˆ^GK `ƒGi mGi hvGœQ| gnvwek¼ mÁ·ÉmviYkxj|

AvBbÕ¡vBb jwäZ nGq ˆjGgwUÇGK wPwV wjGL RvbvGjb@ˆZvgvi w^Iwi weÕÃqKifvGeB my±`i| Avgvi Awfb±`b|

RxweZ gvbyGli RxeGbi ‰KwU Ask KvGU my±`Gii Abym®¬vGb| ˆKD ˆRvbvK ˆcvKvi SuvGKi ˆmŒ±`hÆ ˆLuvGR, Avevi ˆjGgwUÇi gGZv

gvbyGliv weM eÅvs w^Iwii ˆfZi my±`i ˆLuvGR|

ciKvGji gvbyGliv wbøqB ˆmŒ±`hÆ LyuRGe| Kx ˆmŒ±`hÆ LyuRGe?

// Original page 12
[[page-12]]

Avwg Avgvi keG`Gni RbÅ ˆLuvov Kei ˆ`LwQ, e†wÓ¡ ˆ`LwQ, `ƒGii gvBwKsGqi kõ ÷bwQ| ‰G`i gGb nq ˆKD Lei ˆ`qwb, ˆWWewW AvmGQ

bv

‰KwU weGkl ˆNvlYv@KjgvKv±`vi K‡Zx m¯¦vb, wek¼we`ÅvjGqi ‘cÉGePi’ BdGZLvi Bmjvg mvGnGei RvbvRv...

w`Gbi AvGjv `Ë‚Z wbGf hvGœQ| AvRI wK ivGZ e†wÓ¡ ^vgGe ‰es IB weGkl w`bUvi gGZv SuvGK SuvGK ˆRvbvwK ˆei nGe? gGb nGœQ Zv-B

nGe|


3.

Avwg ev Avgvi ˆPZbv ev AbÅ wKQy ‰Lb w`jy ˆivGWi evwoGZ, Avgvi wbGRi evwo| ‰LvGb KxfvGe DcwÕ©Z nGqwQ Zv Rvwb bv| Avgvi

AeÕ©v ˆmÉvGZ Mv fvwmGq ˆ`Iqvi gGZv| ˆmÉvZ ˆhw`GK wbGq hvGe AvgvGK ˆhGZ nGe| wbGRi Õ¼vaxb BœQvq wKQy Kivi ˆbB| gGb nGœQ Avgvi

wP¯¦v wbqw¯¨Z|

wbGRi evwoGZ ‰Gm Avwg AvbG±` Awff„Z nGqwQ| gGb nGœQ KZ `xNÆ w`em KZ `xNÆ iRbxB bv AvgvGK evBGi KvUvGZ nGqGQ| ‰Lb

wdGi ‰GmwQ| me AvGMi gGZvB AvGQ| cwjb Zvi NGi B´ŸviGbGU Kx ˆhb ˆ`LGQ| gGb nq ˆdmeyK AvcGWU KiGQ| i‚webv kvIqvi ˆQGo

ˆMvmj KiGQ| mKvj 10Uv evGR| ‰B mgq ˆm ‰Kevi kvIqvi ˆbq| kvIqvi wbGq mKvGji bvkZv KGi| AvGiKevi kvIqvi ˆbq ivGZ

NygyGZ hvIqvi AvGM AvGM|

iv®²vNGi bZzb ‰KUv KvGRi ˆgGqGK ˆ`LGZ cvwœQ| ˆm i‚webvi ˆeËKdvÕ¡ ˆiwW KiGQ| ‰K ÕÏvBm i‚wU, ‰K ™Ïvm gvjUvi im, ‰K Kvc

`ya, ‰KUv ˆm«¬ wWg| wU-cU fwZÆ nvjKv wjKvGii Pv ˆ`Iqv nGe| i‚webv bvkZv Kivi duvGK duvGK Pv LvGe| w`Gbi cÉ^g wmMvGiUUv AekÅ

÷i‚GZB LvGe| gvjUvi iGmi ™ÏvGm PzgyK w`Gq|

KvG`i iv®²vNGi XzGKGQ| ˆm Mjv wbPz KGi ejj, WÈwqsi‚Gg ˆMÕ¡ AvGQ, ‰K Kvc Kwd ˆ`b| wPwb-`ya Ad, eÐÅvK Kwd| wPwb-`ya Qvov

‰B wRwbm gvbyGl KÅvgGb Lvq ˆK RvGb!

mvjgv ejj, Kwd Avcwb wbGR evbvqv wbqv hvb| Avgvi nvZ e®¬|

KvG`i ejj, ˆMÕ¡ ˆK AvmGQ ÷bGj nvGZi KvR e®¬ nGq hvGe| wWwei B´ÖGcÙi| gÅvWvgGK AÅvGiÕ¡ KiGZ AvmGQ|

Kb Kx?

gvWÆvi PvRÆ| gÅvWvg AvgvG`i mÅviGi wel LvIqvGq ˆgGiGQ| cwòKvq Lei PGj ‰GmGQ|

I AvÍÏvn|

AvcGbi ˆZv ‘I AvÍÏv’ ejvi `iKvi bvB| gÅvWvg ejGe 'I AvÍÏv'| hð KGi Kwd evbvqv ˆ`b, wbqv hvB|

Kwdi mGã Avi wKQy w`e? ˆKK w`e?

÷ay Kwd ˆPGqGQ, ÷ay Kwd wbqv hve| evowZ hð KiGj mG±`n KiGe| cywjGki ˆjvK| Avwg wbGRI wecG`i gGaÅ AvwQ| `ywbqvi cÉk²

KiGZGQ | Avcwb ˆeuGP ˆMGQb| Avcwb RGqb KGiGQb mÅvGii g†ZzÅi ci| Zvi cGiI UzKUvK cÉk² AvcbvGiI KiGe| wWwe cywjk wbGRi

evcGiI QvGo bv| ‰gb LZibvK wRwbm|

KvG`i Kwd wbGq AwZ webxZ fwãGZ wWwe B´ÖGcÙi LwjGji mvgGb ivLj| Lwjj ejj, ^ÅvsK qyÅ|

KvG`i webGq ˆfGO cGo ejj, mÅvi, ˆbv ˆgbkb|

Lwjj ejj, emvi NGi ˆek KGqKUv AÅvmGUÇ ˆ`LwQ| ‰LvGb wK wmMvGiU LvIqv hvq?

wR, LvIqv hvq| wmMvGiU wK Avcbvi mGã AvGQ bv ‰Gb w`e?

wmMvGiU mGã AvGQ|

mÅvi, jvBUvi wK AvGQ?

AvGQ, ^ÅvsK qyÅ|

ˆbv ˆgbkb, mÅvi| gÅvWvg ‰Lb kvIqvi wbGZGQb| kvIqvi wbGq ˆeËKdvÕ¡ KiGeb, Zvici Avcbvi KvGQ AvmGeb|

ˆKvGbv Amyweav ˆbB, Avwg AGcÞv Kie| gÅvWvGgi ˆgGqwU wK evmvq AvGQ?

wR AvGQ| Kx KiGZGQ Rvwb bv, ˆ`GL Avme?

ˆ`GL AvmGZ nGe bv| Avcwb Avgvi mvgGb emyb| Avcbvi mÅviGK ˆh ivGZ nvmcvZvGj wbGq hvb, ˆm ivGZi NUbvUv Avcbvi gyL

ˆ^GK ÷wb| NUbv hv NGUGQ Zv-B ejGeb| bZzb wKQy hyî× KiGeb bv, Avevi wKQy ev`I ˆ`Geb bv| ejyb Kx NGUwQj|

KvG`i Kx NGUwQj ˆek àwQGq ejGQ| Avwg KvG`Gii K^v ÷bwQ| ˆm wK fveGQ ZvI eySGZ cviwQ| cywjk B´ÖGcÙi Lwjj Kx fveGQb

Zv eySGZ cviwQ bv| gGb nq, wZwb wKQy fveGQb bv| wKsev hv AvgvGK wbq¯¨Y KiGQ ˆm LwjGji fvebv AvgvGK RvbvGZ PvGœQ bv|

KvG`i ejGQ, mÅvi, Avwg ^vwK ‰KZjvq| ivZ AvbygvwbK ˆ`o NwUKvq gÅvWvg Avgvi NGi avØv w`Gjb| Avwg `iRv LyjGZB gÅvWvg

ejGjb, ˆgBb ˆivGW wMGq `uvovI| ˆZvgvi mÅvGii kixi Lvivc| AÅvÁ¼yGj´Ö AvmGZ eGjwQ| ‰i gGaÅ PGj Avmvi K^v| Zzwg AÅvÁ¼yGj´ÖGK

evmv wPwbGq wbGq AvmGe| gÅvWvGgi K^v ÷Gb Avwg ˆ`ŒGo ivÕ¦vq PGj ˆMjvg|

Lwjj ejj, mÅvGii Kx nGqGQ RvbGZ PvBGjb bv?

ZLb RvbGZ PvB bvB|

AÅvÁ¼yGj´Ö Avmvi ci RvbGZ ˆPGqGQb?

wR bv| ZLb i‚wM wbGq ˆ`ŒovG`Œwo|

AÅvÁ¼yGjG´Öi mGã nvmcvZvGj wMGqwQGjb?

wR| AekÅB|

// Original page 13
[[page-13]]

Lwjj wmMvGiU aivGZ aivGZ ejj, IB ivGZ Avcbvi gÅvWvg Avcbvi NGi hvb bvB| wZwb AvcbvGK ˆgvevBj ˆUwjGdvGb wmMvGiU

wKsev MuvRvi cywiqv AvbGZ eGjGQb| Avcwb IB wRwbm wbGq wdGi ‰Gm ˆkvGbb AÅvÁ¼yGj´Ö ‰Gm Avcbvi mÅviGK wbGq ˆMGQ| Avcwb

nvmcvZvGjI hvb bvB|

Avwg eySGZ cviwQ KvG`i fGq-AvZGâ AwÕ©i nGq cGoGQ| cywjk B´ÖGcÙGii cÉwZwU K^vB mZÅ| KvG`i ˆfGe cvGœQ bv, ‰B ˆjvK ‰Z

wKQy Rvbj KxfvGe|

Lwjj nvB ZzjGZ ZzjGZ ejj, mgvGb wg^Åv K^v eGj hvGœQb| kixi ˆ^GK Pvgov LyGj ˆdje| KvGb aGi `kevi DVem Ki‚b|

LwjGji K^v ÷Gb Avwg AevK| wgwÓ¡ Mjvq Avcwb Avcwb KGi KvGb aGi DVem KiGZ ejGQ|

KvG`i mGã mGã AvG`k cvjb Kij| Lwjj ejj, Avwg hZÞY ‰B evwoGZ ^vKe Avcwb ZZÞY KvGb aGi ^vKGeb| Avcbvi gÅvWvg

hw` Kvb ˆ^GK nvZ bvgvGZ eGj Zvi cGiI bvgvGeb bv|

AekÅB| mÅvi, ev^i‚Gg wK hvIqv hvGe?

hvIqv hvGe bv ˆKb! KvGb aGi hvGeb|

Lwjj AvGiKUv wmMvGiU aivj| ˆm Avbw±`Z ‰es DrdzÍÏ| Lwjj PgrKvi cuÅvP ˆLjvGœQ| Avwg cÉvq wbwøZ ˆm i‚webvGK cuÅvGP

ˆdjGe| ˆm cÉÕ§wZ wbGqB ‰GmGQ|

Avcbvi bvg ˆhb Kx?

KvG`i|

‰Z jÁ¼v bvGg ˆZv WvKGZ cvie bv| ‰Lb ˆ^GK Avcbvi bvg Kv`y|

Amyweav bvB mÅvi|

‰Lb hvb, Avcbvi gÅvWvGgi ˆeËKdvÕ¡ ˆUweGji cvGk `uvwoGq ^vKzb| gÅvWvg hLb wRGæm KiGe KvGb aiv ˆKb, ZLb Avgvi K^v

ejGeb| Lei`vi Kvb ˆ^GK nvZ bvgvGeb bv| Kvb ˆ^GK nvZ bvgvGj AvcbvGK UÅveGjGUi gGZv wMGj ˆdje|

Kvb ˆ^GK nvZ bvgve bv mÅvi| Avcwb hLb ejGeb ZLb bvgve, Zvi AvGM bv|

Lwjj fzj KGiGQ| i‚webv mnR wPR bv| KvG`iGK KvGb awiGq ˆm i‚webvGK fq cvIqvGbvi ˆPÓ¡v KiGQ| i‚webv fq cvIqv UvBc ˆgGq

bv LwjGji mGã i‚webvi KG^vcK^Gbi RbÅ Avwg AGcÞv KiwQ| Avb±`gq AGcÞv ejv ˆhGZ cvGi| ˆKvGbv ‰KUv fvGjv wmGbgv ˆ`Lvi

AvGMi gynƒGZÆi AvbG±`i gGZv Avb±`|

g†ZG`iI ZvnGj Avb±`-ˆe`bvi eÅvcvi AvGQ| ZGe Avb±`-ˆe`bvi ZxeËZv Kg| KvG`i KvGb aGi NyiGQ@`†kÅwU gRvi jvMGQ| RxweZ

gvbyl AGbÅi weeËZ AeÕ©vq Avb±` cvq| ‰ RMGZI ZvB|

i‚webv wmMvGiU nvGZ WÈwqsi‚Gg emGZ emGZ ejj, mwi, ˆ`wi Kijvg| Lwjj DGV `uvovj, webxZ Mjvq ejj, gÅvWvg, ˆKvGbv mgmÅv

ˆbB| KvG`i eGj ‰KRb AvgvGK Kwd w`GqGQ, Kwd LvwœQjvg|

Lwjj PvwœQj, KvG`Gii cÉmã IVvq i‚webv Zvi KvGb aGi `uvwoGq ^vKv welGq wKQy ejGe| i‚webv wKQyB ejj bv|

Lwjj ejj, Avgvi kÉG«¬q wkÞK W. BdGZLvi‚j Bmjvg mÅvGii wfGmiv wiGcvUÆ nvGZ ‰GmGQ| cvKÕ©jxGZ UwÝK eÕ§ cvIqv ˆMGQ|

DœPgvòvq AiMÅvGbv dmdivm|

i‚webv wmMvGiGU Uvb w`Gq ejj, I AvœQv|

Lwjj ˆPvL mi‚ KGi ejj, welUv ˆKD ZvGK LvBGqGQ|

i‚webv ejj, wKsev wbGRB ˆLGqGQ|

Lwjj ejj, ‰B Avkâv AekÅB AvGQ| ˆm ˆÞGò wfKwUg ˆW^GbvU ˆiGL hvGe| wKsev g†ZzÅi AvGM KvDGK eGj hvGe| AvcbvGK wK

wKQy eGj ˆMGQb?

bv ZvGK Aævb AeÕ©vq nvmcvZvGj wbGq wMGqwQ| wZb w`b wZb ivZ nvmcvZvGj wQj| gvGS gGaÅ ævb wdGiGQ| K^vevZÆv eGjGQ,

wK¯§ wel LvIqv wbGq wKQy eGjwb|

Lwjj ejj, Avgvi kÉG«¬q wkÞGKi LvZvcò, WvGqwi ‰me cixÞv KGi ˆ`LGZ PvB|

i‚webv kî× Mjvq ejj, K^vq K^vq ‘Avgvi kÉG«¬q wkÞK’ ‰B eyjwkU KcPvGeb bv| Avcwb Klgbv Zvi Qvò wQGjb bv| Avcwb ˆhgb

Avgvi welGq ˆLuvR wbGœQb, AvwgI Avcbvi welGq ˆLuvR wbGqwQ| AÅvµÏvGqW wdwRGÝ Avcwb Klgbv cGobwb| Avcwb BsGiwR fvlv I

mvwnGZÅi Qvò| AbvmÆ chÆ¯¦ cGoGQb| AbvGmÆ ^vWÆKÑvm cvIqvq Avcbvi ‰g‰ cov nqwb| Avcwb KweZv ˆjLvi ˆPÓ¡v KGib| Ai‚wYgv ˆmb

Q«ÂbvGg wKQy AwZ ALv`Å KweZv còcwòKvq cÉKvwkZ nGqGQ| hv KiGeb wbGRi Ici wek¼vm ˆiGL KiGeb| ˆKvGbv ˆgGqi bvGgi AvovGj

KiGeb bv

Lwjj ^ZgZ fve KvUvGZ KvUvGZ ejj, Avwg wK ‰KUv wmMvGiU aivGZ cvwi?

i‚webv ejj, AekÅB cvGib| Avwg hw` wmMvGiU ˆLGZ cvwi AvcwbI cvGib| fvGjv K^v, KvG`i KvGb aGi NyiGQ ˆKb?

gÅvWvg, I AvgvGK wKQy wg^Åv BbdiGgkb w`GqGQ|

wg^Åv BbdiGgkGbi kvwÕ¦ hw` KvGb aiv nq, ZvnGj wmMvGiU ˆdGj AvcbviI ˆZv KvGb aGi `uvwoGq ^vKv DwPZ| AvcwbI AvgvGK

wg^Åv BbdiGgkb w`GqGQb| eGjGQb, Avcwb Avgvi Õ¼vgxi wWGiÙ Õ¡zGW´Ÿ| hv Avcwb bv|

Lwjj ejj, gÅvWvg, KvG`i ‰KwU nZÅvKvGíi mvmGcÙ| AvcwbI mvmGcÙ| Avwg Z`¯¦Kvix Awdmvi| gvgjvi Z`G¯¦i mvnvGhÅi RbÅ

Avgiv mvmGcÙG`i mGã wKQy ˆg´Ÿvj ˆMg ˆLwj| Zvi mGã Avwg ‰K aiGbi ˆg´Ÿvj ˆMg ˆLjwQ| KvG`Gii ˆgvivwjwU ˆfGO ˆ`Iqv nGqGQ|

‰Lb PU KGi wg^Åv ejGe bv|

Avwg ‰KRb mvmGcÙ?

wR gÅvWvg| ‰ evwoGZ hviv AvGQ mevB mvmGcÙ| Avcbvi ˆgGq cwjb, hvi eqm ˆZi eQi, ˆmI mvmGcÙ| Pvjywb w`Gq ˆPGj gƒj

Avmvwg ˆei Kiv nGe| ‰B KvRwU Avwg fvGjv cvwi| Kwe wnGmGe Avwg eÅ^Æ nGZ cvwi, Z`¯¦ KgÆKZÆv wnGmGe Avgvi mybvg AvGQ|

i‚webv ejj, Avwg ˆhGnZz mvmGcÙ, Avcwb wbøqB Avgvi mGã ˆg´Ÿvj ˆMg ˆLjGeb ev ˆLjv ÷i‚ KGiGQb|

// Original page 14
[[page-14]]

gÅvWvg, Avcbvi mGã Avwg ˆg´Ÿvj ˆMg ‰LGbv ÷i‚ Kwiwb| ZGe AekÅB ÷i‚ Kie|

KLb ÷i‚ KiGeb?

Avcwb AbygwZ w`Gj ‰LbB ÷i‚ KiGZ cvwi| gÅvWvg, Avwg Avcbvi Õ¼vgxi ˆWWewW wbGq ‰GmwQ| eviv±`vq `uvovGjB ˆ`LGZ cvGeb

cywjGki Mvwoi ˆcQGb ‰KUv AÅvÁ¼yGj´Ö AvGQ| AÅvÁ¼yGjG´Öi ˆfZi KwdGb ˆWWewW AvGQ| myiZnvj ˆhGnZz ˆkl nGqGQ, ˆWWewWi KvR

ˆkl|

Lwjj cGKU ˆ^GK njy` Lvg ˆei Kij| njy` LvGgi ˆfZi miKvwi wmGji KvMR| Lwjj mvGne KvMR ‰wMGq w`Gq ejj, gÅvWvg,

‰LvGbB mB KGi ˆWWewW wiwmf Ki‚b|

i‚webv mB Kij| Lwjj ejj, myiZnvGji ˆWWewW ‰fvGe nÅv´£Ifvi Kiv nq bv| bvbv SvGgjvi ˆfZi w`Gq ˆhGZ nq| Avwg

ˆ`ŒoSuvc KGi weGkl eÅeÕ©vq wbGq ‰GmwQ| ‰UvB Avgvi ˆg´Ÿvj ˆMg| KvG`iGK Avwg AÅvGiÕ¡ KGi wbGq hve ˆfGewQjvg| IGK AvcvZZ

ˆiGL hvwœQ| evmvq ˆWWewW, AvcbvGK AGbK KvRKgÆ KiGZ nGe| ‰KRb cyi‚Gli mvnvhÅ `iKvi|

i‚webvi ˆVuvGUi ˆKvbvq ÞxY nvwmi ˆiLv ˆ`Lv w`GqB wgwjGq ˆMj| ˆm ˆg´Ÿvj ˆMgUv cQ±` KGiGQ|

gÅvWvg, AbygwZ w`Gj Avwg DwV| Avcbvi ‰Lb AGbK SvGgjv| ˆWWewW `Ë‚Z Kei ˆ`Iqvi eÅeÕ©v Ki‚b| AwZwiwî× Mig@ˆWWewW

wWKGÁ·vR Kiv ÷i‚ nGqGQ|

i‚webv wmMvGiU aivj| ˆm eo iKGgi avØv ˆLGqGQ@‰ iKg gGb nGœQ bv| Lwjj WvKj, Kv`y ˆKv^vq? Kv`y |

i‚webv ejj, Kv`yUv ˆK?

KvG`i AGbK jÁ¼v bvg ˆZv, ‰RbÅ kUÆ KGi Kv`y WvKwQ| Avcwb ˆhgb Avcbvi Õ¼vgxi e®¬z iweDjGK iwe WvGKb AGbKUv ˆm iKg|

Kv`y mvgGb ‰Gm `uvwoGqGQ| ˆm ‰LGbv KvGb nvZ w`Gq AvGQ| ˆPvL jvj| KcvGj we±`y we±`y Nvg|

Lwjj ejj, AGbKÞY ˆZvgvi mGã Avcwb Avcwb KGi K^v ejv nGqGQ| ‰Lb ˆ^GK Zzwg, Zvici ZzB| wVK AvGQ|

KvG`i ejj, wR mÅvi, wVK AvGQ|

Kv`y, Kvb ˆ^GK nvZ bvgvI| ˆZvgvi ‰Lb cÉPzi KvR| ˆZvgvi mÅvGii ˆWWewW wbGq ‰GmwQ| ˆKv^vq ivLGe wVK KGiv| cÉPzi eid

jvMGe| eiGdi eÅeÕ©v KGiv| MÉvGgi evwoGZ ˆWWewW wbGZ PvBGj gvBGò×vevGmi eÅeÕ©v KGiv| Pv-cvZv-dvZv Kx Kx ˆhb jvGM| ˆKvGbv

‰KUv ˆkl we`vq ˆÕ¡vGi PGj ˆMGj mewKQy cvGe|

i‚webv ejj, DBj BD wµÏR wjf Avm bvI!

Lwjj `uvovGZ `uvovGZ ejj, AekÅB gÅvWvg| ‰Þzwb PGj hvwœQ| Avgvi aviYv, ˆKD ˆUwjGdvb KiGj Avcwb ‰Lb aiGeb bv| ``qv

KGi AvgviUv aiGeb| Avcbvi wbGRGK wKÑqvi Kivi ‰KUv c^ AvGQ| hw` Avcbvi Õ¼vgxi ˆjLv ˆKvGbv KvMR cvb| hw` ˆjLv ^vGK ‘Avwg

ˆÕ¼œQvq welcvb KGiwQ| Avgvi g†ZzÅi RbÅ ˆKD `vqx bq|’ ‰ iKg wKQy hw` bv cvb Avcwb D«¬vi ˆcGZ cvGib| ‰Lb ‰KUv mr civgkÆ

ˆ`e|

i‚webv ejj, Kx iKg?

‰bvGqZ bvGg ‰KRb ˆjvK AvGQ, KviIqvb evRvGi ^vGK| gvbyGli mB Rvj Kivi eÅvcvGi Zvi `ÞZv AmvaviY| Rvj cvmGcvUÆ, Rvj

`wjGj Zvi Ici ˆKD ˆbB| Zvi ˆUwjGdvb bvÁ¼vi wK ˆ`e?

i‚webv Reve w`j bv| KwVb ˆPvGL ZvwKGq iBj| ‰B cÉ^g Avwg Lwjj Kx wP¯¦v KiGQ Zv aiGZ cvijvg| ‰bvGqZ bvGgi ˆjvKwUI

Zvi duvG`i Ask| ‰bvGqZ wWwe cywjGki ˆjvK| i‚webv Zvi KvGQ Rvj KvMR ŠZwi KiGZ hvGe ‰UvB duv`|

Kwdb ivLv nGqGQ ˆkvevi NGii DîGii eviv±`vq| evwoGZ ^g^Gg AvZâ| KvG`i gv^vq Uzwc cGi ˆdGjGQ| Uzwc gv^vq KvG`iGK Klgbv

ˆ`wLwb| ZvGK A«¿zZ ˆ`LvGœQ| Uzwci KviGYB nqGZv gyL jÁ¼vGU nGqGQ| KvG`i KvcfwZÆ PvGj AvMievwZ R¾vwjGq w`GqGQ| AvMievwZàGjv

nq ˆfRv wKsev ˆKvGbv ˆfRvj AvGQ| ‰KUz R¾GjB wbGf hvGœQ| KvG`i eÅÕ¦ AvMievwZi Z`viwKGZ|

mvjgv gv^vq ˆNvgUv w`Gq iv®²vNGi mgq KvUvGœQ| ˆavqv evmb AvGiKevi ayGq ˆdjGQ| gyGL weoweo KiGQ, ‘AvÍÏvn ing KGiv|’

`ycyGi ‰B evwoGZ iv®²v nGe wK bv Zv eySGZ cviGQ bv| giv-evwoGZ Pzjv R¾vjvGbvi wbqg ˆbB, ZGe eoGjvGKi evwoi wbqgKvbyb ^vGK

Avjv`v| `ycyGi gÅvWvg hw` eGjb, ‘Lvbv jvMvI’, ZLb ˆm Kx KiGe? KvG`Gii KvGQ ˆm civgkÆ ˆPGqwQj| KvG`i gyL SvgUv w`Gq eGjGQ,

AvgvGi w`K KiGeb bv| Avgvi me eyw«¬ ˆkl| hv Kivi wbGRi eyw«¬gGZv KGib|

mvjgv ejj, ivBm KzKvGi Pvj w`Gq ivwL Avi wdÌR ˆ^GK Bwjk gvQ evi KGi ivwL| gÅvWvg Lvbv w`GZ ejGj `k wgwbGUi gGaÅ Lvbv

w`GZ cvie| iv®²v Lvwmi gvsm AvGQ, gvBGò×vIGfGb Mig KGi w`e| PjGe bv?

KvG`i ejj, PjGe wK bv Rvwb bv| Avwg euvwP bv wbGRi h¯¨Yvq|

KvG`i AekÅB wbGRi h¯¨Yvq AwÕ©i| ˆm cvwjGq hvIqvi av®¬vq AvGQ| evGMinvGU ^vGK Zvi Õ•zjRxeGbi e®¬z kvgmywób| kvgmywóGbi

KvV ˆPivBGqi Kj AvGQ| Zvi KvGQ gvmLvwbK cvwjGq ^vKv hvq| cÉGqvRGb ˆmLvb ˆ^GK Bw´£qv PGj hvIqv| wWwe cywjGki fvefwã Zvi

KvGQ ˆgvGUB fvGjv jvMGQ bv| ‰B nvivgRv`v AekÅB ZvGK wigvG´£ wbGq hvGe|

cvwjGq ˆhGZ nGj ZvGK ˆhGZ nGe ‰K KvcGo| eÅvM wbGq ˆei nGjB mevB mG±`n KiGe| Lvwj nvGZI hvIqv hvq bv, UvKv-cqmv

``iKvi| KvG`i Zvi gvwbeÅvM LyGj UvKv àbj| ‰K nvRvi UvKvi ‰KUv ˆbvU AvGQ| fvswZ UvKv AvovB kGqi gGZv| ‰Z AÍ¸ UvKv wbGq

iIbv nIqv wVK bv| KGqKUv Ri‚wi wRwbm ˆKbv `iKvi ‰B eGj ˆm wK gÅvWvGgi KvGQ UvKv PvBGe? gÅvWvg ‰Lb `ytL-av®¬vq AvGQ| ‰B

AeÕ©vq KZ UvKv hvGœQ Zv ˆKD ˆLqvj KGi bv|

i‚webv AvaN¥Ÿvi Ici ˆkvevi NGii iwKs ˆPqvGi eGm AvGQ| Zvi nvGZ ˆgvevBj ˆdvb| AvaN¥Ÿv AvGM ˆm iweGK ˆUwjGdvb

KGiwQj| Lwjj wVKB eGjGQ, iwei Avmj bvg iweDj| i‚webv ˆQvU KGi WvGK iwe| i‚webvGK ˆQvU KiGj nq i‚we, iweDj ˆQvU KiGj

nq iwe| i‚we iweGZI wgj| cÉ^g `yevi KGj iwe aGiwb| Z‡ZxqevGi aij|

i‚webv ejj, ‰Þzwb evmvq AvGmv| cywjk Ii ˆWWewW evmvq w`Gq ˆMGQ| ‰Lb Avi Avgvi gv^v KvR KiGQ bv| ˆZvgvGK eÅeÕ©v KiGZ

nGe|

// Original page 15
[[page-15]]

iweDj ejj, ˆZvgvi evmvq Avmv mÁ¿e bv| cwòKvq wbDR nGqGQ RvGbv? ˆmLvGb Avgvi bvg AvGQ| LyeB dvjZz cwòKv, ˆKD cGo

bv@mvZmKvj bvg| ˆnwWs KGiGQ@‘Õ¨x KZ‡ÆK AaÅvcK Õ¼vgx Lyb’| ˆZvgvGK cGo ˆkvbve?

cGo ˆkvbvGZ nGe bv| cwòKv wbGq PGj ‰Gmv|

ejjvg ˆZv Avmv mÁ¿e bv| Avevi wbDR nGq hvGe| wWwe cywjkI AvgvGK mG±`n KiGQ| wKQyÞY AvGM wWwe cywjGki ‰K B´ÖGcÙi

ˆUwjGdvb KGiGQ, bvg Lwjj|

Zzwg Zv nGj AvmGZ cviQ bv?

bv mÁ¿e bv| ˆZvgvGK evÕ¦e eySGZ nGe| ˆZvgvi evwoi mvgGb wbøq mvsevw`K NyiNyi KiGQ|

Avgvi evwoi mvgGb ˆKvGbv mvsevw`K NyiNyi KiGQ bv|

Iiv AvovGj-AveWvGj ^vGK| myGhvMgGZv D`q nq| ‰G`i Avwg myGhvM ˆ`e bv|

AvœQv, wVK AvGQ|

i‚webv, mwi|

mwi nIqvi wKQy ˆbB|

i‚webv ˆgvevBj nvGZ iwKs ˆPqvGi `yjGQ| ˆePvwiGK ˆ`GL gvqv jvMGQ| ˆKD Zvi cvGk ˆbB, AekÅ ˆm PvGœQI bv ˆKD Zvi cvGk

^vKzK| Zvi evev-gv AvGgwiKvq ^vKGjI ˆek wKQy AvñxqÕ¼Rb XvKvq ^vGKb| cywjGki ‰KRb AÅvwWkbvj AvBwR Zvi PvPvGZv fvB|

i‚webv KviI mGãB ˆhvMvGhvM KiGQ bv|

iwKs ˆPqvGii `yjywb e®¬ KGi i‚webv WvKj, KvG`i!

KvG`i mGã mGã DcwÕ©Z nGjv| ‰Lb Zvi nvGZ Zmwe| ˆm Zmwe ˆNvivGœQ, wK¯§ gGb gGb wKQy coGQ bv| coGj Avwg eySGZ

cviZvg| KvG`Gii KgÆKvGí Avwg gRv cvwœQ| g†ZzÅi cGiI gRv cvIqvi welqUv bÓ¡ nGœQ bv, ‰Uv fvGjv|

KvG`i! wmMvGiU wbGq AvGmv|

‰K KvUzÆb wbGq Avwm, gÅvWvg?

AvGbv|

mvjgv `yB-‰KUv UzKUvK wRwbm ˆPGqGQ| Pv-cvZv, wPwb, Kwd| Abbe?

AvGbv|

`ycyGi wK NGi cvK nGe, gÅvWvg?

cvK nGe bv ˆKb? gvbyGli g†ZzÅ nq, Þzavi g†ZzÅ nq bv|

KvG`i ejj, Avcbvi Avi wKQy jvMGe gÅvWvg?

‰KUv cwòKv wbGq AvmGZ cvGiv, mKvj bv Kx ˆhb bvg?

mvZmKvj?

nuÅv, mvZmKvj| ^vK, cwòKv AvbGZ nGe bv|

UvKv ˆ`b, gÅvWvg| `yB nvRvi w`GjB PjGe|

Avgvi LvGUi Wvb w`GKi WÈqvGi UvKv AvGQ| ZvovZvwo AvmGe| Avgvi wmMvGiU ˆkl|

WÈqvi LyGj KvG`i 50 nvRvi UvKvi ‰KwU evw´£j ˆcj| eÅvsGKi muvUv KvMR ˆbB, evw´£j ˆ^GK wKQy nqGZv LiP nGqGQ| KvG`i evw´£j

wbGq ˆei nGœQ| Avwg ‘ˆPvi ˆPvi’ eGj wPrKvi KiwQ| Avgvi wPrKvi i‚webvi KvGb ˆMj bv| hvIqvi K^vI bv|

Avwg KvG`Gii mGã AvwQ| KvG`i jÞÅ KiGQ bv AvgvG`i evwoi mvgGb `uvwoGq ^vKv ‰KRb ZvGK AbymiY KiGQ| ˆm B´ÖGcÙi

LwjGji ˆjvK| ZvGK ivLv nGqGQ evwoi Ici bRi`vwii RbÅ| ˆm ˆgvevBGj LwjGji mGã ˆhvMvGhvM Kij|

KvG`i ivÕ¦vi cvGki ‰K PvGqi ˆ`vKvGbi mvgGb `uvovGbv| PvGqi AWÆvi w`GqGQ| KvG`i wmMvGiU Lvq bv| ‰KUv wmMvGiUI ˆm awiGq

LyK LyK KGi Kvkj| ˆm fqven AvbG±` AvGQ| gywî×i Avb±`|

Lye BGœQ wQj KvG`Gii mGã mGã ^vKvi| ˆmUv mÁ¿e nGjv bv| Avwg ‰Lb cwjGbi NGi| cwjb Zvi ˆdmeyGK BsGiwRGZ Z^Å w`GœQ|

ZG^Åi evsjvUv ‰gb:

Avgvi mrevevi keG`n ‰Lb eviv±`vq ivLv AvGQ| KwdGbi ˆfZi wZwb AvGQb| Avgvi Lvivc jvMGQ| Kv®²v cvGœQ| Avgvi ‰B

mrevev AvgvGK Lye Av`i KiGZb| wZwb AZÅ¯¦ ævbx wQGjb| AvgvGK weævGbi AGbK wKQy ejGZb| wZwb Aâ KGi ‰Kevi AvgvGK

ˆ`wLGqGQb ˆh 3 mgvb 2 nGZ cvGi| wZwb KxfvGe KGiwQGjb Avgvi gGb ˆbB| wZwb ˆeuGP ^vKGj Zuvi KvGQ wkGL wbZvg|

i‚webv iv®²vNGi, Zvi nvGZ ‰K nvRvi UvKvi ‰KUv ˆbvU| i‚webv mvjgvGK ejj, AvgvGK ‰K cÅvGKU wmMvGiU ‰Gb `vI, KvG`i ˆ`wi

KiGQ | wmMvGiU AvbGZ cviGe bv? WÈvBfvi AvGmwb| WÈvBfvi ^vKGj ZvGK cvVvZvg|

wmMvGiU AvbGZ cvie Avcv| Avcwb ˆMGU `vGivqvbGi eGj ˆ`b| `vGivqvb AvUKvGe|

eGj w`wœQ| ZvovZvwo ‰Gmv| ˆebmb AÅv´£ ˆnGRm AvbGe@jvBU|

wR AvœQv| hve Avi Avme|

mvjgv Zvi eÅvM wbGq ˆei nGjv| Avi wdij bv|

cwjGbi ˆdmeyGKi AvcGWU:

AvR AvgvG`i evmvq iv®²v nqwb| Avwg Avi gv AGié Rym ‰es `ya ˆLGqwQ| Avi wWg wm«¬ ˆLGqwQ| KvG`i PvPv Avi mvjgv Lvjv

evRvi KiGZ wMGq wdGi AvGmbwb| gvGqi aviYv, Zviv `yRGbB cvwjGq ˆMGQ|


m®¬ÅvGejv wWwe B´ÖGcÙi Lwjj ˆUwjGdvb Kij| i‚webv ˆUwjGdvb aij| Lwjj ejj, gÅvWvg, AvcbvG`i evwoi ˆKqviGUKviGK gnvLvjx

evmGÕ¡kb ˆ^GK AÅvGiÕ¡ Kiv nGqGQ| ZvGK ^vbv nvRGZ wbGq hve, bv wK Avcbvi KvGQ cvwVGq ˆ`e?

i‚webv ejj, Avgvi KvGQ cvwVGq w`b|

// Original page 16
[[page-16]]

Avcbvi evmvi KvGRi ˆgGq mvjgvi ˆgvevBj ˆdvb Avgiv UÇÅvK KiwQjvg| ZvGKI aiv nGqGQ| Zvi eÅvGM ˆek wKQy wRwbmcò cvIqv

ˆMGQ| ZvGKI wK cvwVGq ˆ`e?

nuÅv| ivGZ iv®²v KiGe|

Lwjj ejj, gÅvWvg, Avwg Avgvi RxeGb AGbK A«¿zZ gvbyl ˆ`GLwQ, Avcbvi gGZv ˆ`wLwb|

i‚webv ejj, Avgvi ˆPGqI AGbK A«¿zZ Avgvi Õ¼vgx| wZwb gviv ˆMGQb, Zuvi me A«¿zGZi mgvwµ¦ nGqGQ| Avwg wK AvcbvGK ‰KUv

AbyGiva KiGZ cvwi?

cvGib |

Õ¼vgxi ˆWWewW wbGq Avwg wecG` cGowQ| fvGjv wecG` cGowQ| Avcwb wK ˆKvGbv MwZ KiGZ cvGib?

Kx aiGbi MwZ?

ˆWWewW Zuvi MÉvGgi evwoGZ cvVvGZ cvGib?

nuÅv, cvwi|

mvmGcÙ wnGmGe Avcbviv wK AvgvGK AÅvGiÕ¡ KiGeb?

‰LGbv bv| Avcwb ˆZv cvwjGq hvGœQb bv, AvgvG`i bRi`vwiGZB AvGQb| ZGe Avcbvi e®¬z iweDjGK AÅvGiÕ¡ Kiv nGqGQ| hvGK

Avcwb Av`i KGi iwe WvGKb|

I, AvœQv|

Avcbvi RbÅ AvGiKwU `ytmsev` AvGQ| Avcbvi nvReÅvG´£i eo gvgv wKQyÞY AvGM gviv ˆMGQb| mwi |

i‚webv ejj, Avcwb mwi nGœQb ˆKb? Avcwb ˆZv ZvGK gvGibwb|

AvcbvGK ‰KwU `ytmsev` w`Gq KGÓ¡i KviY nGqwQ eGj mwi ejjvg|

wVK AvGQ|

Avgvi KvQ ˆ^GK Avi ˆKvGbv mvnvhÅ wK Avcwb Pvb|

PvB | ‰bvGqZ bvGgi ‰KRGbi ˆUwjGdvb bvÁ¼vi ˆ`Geb eGjwQGjb| ˆUwjGdvb bvÁ¼viUv PvB| Zvi AvGM RvbGZ PvB Avwg Avcbvi

cÉavb mvmGcÙ| AvgvGK mvnvhÅ KiGZ PvGœQb ˆKb?

Avcbvi gGZv i…ceZx ‰KRb duvwmGZ SzjGe fveGZ KÓ¡ jvMGQ eGjB nqGZv ejwQ|

Avwg Kzi…cv nGj wK ‰bvGqGZi bvÁ¼vi Avcwb w`GZb bv?

nqGZv bv| bvÁ¼viUv wjLyb|

‰KUz ai‚b, Avwg KvMR-Kjg wbGq AvmwQ|

i‚webv KvMR-Kjg AvbGZ ˆMGQ Avwg AvZÆwPrKvi KiwQ@i‚webv fzj KiGe bv| fqsKi duvG` cv ˆ`Ge bv| Lei`vi Lei`vi

Lei`vi|

i‚webv kv¯¦ fwãGZ ˆUwjGdvb bvÁ¼vi wjLj| i‚webv duvG` cv w`GZ hvGœQ, Avwg ZvGK AvUKvGZ cviwQ bv| Avwg ‰KRb AeRvfÆvi Qvov

wKQyB bv| ÷ay ˆ`Lv Qvov Avgvi wKQy Kivi ˆbB|

i‚webvi ˆVuvGUi duvGK euvKv nvwm| ‰B nvwm Avgvi cwiwPZ| ˆKvGbv `yÓ¡z eyw«¬ Zvi gv^vq ‰GmGQ| fqsKi ˆKvGbv `yÓ¡z eyw«¬| `yÓ¡z eyw«¬Uv

Kx nGZ cvGi|

i‚webv ‰bvGqZ bvGgi wWwe cywjGki ‰GRG´Ÿi KvGQ ˆUwjGdvb KiGQ| Avwg AvZâ wbGq AGcÞv KiwQ|

Avcwb ‰bvGqZ|

üu |

÷GbwQ, Avcwb gvbyGli `Õ¦LZ bKj KiGZ cvGib| AvmGjB wK cvGib?

Avcbvi Kx `iKvi ˆmUv eGjb| avbvB-cvbvB K^v bv| KvGRi K^vq Avmyb|

Avgvi Õ¼vgxi `Õ¦LZ bKj KiGZ cviGeb?

bv cvivi KviY ˆ`wL bv|

‰KUv KvMGR ˆjLv ^vKGe, Avgvi g†ZzÅi RbÅ wWwe B´ÖGcÙi Lwjj `vqx| ‰i wbGP Avgvi Õ¼vgxi `Õ¦LZ KGi w`Geb| cviGeb?

`Õ¦LGZi bgybv wWwe B´ÖGcÙi Lwjj mvGnGei KvGQ AvGQ| Zvi KvQ ˆ^GK wbGq ˆbGeb| ‰B KvGRi RbÅ KZ UvKv ˆbGeb?

Avwg ejjvg, mvevm|

AvdGmvm Avgvi mvevm ejvUv i‚webv ÷bGZ ˆcj bv| i‚webvi eyw«¬GZ PgrK‡Z nGq Avwg ‰KRxeGb AGbKevi eGjwQ, mvevm|

‰Kevi Avgvi `vwg ‰KUv ˆgvevBj ˆdvb nvwiGq ˆMj| ˆgvevBj ˆdvbUv ev^i‚Ggi ˆewmGbi Ici ˆiGL gyL ayGq ˆkvevi NGi XzGKwQ|

ZLb gGb coj ˆgvevBj ˆdvb ev^i‚Gg ˆiGL ‰GmwQ| ev^i‚Gg XzGK ˆ`wL ˆdvb ˆbB| ÷ay ev^i‚Gg ˆKb mviv evwoGZ ˆKv^vI ˆbB|

i‚webv ejj, ˆkvevi NGi Avwg eGm AvwQ| Zzwg ev^i‚g ˆ^GK ˆei nIqvi ci ˆmLvGb ˆKD ˆXvGKwb|

Avwg ejjvg, ˆgvevBj ˆdvbUv ev^i‚Ggi ˆewmGb Avwg ˆiGLwQ| ˆewmb mvgvbÅ ˆfRv wQj, UvIGqj w`Gq gyGQ Zvi Ici ˆiGLwQ|

i‚webv ejj, ZvnGj ‰B KvRUv Zzwg KGiQ ˆZvgvG`i BDwbfvwmÆwUi ev^i‚Gg| ˆZvgvi ˆeËBb BDwbfvwmÆwUi ev^i‚g Avi evwoi ev^i‚Gg

àwjGq ˆdjGQ| ˆUwjGdvb KGi ˆLuvR bvI|

ˆLuvR wbGq BDwbfvwmÆwUi ev^i‚Gg ˆgvevBj ˆdvb cvIqv ˆMj| Avwg gGb gGb ejjvg, mvevm!


4.

m®¬Åv QqUv|

// Original page 17
[[page-17]]

gvBGò×vevGm KGi Avgvi ˆWWewW MÉvGgi evwoi w`GK iIbv nGqGQ| WÈvBfvGii cvGk eGmGQ KvG`i| ‰K w`Gb ˆm eyGov nGq ˆMGQ|

ˆmvRv nGq nuvUGZ cviGQ bv, euvKv nGq nuvUGQ| K^vI cwiÓ•vi ejGZ cviGQ bv| me K^vB RovGbv| aiv covi ci cywjk ZvGK fvGjvgGZv

Wjv w`GqGQ| wbGPi ˆVuvU ˆKGU dzGj DGVGQ| ‰B ˆdvjv gGb nq AviI evoGe| ˆm ˆKb cvwjGq wMGqwQj, ‰B eÅvLÅv i‚webvGK w`GZ

wMGqwQj| i‚webv ejj, ˆZvgvi K^v cGi ÷be| ˆZvgvi mÅvGii ˆWWewW wbGq iIbv nGq hvI|

Kx wbGq iIbv ne, gÅvWvg?

ˆZvgvi mÅvGii ˆWWewW|

KvG`i dÅvmdÅvGm Mjvq ejj, ‘wR gÅvWvg|’ ‰gwbGZB ˆm AvZGâ wQj, ‰Lb ˆmB AvZâ `k àY evoj| ˆPvL ˆKvUi ˆ^GK ˆei

nIqvi Dcò×g nGjv|

KvGRi ˆgGq mvjgv wdGi ‰GmGQ| ˆhb wKQyB nqwb, ‰B fve wbGq ˆm iv®²v emvGœQ| ‰Kevi ‰Gm eGj ˆMj, giv evwoGZ gvQ LvIqv

wbGla| Bwjk gvGQi e`Gj wWGgi mvjyb Kwi?

i‚webv nvB ZzjGZ ZzjGZ ejj, hv BœQv KGiv|

wWwe B´ÖGcÙi Lwjj Avgvi Õ¡vwWi‚Gg| ˆmLvGb ˆm Kx KiGQ, wKQyB eySGZ cviwQ bv| ˆmB NiUv ˆ`LGZ cvwœQ bv| i‚webvGK ˆ`LGZ

cvwœQ, ˆm m®¬ÅvGejvi kvIqvi wbGœQ| cwjbGK ˆ`LwQ, ˆm KwÁ·DUvGi ˆMg ˆLjGQ| ˆMGgi bvg ‘Wvqg´£ ivk’| cwjGbi mGã ‰B ˆLjv

AvwgI AGbKevi ˆLGjwQ| AÅvsKGii ˆMvcb ànvq XzGK nxiv msMÉn KiGZ nq| bvbv SvGgjv AvGQ| gv^vq cvnvo ˆfGO cGo, mvc ‰Gm

ˆQvej ˆ`q| Avwg me SvGgjv ‰ovGZ cvwi bv| cwjb cvGi|

Avwg ‰Lb kxZvZÆ| kixi ^vKGj ejZvg, kxGZ kixi KuvcGQ| kixi ˆbB, Zvi ciI kxGZi Abyf„wZ| fq nGœQ, ‰B kxZ wK AviI

EvoGe? hw` AviI evGo, ZLb Kx nGe? Zvi ˆPGq eo wP¯¦v, Avgvi ˆWWewW Kei nGq hvIqvi ci Avgvi Kx nGe? Avgvi AwÕ¦Z½ ^vKGe,

bvwK ^vKGe bv? KeGi bvgvGbvi `†kÅ wK Avwg ˆ`LGZ cve? ‰B `†kÅUv Avgvi ˆ`Lvi kL AvGQ|

B´ÖGcÙi Lwjj ˆUwjGdvGb RvwbGqwQj, eo gvgv gviv ˆMGQb| Avgvi RbÅ ‰Uv wQj AwZ AvbG±`i msev`| eo gvgvi wbøqB Avgvi

AeÕ©v nGqGQ| Zvi mGã ˆhvMvGhvM KiGZ cvie|

‰LGbv ˆmUv mÁ¿e nqwb| ˆh AvgvGK wbq¯¨Y KiGQ, ˆm eo gvgvi mGã AvgvGK ˆ`Lv Kivqwb| ˆm wK AvgvGK wbGq weGkl ˆKvGbv

cwiKÍ¸bv KiGQ? cwiKÍ¸bvUv Kx?

cyGiv ÕÃ†wZkwî× AvgvGK ˆ`Iqv nqwb| AvgvGK wel LvIqvGbvi welq Avgvi gGb ˆbB| RyuB bvGgi ˆh ˆgGqwU ivZ wZbUvq i‚webvGK

ˆUwjGdvb KGiwQj, Zvi K^v gGb ˆbB| cwjGbi evev ˆK, Zv-I gGb ˆbB|

‰gbwK nGZ cvGi ˆh AvgvGK ÷ay cÉGqvRbxq Z^Å ˆ`Iqv nGœQ? AcÉGqvRbxq Z^Å KwÁ·DUvGii fvBivGmi gGZv| AÅvw´ŸfvBivm ˆcÉvMÉvg

w`Gq AvUGK ˆ`Iqv nGœQ| Av`vi wiGqwjwU eBGq cGowQjvg, gvbyl, RxeR¯§, MvQcvjv@meB nGjv gÅvwUÇÝ QweUvi gGZv, KwÁ·DUvGii

ˆLjvi gGZv fviPzqvj ˆMg| Avgiv ‰KRb gvÕ¡vi ˆcÉvMÉvGgi ŠZwi weGbv`b ˆLjv|

i‚webv ˆgGqGK wbGq Pv ˆLGZ eGmGQ| i‚webv h^vixwZ ‰K cU Pv wbGq eGmGQ| wcwiGP KvUv AvGcj, gvLb jvMvGbv ˆUvÕ¡ weÕ•zU| ˆQvë

™ÏvGm ˆe`vbvi im| i‚webv ˆPvLgyL KzuPGK ˆe`vbvi im ˆLj| cwjb ejj, ˆe`vbvi im Zzwg cQ±` KGiv bv?

Kwi ˆZv?

Zv nGj LvIqvi mgq gyL KzuPKvI ˆKb?

i‚webv ejj, KÓ¡v, ‰B RbÅ cQ±` Kwi bv|

Zv nGj LvI ˆKb?

cÉPzi wfUvwgb-B AvGQ, ‰B RbÅ LvB| AÅvw´Ÿ-‰wRs cÉcvwUÆ AvGQ|

ˆe`vbvi im ˆLGj ˆZvgvi eqm evoGe bv?

axGi evoGe|

Zzwg wK AGbK w`b ˆeuGP ^vKGZ PvI?

mevB Pvq|

Avwg PvB bv|

AÍ¸ eqGm gGi ˆhGZ PvI?

üu | IB ˆjvK evevi Õ¡vwWi‚Gg ‰ZÞY aGi Kx KiGQ?

i‚webv PgGK DGV ejj, evev ejQ ˆKb? Zzwg ˆZv IGK Klgbv evev WvKGZ bv|

gGb gGb WvKZvg| ‰Lb Dwb gviv ˆMGQb, ZvB gGb gGb bv ˆWGK wVKgGZv WvKwQ|

Zzwg ZvGK cQ±` Ki?

üu | Zzwg Avgvi cÉGk²i Reve w`œQ bv ˆKb? IB ˆjvKUv evevi Õ¡vwWi‚Gg XzGK Kx KiGQ?

Zvi KvMRcò, WvGqwi@‰B me NuvUvNuvwU KiGQ|

ˆKb?

ˆm wWwe cywjGki ˆjvK| Zvi aviYv, Zzwg ‰Lb hvGK evev WvKQ, ZvGK Lyb Kiv nGqGQ| ‰B welGq Z`¯¦ KiGQ|

ˆK Lyb KGiGQ?

‰LGbv ˆm ˆei KiGZ cvGiwb|

ˆei KiGZ cviGe?

Rvwb bv cviGe wK bv|

kvjÆK ˆnvgm ^vKGj cviZ| kvjÆK ˆnvgGmi AGbK eyw«¬| ZzwgI cviGe, ˆZvgvi AGbK eyw«¬| gv, Zzwg wK Rvb, ˆK Lyb KGiGQ?

bv

IB ˆjvK wK RvGb?

// Original page 18
[[page-18]]

ˆm-I RvGb bv| ZGe Zvi aviYv, Avwg Lyb KGiwQ|

gv, Zzwg wK KGiQ?

bv, Avwg Lyb Kwiwb| Zzwg Avgvi K^v wek¼vm KGiQ?

cwjb mGã mGã ejj, KGiwQ| KviY, Zzwg Klgbv wg^Åv ej bv|

i‚webv ˆQvë wbtk¼vm ˆdGj ejj, Zzwg hvGK ‰Lb evev WvKQ, ‰B gvbylUv cvGqi bL ˆ^GK gv^vi Pzj chÆ¯¦ fvGjv gvbyl| weevwnZ

RxeGb Klgbv ˆKvGbv welq wbGq Avgvi mGã ivM KGiwb|

evev ˆh fvGjv gvbyl, ‰Uv Avwg Rvwb| KwÁ·DUvi ˆMGgi mvcàGjvI RvGb| Zviv mnGR evevGK ˆQvej w`GZ Pvq bv|

Avwg ‰Lb Avi i‚webv I cwjbGK ˆ`LGZ cvwœQ bv| i‚webv I cwjb ‰B gynƒGZÆ ˆh K^vwU ejj, Zv AvgvGK RvbvGbvi RbÅB nqGZv ‰B

`yRbGK ‰ZÞY ˆ`LwQjvg| AvgvGK RvbvGbv ˆkl nGqGQ eGj ‰G`i ˆ`LwQ bv| Avwg ˆ`LwQ LwjjGK| ˆm eBGqi ZvGKi ˆcQb ˆ^GK ˆQvë

‰KUv wkwk D«¬vi KGiGQ| wkkwki MvGq ˆjLv, ‘DBGcvKvi wel’| wkkwki AGaÆKUv Lvwj| Lwjj Lye mveavGb cwjw^Gbi eÅvGM wkwk fGi

cGKGU ivLj| ZvGK AmÁ¿e wPw¯¦Z gGb nGœQ| ˆh wel LvBGq nZÅv KiGe, ˆm weGli wkwk ˆdGj hvGe bv| ZGe AmÁ¿e eyw«¬gZx i‚webv ‰B

KvRwU KiGZ cvGi|

Lwjj fveGQ, ‰B gwnjvi mGã K^vevZÆvq AviI mveavb nGZ nGe| ˆQvULvGUv duv` ˆcGZ ‰GK aiv hvGe bv| Zvi RbÅ jvMGe eo

duv`| ‰bvGqGZi eÅvcviUv ‰B ˆgGq ˆhfvGe nÅvG´£j KGiGQ, Zv weÕÃqKi|

Lwjj ‰Lb Avgvi WvGqwii cvZv DÎŸvGœQ| ‰LvGb ˆm wKQyB cvGe bv| Avwg WvGqwiGZ eÅwî×MZ wKQyB ˆjwL bv| ˆKvqv´Ÿvg RMGZi

inmÅgqZv wbGq ˆjwL| AGâi wKQy cÅvivWÝ ˆjLv nGqGQ| cÅvivWÝàGjv cwjGbi RbÅ ˆjLv| ˆm AZÅ¯¦ cQ±` KGi| ‰B gynƒGZÆ Lwjj

AvMÉn wbGq AGâi ‰KUv cÅvivWÝ ˆ`LGQ| Avwg wjGLwQ:

36 Bwç=1 MR

Dfq cÞGK 4 w`Gq fvM w`jvg

9 Bwç = 1/4 MR

Dfq cGÞ eMÆgƒj Kiv nGjv

9 = 1/4

ZvnGj `uvovq

3 = 1/2

A^Ævr 6 Bwç = 1 MR

‰KUz AvGM ˆ`LvGbv nGqGQ, 36 Bwç mgvb ‰K MR| ‰Lb AGâ cÉgvY Kiv nGjv 6 Bwç mgvb ‰K MR| Kx KGi mÁ¿e?

Lwjj gv^v PzjKvGœQ| KvMR-Kjg wbGq eGmGQ| cÅvivWÝ gv^vq XzGK ˆMGQ| AwZ mvgvbÅ cÅvivWGÝ ˆm AwÕ©i, Avi Avwg XzGK ˆMwQ

cÅvivWGÝi gnvmgyG`Ë|


Lwjj I i‚webv emvi NGi| i‚webv eÅÕ¦ bGL ˆbjcwjk ˆ`Iqv wbGq| AÅvkGUÇi ‰K ˆKvbvq Zvi aivGbv wmMvGiU cyoGQ| wmMvGiGUi ˆfZi

MuvRv fiv AvGQ| weKU M®¬ AvmGQ| i‚webvi nvGZ ˆbjcwjGki eËvk| Avwg `yRbGK ˆ`LwQ| i‚webv Kx fveGQ, eySGZ cviwQ bv| LwjGji

wP¯¦v aiGZ cviwQ| i‚webvi wP¯¦v-KÍ¸bv eÐK KGi ˆ`Iqv nGqGQ| ‰gb mgq wK AvmGe ˆh Avwg ˆ`LGZ cve; wK¯§ ˆK Kx ejGQ, Zv ÷bGZ

cve bv? g†GZi RMr civevÕ¦e RMr| evÕ¦eZv eÅvcviUvB AekÅ AZÅ¯¦ ˆauvqvGU|

KÑvGm evÕ¦eZv wbGq Avwg ‰Kevi ‰KUv eî×‡Zv w`GqwQjvg| Avgvi eî×‡Zvi welq wQj evÕ¦eZvi welqwU gvbyGli gwÕ¦Ó• ŠZwi KGi|

ˆiwUbv ˆ^GK BbdiGgkb gwÕ¦GÓ• hvq| gwÕ¦Ó• Zv cÉGmm KGi AvgvG`i hv ˆ`Lvq, Zv-B AvgvG`i KvGQ wiGqwjwU| cÉGmwms cÉwò×qvq mvgvbÅ

ò‚wU nGj wiGqwjwU AbÅ iKg nGe| Avgiv hv ˆ`LwQ, Zv-B evÕ¦e gGb Kivi wKQy ˆbB| AvgvG`i gwÕ¦Ó• hv fveGZ evaÅ KiGQ, Zv-B evÕ¦e|

KÑvGmi ‰KwU ˆgGq cÉk² Kjj, mÅvi, Avwg ˆh KÑvGm eGm AvwQ, ‰Uv wK evÕ¦e?

Avwg ejjvg, ˆZvgvi bvg Kx?

ˆm ejj, eKzj|

Avwg ejjvg, AvgvG`i gwÕ¦Ó• ‰gb wUÇK KiGZ cvGi ˆh dzGji bvGg hvG`i bvg, ZvG`i ˆ`Lvgvò ˆmB dzGji MG®¬ Pviw`K g g KiGZ

^vKGe| gwÕ¦Ó• ‰B wiGqwjwU ŠZwi KiGQ, hv gƒj wiGqwjwUi evBGi|

Avgvi K^v ˆkl nIqvi AvGMB KÑvGmi ‰KRb Qvò gyL ÷Kbv KGi ejj, mÅvi, Ii Mv ˆ^GK ˆMveGii M®¬ AvmGQ| ˆm wK ZvnGj

ˆMvei?

mevB ˆnv ˆnv KGi nvmGZ ÷i‚ Kij| mevi AvGM nvmj eKzj| Avgvi nvwm ‰j bv| KÑvmfwZÆ QvòQvòxi nvwmi kGõ gv^v MgMg KiGZ

jvMj|

‰Lb Avevi nvwmi kõ ÷bwQ| wòk-PwÍÏkRb QvòQvòxi nvwmi kõ bq| nvRvi nvRvi gvbyGli Pvcv nvwm| wKQy ‰KUv NUGZ hvGœQ| Kx

NUGZ hvGœQ, eySGZ cviwQ bv| Avwg wK AbÅ ˆKvGbv evÕ¦eZvq XzKGZ hvwœQ? nvwmi kõ QvwcGq i‚webvi Mjv ÷bjvg, Õ¡vwWi‚Gg wKQy

ˆcGqGQb?

BbGmKwUmvBGWi ‰KUv ˆevZj ˆcGqwQ| ˆevZGj Kx AvGQ, Zv Rvbvi RbÅ jÅveGiUwiGZ cvVve|

LvZvcò NuvUvNuvwU KGi wKQy cvbwb?

bv Avwg Avcbvi ˆgGq cwjbGK wKQy cÉk² KiGZ PvB|

AvR ev` ^vK| AvGiK w`b Ki‚b| Zvi evevi ˆWWewW mviv w`b eviv±`vq cGo wQj| ˆm msMZ KviGYB AvcGmU|

Lwjj ejj, Avwg hZ `ƒi Rvwb, BdGZLvi mvGne Zvi evev bb|

evev bv nGjI cwjb ZvGK evev WvKv ÷i‚ KGiGQ| AvGM WvKZ bv| AvR ˆ^GK WvKGQ| cwjbGK cÉk² bv KGi Avcwb AvgvGK cÉk²

Ki‚b| hZ BœQv Ki‚b| Avwg wg^Åv K^v ewj bv|

// Original page 19
[[page-19]]

hviv wg^Åv eGj bv, Zviv LyeB wecäbK|

ˆKvb AG^Æ?

Zviv hLb ‰KUv-`yGUv wg^Åv eGj, ZLb ˆmB wg^ÅvGK mZÅ aiv nq| ‰K nvRvi ˆfovi cvGj ‰KUv ˆbKGo XzGK covi gGZv| ‰K

nvRvi mwZÅi gGaÅ ‰KUv wg^Åv| fqsKi wg^Åv|

i‚webv nvmj| LwjGji Dcgv Zvi cQ±` nGqGQ| Lwjj ejj, Avcbvi mGã iweDj mvGnGei ˆh e®¬zZ½, Zv Avcbvi Õ¼vgx KxfvGe

ˆ`LGZb?

ˆKvGbvfvGeB ˆ`LZ bv| ˆm RvbZ, iwei mGã Avgvi ˆKvGbv e®¬zZ½ ˆbB| iwe AwZ KgÆV ‰KRb| meÆKGgÆ cvi`kÆx| ZvGK w`Gq Avwg

bvbv KvR KwiGq wbZvg| wewbgGq mvgvbÅ Awfbq|

‘wewbgGq mvgvbÅ Awfbq’ eÅvcviUv eySjvg bv|

fve Kiv ˆh, Avwg ZvGK AmÁ¿e cQ±` Kwi| nqGZv ev ˆMvcGb fvGjvevwm| weevwnZ nIqvq evav cGo ˆMwQ| bq ˆZv Zvi mGã ˆfGM

ˆhZvg|

Awfbq KGi Avcwb KvR Av`vq KGi ˆbb?

Awfbq QvovI Avwg KvR Av`vq KiGZ cvwi, AbÅGK w`Gq KvR KwiGq wbGZ cvwi| ˆhgb, AvcbvGK w`Gq KvR KwiGq wbjvg| Avcwb

gvBGò×vevGmi eÅeÕ©v KiGjb, ‰KRb cywjk w`Gjb| ˆKvGbv mgmÅv QvovB Avgvi Õ¼vgxi ˆWWewW MÉvGgi evwoGZ iIbv nGq ˆMj|

Avcbvi Õ¼vgx ˆh ivGZ AmyÕ© nGq coGjb, ˆm ivGZi NUbv ejyb| ˆKvGbv wKQy ev` ˆ`Geb bv ev ˆKvGbv wKQy hyî× KiGeb bv|

Þz`Ë wWGUBjmI wK eje?

nuÅv, ejGeb|

ivZ 10Uvi ci ˆ^GK ejv ÷i‚ Kwi| Zvi AvGM ˆ^GK ejvi wKQy ˆbB|

Ki‚b| ˆbjcwjk ˆ`Iqv ˆkl KGi ejyb| Avwg PvB, K^v ejvi mgq Avcwb Avgvi ˆPvGLi Ici ˆPvL ivLGeb| ˆKD AbÅw`GK ZvwKGq

K^v ejGj Avgvi AÕ¼wÕ¦ jvGM|

i‚webv ˆbjcwjk ˆ`Iqv ˆkl Kij| `yB nvZ ˆgGj ˆ`Lj, Zvici K^v ejv ÷i‚ Kij|

ivZ 10Uvi gGaÅ AvgvG`i ivGZi Lvevi nGq hvq| Avgiv ˆh hvi gGZv AvgvG`i KgÆKví ÷i‚ Kwi|

eÅvLÅv KGi ejyb| ˆh hvi gGZv KgÆKví gvGb Kx?

i‚webv wmMvGiU awiGq K^v ejGQ, Avwg LwjGji ˆPGqI AGbK AvMÉn wbGq ÷bwQ| i‚webv ‰Lb hv ejGQ, Zvi ÕÃ†wZ Avgvi ˆbB| MeB

bZzb ÷bwQ|

i‚webv ejGQ, AvgvG`i ˆh hvi KgÆKví eÅvLÅv KiGZ ejGQb, KiwQ| Avgvi ˆgGq cwjb AwUwÕ¡K| ˆm AGbK ivZ chÆ¯¦ RvGM|

KwÁ·DUvGi ˆMg ˆLGj| ˆdmeyK LyGj eGm ^vGK| Zvi ˆdmeyGKi e®¬zi msLÅv cuvP nvRvi AvVvGiv| ‰G`i cÉGZÅGKi bvg ˆm RvGb|

Avgvi Õ¼vgx Õ¡vwWi‚Ggi `iRv wfwoGq eGm ^vGKb| eB cGob, ˆjLvGjwL KGib| cÉwZ ivGZ AvaN¥Ÿv ˆgwWGUkb KGib| Avwg Klgbv

ˆmB NGi hvB bv|

Avwg ^vwK ˆkvevi NGi| ˆewki fvGM ivGZ f„GZi Qwe ˆ`wL| Qwe ˆ`Lvi gvSLvGb ‰Kevi ‰Gm ˆe`vbvi im LvB| Avwg `yB ™Ïvm KGi

ˆe`vbvi im LvB| mKvGj ‰K ™Ïvm, ivGZ ‰K ™Ïvm| ˆe`vbvi im ˆLGq cwjGbi NGi DuwK ˆ`B| AvgvGK ˆ`GL cwjb eGj, ˆWv´Ÿ wWÕ¡veÆ wg,

wµÏR| Avwg ewj, AvB jvf BD|

cwjGbi Ni ˆ^GK wbGRi NGi Avwm| Qwe ˆ`Lv ˆkl KGi NywgGq cwo|

ˆmB ivGZ Avwg cvcÆj Õ•vB bvGgi ‰KUv f„GZi Qwe ˆ`LwQjvg|Qwei gvSLvGb ˆe`vbvi Rym ˆLGZ wMGq ˆ`wL ˆUweGj RyGmi ™Ïvm

ˆbB| KvGRi ˆgGqUv bZzb, ˆm Rym evwbGq ZvGZ `yB UzKiv eid w`Gq Lvevi ˆUweGj ivLGZ fzGj ˆMGQ| Avwg ˆMjvg cwjGbi NGi| cwjb

ejj, ˆWv´Ÿ wWÕ¡veÆ wg| Avwg ewj, AvB jvf BD|

wbGRi NGi ‰Gm Qwe ˆkl KGi NygyGZ ˆMjvg| KZÞY NywgGqwQ, Rvwb bv| Nyg fvOj cwjGbi SuvKzwbGZ| ˆLvjv `iRv w`Gq ˆm XzGKGQ|

Avgvi Nyg fvOvGbvi ˆPÓ¡v KiGQ|

Avwg aogo KGi ˆRGM DGV ejjvg, Kx nGqGQ gv?

cwjb Kuv`GZ Kuv`GZ ejj, evmvq f„Z ‰GmGQ|

f„ZUv Kx KiGQ?

AvgvGK wWÕ¡veÆ KiGQ|

KxfvGe wWmUveÆ KiGQ?

ˆMuv ˆMuv, NZ NZ KGi kõ KiGQ| `iRvq evwo w`GœQ|

Pj ˆ`wL|

cwjb ejj, Avwg hve bv| Zzwg ˆ`GL ‰Gmv| f„ZUvGK ZvwoGq w`Gq AvmGe|

Avwg cwjGbi NGi ˆMjvg| ˆmLvb ˆ^GK ˆMjvg Õ¡vwWi‚Gg| f„ZinmÅ ˆf` nGjv| Avgvi Õ¼vgx ˆgGSGZ Aævb nGq cGo AvGQ| ˆMuv ˆMuv

kõ gGb nq ˆmB ‰ZÞY KiwQj| Zvi NGi fvOv ™ÏvGmi UzKiv| UzKivq ˆe`vbvi im ˆjGM AvGQ|

AÅvÁ¼yGjG´Öi RbÅ ˆUwjGdvb Kijvg| iweGK ˆUwjGdvb Kijvg| ZvGK nvmcvZvGj wbGq ˆMjvg|

Lwjj ejj, Wvî×viiv wK dzW cqRwbsGqi wPwKrmv KGiGQ? Õ¡gvK Iqvk KGiGQ?

bv Zviv gvB´£ ˆÕ¡ÈvK aGi wbGqGQ| ˆmfvGe wPwKrmv KGiGQ| Avwg ˆh mwZÅ K^v ejwQ, ‰ iKg wK gGb nGœQ?

nuÅv| ZGe KvGRi ˆgGqUv bZzb ‰GmGQ, K^vUv ˆZv wg^Åv| Avwg hZ `ƒi Rvwb, mvjgv bvGgi ˆgGqUv Avcbvi Õ¼vgxi g†ZzÅi ci RGqb

KGiGQ| Avcbvi ‰B AskUv wK wg^Åv bq?

nuÅv, wg^Åv|

‰B wg^ÅvUv ˆKb eGjGQb?

// Original page 20
[[page-20]]

Rvwb bv ˆKb ejjvg|

Lwjj ejj, Avwg Rvwb| Avcwb Lye àwQGq MÍ¸ ejGZ ˆMGQb| àwQGq MÍ¸ ejGZ ˆMGj AcÉGqvRbxq wRwbm PGj AvGm| AvcbviI

‰GmGQ|

nGZ cvGi|

Avcbvi ˆgGq cwjb Zvi evevGK Lye cQ±` KGi, Avcwb eGjGQb| wVK bv?

nuÅv, wVK|

ˆm Zvi evevi mGã ivZ ˆRGM KwÁ·DUvi ˆMg ˆLGj|

nuÅv|

Zvi NGii cvGkB Zvi evevi Õ¡vwWi‚g| ˆm f„GZi fq ˆcGq Zvi evevi NGi bv wMGq AvcbvGK ˆKb RvMvj?

Rvwb bv|

Avgvi aviYv, Avcbvi ˆgGq Avcbvi KvGQ AvGmwb| Avcwb nii gywf ˆ`GLb| f„GZi kõ AvcbviB ˆkvbvi K^v|Zv Qvov AwUwÕ¡K

wk÷iv f„Z fq cvq bv, gvbyl fq cvq|

i‚webv wKQy ejj bv| ˆm mvgvbÅ fq cvGœQ| Nb Nb wmMvGiGU Uvb w`GZ ˆ`GL ˆm iKgB gGb nGœQ| Lwjj ejj, KvGRi ˆgGqi cÉmGã

Avevi wdGi Avwm| IB ivGZ Avcbvi evmvq KvGRi ˆgGq wQj bv, ZvB bv?

nuÅv|

KvG`i wK ˆe`vbvi im evbvq?

bv

ZvnGj Avwg wK aGi wbGZ cvwi, ˆe`vbvi im Avcwb evwbGqwQGjb?

aGi wbGZ cvGib|

AvœQv, ‰ iKg wK nGZ cvGi, IB ivGZ Avcbvi ˆe`vbvi im ˆLGZB BGœQ KiwQj bv, Avcwb Õ¼vgxi KvGQ ™Ïvm wbGq ˆMGjb| ˆe`vbvi

imUv bÓ¡ bv KGi ZvGK ˆLGq ˆdjGZ ejGjb|

i‚webv KwVb Mjvq ejj, Avcwb wK cÉgvY KiGZ PvGœQb, IB ivGZ Avwg ˆe`vbvi im evwbGq ZvGZ wel wgwkGq Avgvi Õ¼vgxGK

LvBGqwQ?

Avwg wKQyB cÉgvY KiGZ PvwœQ bv| Avwg AbygvGbi K^v ejwQ| ‰KUv wek¼vmGhvMÅ wmbvwiI `uvo KivGbvi ˆPÓ¡v KiwQ| ‰i ˆewk wKQy

bq |

i‚webv ejj, AvRGKi gGZv ˆRiv KivUv wK e®¬ Kiv hvq?

ˆRiv KiwQ bv ˆZv| ˆRiv KiGe DwKj| Avcwb KvVMovq `uvovGeb, DwKj ‰GKi ci ‰K cÉk² KiGe| AGbK ˆbvsiv cÉk² KiGe|

wò×wgbvj jBqviiv i…ceZxG`i ˆbvsiv cÉk² KiGZ cQ±` KGi| DwKjG`i ˆbvsiv cÉGk²i nvZ ˆ^GK euvPvi ‰KUv Dcvq nGœQ Õ¼xKvGivwî×gƒjK

Revbew±` ˆ`Iqv|

i‚webv ejj, Zvici nvwmgyGL duvwmGZ SzGj cov|

Lwjj ejj, ˆgGqG`i g†ZzÅ`í ˆ`Iqvi eÅvcvGi Av`vjZ bgbxq ^vGK| Avcwb cÉgvY Kivi ˆPÓ¡v KiGeb ˆh Avcbvi Õ¼vgx AvcbvGK

gvbwmK I kvixwiKfvGe wbhÆvZb KiZ| NGi i…ceZx Õ¨x ˆiGL ˆm ˆekÅvq Mgb KiZ| KvGRi ˆgGqG`i mGã Zvi kvixwiK mÁ·KÆ wQj|

‰me ˆ`GL÷Gb Avcbvi gv^v wVK wQj bv| ˆfGe ˆ`LGeb| gÅvWvg, Avwg DwV| AvMvgxKvj gÅvwRGÕ¡ÈGUi mvgGb Revbew±` ˆ`Geb| ˆQvë

‰KUv `ytmsev` AvGQ| `ytmsev`Uv wK ˆ`e?

w`b| Avcbvi mymsev`àGjvI `ytmsevG`i gGZv|

Lwjj DGV `uvovGZ `uvovGZ ejj, Lye eo `ytmsev` AekÅ bq| Avcbvi Õ¼vgxi ˆWWewW wbGq ˆh gvBGò×vevmwU hvwœQj, ˆmwU LvG` cGo

ˆMGQ| KvG`Gii VÅvs ˆfGO ˆMGQ| ˆm nvmcvZvGj fwZÆ nGqGQ|

i‚webv kõ KGi ˆnGm ˆdjj| Avgvi wbGRiI nvwm AvmGQ| i‚webv ˆnGm ˆdjvi KviY Lwjj aiGZ cviGQ bv| ZvGK LvwbKUv

KbwdDR&W& gGb nGœQ| KvG`i ˆh Kqevi gvBGò×vevm ev evGm KGi XvKvi evBGi ˆMGQ, ˆm KeviB AÅvKwmGW´Ÿ nGqGQ ‰es cÉwZeviB Zvi

cv ˆfGOGQ| eÅvcviUv KvKZvjxq, bvwK ˆevGai AMgÅ AbÅ wKQy?

i‚webv Mv `ywjGq nvmGQ| ‰B nvwmi ‰KUv bvg AvGQ, ÷ay ˆVuvGU nvmv bv, meÆvGã nvmv| kixi nvmv|

Lwjj ejj, Avcbvi ˆgGq cwjb mÁ·GKÆ RvbGZ PvwœQ| ˆm wK Avcbvi AvGMi nvReÅvG´£i m¯¦vb?

i‚webv ejj, Avwg ‰KeviB weGq KGiwQ| Avgvi AvGMi nvReÅv´£ eGj wKQy ˆbB|

ZvnGj cwjb ˆK?

cwjb Avgvi ˆQvU ˆevGbi ˆgGq| Avgvi ˆQvU ˆevGbi weGq nqwb| cwjGbi R¯Ã Zvi RbÅ weivU mgmÅv nGqwQj| cwjbGK Zvi KvQ

ˆ^GK wbGq Avwg Avgvi ˆevbGK gywî× ˆ`B| cwjb RvGb, Avwg Zvi gv|

Avcbvi ˆQvU ˆevGbi welGq ejyb|

ˆm AvGgwiKvq ^vGK| weGq KGiGQ| myGL AvGQ| ‰B nZÅv gvgjvq ˆm ˆKvGbvfvGeB hyî× bq| KvGRB Zvi welGq wKQy eje bv|

Avcwb cvwjGq gv ˆmGRGQb| Avcbvi Õ¼vgx ˆKb evev mvRGjb bv|

Avwg PvBwb | Avgvi Õ¼vgx ‰KRb cweò gvbyl| Acweò ˆKvGbv wKQyi mGã ˆm hyî× ˆnvK, Zv PvBwb|

Acweò ˆKvGbv wKQyi mGã hyî× ^vKGZ Avcbvi Avcwî ˆbB, bv?


Mvwo LvG` cGoGQ ÷bGj gGb nq wMwiLv`| cÉ^g hLb ÷bjvg Avgvi ˆWWewW enb Kiv gvBGò×vevm LvG` cGoGQ, ZLb ˆfGewQjvg, fqven

wKQy NGUGQ| ‰Lb Avwg AKzÕ©Gj AvwQ| ˆZgb wKQy NGUwb| ivÕ¦vi cvGki b`Ægvq cGo wMGqwQj| avØvavwØ KGi Mvwo ˆZvjv nGqGQ|

WÈvBfvi Õ¡vUÆ ˆbIqvi ˆPÓ¡v KiGQ| Bwéb wKQyUv Niii kõ KGi ˆ^Gg hvGœQ|


== Chapter 3

// Original page 21
[[page-21]]

KvG`iGK nvmcvZvGj ˆbIqv nGqGQ ÷GbwQjvg, ‰UvI mwZÅ bq| ˆm wKQyÞY ci ci cv ˆPGc aGi ˆMvOvwbi AvIqvR KiGQ| Zvi

ˆPnviv bxj eYÆ aviY KGiGQ| AwÝGRGbi NvUwZ nGj gvbyl bxj eYÆ aviY KGi| KvG`Gii AekÅB AwÝGRGbi Afve nGœQ| ZvGK `Ë‚Z

nvmcvZvGj ˆbIqv `iKvi|

AÅvwÝGW´Ÿ nGqGQ kvjeGbi ˆfZGii ivÕ¦vq| AvkcvGk ˆKvGbv ˆjvKRb ˆbB, ZGe cywjGki ‰KUv wRc ‰GmGQ| gvBGò×vevm `wo w`Gq

wRGci mGã euvav nGœQ| `wo ˆUGb wbGq hvIqv nGe|

gvBGò×vevm hLb PGj hvGe, ZLb AvwgI wK ZvG`i mGã hve? bvwK Avwg ‰Kv cGo ^vKe kvjeGb? Kx NUGe, wKQyB Rvwb bv| Avgvi

kxZfve cÉej fveGQ| wngkxZj nvIqv ‰KUv weGkl w`K ˆ^GK AvmGQ| ˆmB w`K Dîi, `wÞY, cƒeÆ bv cwøg, ˆK RvGb!

cywjGki wRc gvBGò×vevm wbGq PGj ˆMGQ| gvBGò×vevGmi ˆfZi Avgvi ˆWWewW| Avwg (ev Avgvi ˆPZbv) ‰Kv cGo AvwQ| ‰i ˆKvGbv

gvGb nq? KZÞY ^vKe ‰LvGb?

g†ZzÅi cGii RMGZ mgq ^vKvi K^v bq| KvGRB KZÞY ‰Kv cGo ^vKe, ‰B wP¯¦vI A^Ænxb| nqGZv Ab¯¦Kvj cGo ^vKe| mƒhÆ

‰Kmgq evgb bÞò nGq c†w^ex wMGj LvGe, Avwg ‰LvGbB cGo ^vKe|

ˆhw`K ˆ^GK wngkxZj nvIqv AvmGQ, ˆmw`GK AvKvGk ‰KaiGbi Avfv ˆ`LwQ| ‰i gvGb Kx? nVvr ˆmB Avfvi w`GK ‰KaiGbi Uvb

Abyfe Kijvg| Lye nvjKvfvGe wKQy ‰KUv AvgvGK UvbGQ| Avgvi Ab¯¦ hvòv wK ˆmB w`GK? ˆKv^vq hve?

Avwg nZvk Mjvq ejjvg, ‰LvGb ˆKD wK AvGQb, whwb AvgvGK mvnvhÅ KiGeb? K^v ˆkl nIqvi AvGMB eGbi ˆfZi ˆ^GK wkqvj

WvKGZ jvMj| wkqvj cÉnGi cÉnGi WvGK| ‰Lb ˆKvb cÉni?

ˆKD ‰KRb wkqvGji WvGKi mGã wgwjGq Qov ejGQ@

wkqvj WvGK üØvüqv

ZzwnbG`i KvGRi eyqv

ZvB ˆcGqGQ fq

Zvi hZ mvnm wQj

me nGqGQ Þq|

Rq wkqvGji Rq|

Qov cvV KiGQ Lwjj| Avgvi AeÕ©vb ‰Lb LwjjG`i evmvq| LwjGji mvgGb cuvP-Qq eQGii ‰KwU ˆgGq| ‰i bvg wbøqB Zzwnb|

Lwjj Zvi m`Å ˆjLv Qov ˆgGqGK cGo ˆkvbvGœQ| ZzwnGbi Qov ˆkvbvi AvMÉn ˆbB| ˆm ivÞGmi Qwe AuvKGQ|

LwjGji Õ¨x iv®²vNGi| ˆm iv®²vi Z`viwK KiGQ| AvR ZvG`i evmvq ˆcvjvI, Lvwmi ˆiRvjv ‰es ˆivÕ¡ iv®²v nGœQ| LwjGji Õ¨xi

wKGkvix-wKGkvix ˆPnviv| bZzb kvwo civq ZvGK my±`i jvMGQ| AvR ZvG`i weGqi Qq eQi cƒwZÆ|

ˆgGqwU iv®²vNi ˆ^GK ejj, ZzwnGbi evev, AvR Zzwg KvDGK ˆLGZ ejwb? ˆZvgvi e®¬zev®¬e ˆKD AvmGe bv?

Lwjj ejj, wKQy wKQy AbyÓ¤vb ÷ay Õ¼vgx-Õ¨xi RbÅ| evBGii ˆKD ˆmLvGb ^vKGe bv|

Avwg ‰KMv`v Lvevi iv®²v KGiwQ| me eviB ˆZv Zzwg AbÅG`i ejGZ|

Avi eje bv| ÷ay Zzwg Avi Avwg|

ˆgGqwU nvmGZ nvmGZ ejj, Zzwg AvmGj gÅvGiR AÅvwbfvmÆvwii K^v fzGj ˆMQ| wVK eGjwQ bv?

üu |

BœQv KiGj ‰LGbv ejGZ cvGiv| gvò AvUUv `k evGR|

‰Lb Avi ejGZ BGœQ KiGQ bv| cvGk ‰Gm eGmv|

iv®²v ˆ`LvwœQ ˆZv|

iv®²v KvGRi eyqv hv cvGi, ˆ`LGe|

Zi‚Yx mvgGb ‰Gm emj| Zzwnb Qwe AuvKv e®¬ KGi gyL ZzGj ejj, evev, ˆZvgiv wK¯§ nvZ aivawi KiGe bv| ZvnGj Avwg ivM ne|

Õ¼vgx-Õ¨x `yRbB nvmGQ| Zzwnb gv-evevi nvZ aivawi QvovB ivM nGqGQ| ˆm ivÞGmi Qwe wbGq PGj ˆMj| Lwjj ejj, ‰kv!

weevnevwlÆKx Kx RbÅ fzGj ˆMwQ ˆkvGbv|

‰kv ejj, ev` `vI ˆZv| weevnevwlÆKx fzGj hvIqv ˆZvgvi RbÅ bZzb wKQy bv| cÉ^g `yB eQi Qvov me eviB fzGj ˆMQ| ˆkl gynƒGZÆ

Avwg gGb KwiGq w`GqwQ|

‰evi gGb KwiGq w`Gj bv ˆKb?

m®¬Åv QqUvi mgq AGbKevi ˆUwjGdvb KGiwQ|

ZLb ˆgvevBj ˆdvb e®¬ wQj| Avwg fqsKi ‰K gwnjvi mGã K^v ejwQjvg|

fqsKi ˆKb?

ˆm Zvi Õ¼vgxGK wel LvBGq ˆgGiGQ| Zvi cGiI ˆKvGbv weKvi ˆbB| Zvi Õ¼vgxi ˆWWewW MÉvGgi evwoGZ cvwVGq ˆm mvRGMvR KiwQj|

‰kv ejj, evwbGq K^v ejGe bv ˆZv|

evwbGq ejwQ bv| Avgvi mvgGb eGm bGL ˆbjcwjk w`wœQj| Avwg nZfÁ¼|

‰kv ejj, nqGZv ˆZvgvGK nZfÁ¼ Kivi RbÅB KvRUv KGiGQ| ˆgGqUv ˆh Lyb KGiGQ, Zzwg wbwøZ?

nuÅv| me mG±`n i‚webvi Ici|

i‚webv bvg?

üu | Zvi MuvRv LvIqvi AfÅvmI AvGQ| ˆnvqvU ‰ KÅvGiÙi?

‰kv ejj, mvaviYZ ˆ`Lv hvq, me mG±`n hvi Ici, ˆm Lyb KGiwb| hvGK ˆKD mG±`n KiGQ bv, ˆm Lyb KGiGQ|

Lwjj ejj, MÍ¸-DcbÅvGm ‰ iKg ˆ`Lv hvq| ‰ iKg bv nGj wWGUKwUf MÍ¸ `uvovq bv| evÕ¦Ge me mG±`n hvi Ici, ˆm-B Lywb|

i‚webv Kx KGiGQ ÷bGZ PvI?

// Original page 22
[[page-22]]

bv weevnevwlÆKxGZ LybLvivwei MÍ¸ ˆKb ÷be?

Lwjj ejj, ZvI wVK| AvœQv hvI, ev`|

‰kv ejj, ˆZvgvGK ˆ`GL gGb nGœQ, ˆZvgvi Lye ejGZ BGœQ KiGQ| eGjv, ÷wb|

Lwjj ejj, i‚webv DBGcvKv gvivi welq wKGb ‰GbGQ| DBGcvKvi welq nGjv KwVb wel| ˆe`vbvi RymfwZÆ ™ÏvGm AGaÆK ˆevZj

ˆXGjGQ| Zvi Õ¼vgxGK LvBGqGQ|

‰kv ejj, i‚webv ˆ`LGZ ˆKgb?

Lwjj ejj, Lywb nGjv Lywb| ˆ`LGZ ivRKbÅvi gGZv nGjI Lywb, `uvZ-DuPv ZvoKv ivÞmxi gGZv nGjI Lywb|

Zvi gvGb, ˆZvgvi ‰B Lywb LyeB i…ceZx?

nuÅv, i…ceZx| i…ceZxG`i bvbvb dÅvKov ^vGK| Õ¼vgxi e®¬zG`i mGã ˆcÉg ZvG`i ‰KwU| ˆgvwUf ‰UvB nGe|

AvGjvPbvi ‰ chÆvGq Avwg nVvr eGj DVjvg, ‰kv| ˆZvgvi Õ¼vgxi K^v wek¼vm KiGe bv| DBGcvKvi weGli welqUv Avgvi gGb

cGoGQ| wel Avwg AvwbGqwQ| eo gvgvi dvGgÆwmi ‰KwU ˆQGjGK w`Gq wKwbGqwQ| wel wKwbGqwQ Avi ‰KUv ˆÕ·É wKwbGqwQ| Avgvi eBGq

DBGcvKv aGiGQ| DBGcvKv gvivi RbÅ| DBGcvKvi Ilya ˆhLvGb cvIqv ˆMGQ, ˆÕ·ÉUvI ˆmLvGb wQj|

Avwg K^v ˆkl Kijvg| K^v ˆkl Kiv bv-Kivq wKQy hvq-AvGm bv| ‰kv ˆgGqwUi mGã ev RxweZ KviI mGãB Avgvi ˆhvMvGhvGMi

ÞgZv ˆbB|

‰kv AvgvGK PgGK w`Gq Zvi Õ¼vgxGK ejj, DBGcvKvi Ilya ˆKbv nGqGQ eBcGò ˆ`Iqvi RbÅ|

Lwjj ejj, Zzwg RvbGj ˆKvGïGK? ˆZvgvGK ˆK eGjGQ?

‰kv ejj, AvgvGK ˆK Avevi ejGe? ‰ iKg gGb nGœQ eGj ejwQ| Ilya ˆhLvGb wQj, ˆmLvGb ˆÕ·É wQj bv? ^vKvi ˆZv K^v|

Lwjj wPw¯¦Z gyGL ejj, nuÅv, wQj| ‰Lb gGb cGoGQ| Zzwg KxfvGe ejQ?

‰kv nvmGZ nvmGZ ejj, Avwg cÉvqB gb ˆ^GK ‰gb me K^v ewj, Zv mwZÅ nq| Zzwg ˆZv ‰Uv RvGbv|

Lwjj nuÅv-mƒPK gv^v bvoj| Avwg ejjvg, ‰kv! wµÏR ˆZvgvi Õ¼vgxGK eGjv, i‚webv Zvi Õ¼vgxGK Lyb KGiwb| ˆKD Lyb KGiwb| ‰Uv wQj

mvaviY g†ZzÅ, nvUÆ AÅvUvK ev AbÅ wKQy| eGjv ‰kv, eGjv|

‰kv ejj, iv®²v nGZ ˆ`wi nGe| Zzwg wK ‰K Kvc Pv LvGe?

bv

LvI, ‰K Kvc Pv| `yRb eviv±`vq eGm Pv LvB, PGjv| ‰K Kvc Pv evbve| Zzwg ‰Kevi PzgyK ˆ`Ge| Avwg ‰Kevi|

AvœQv hvI, Pv evbvI|

Avwg ejjvg, Pv cGi evbvGe ‰kv| AvGM i‚webv wbG`Ævl, ‰Uv eGjv| ˆ`wi KiQ ˆKb?

‰kv ejj, Avwg ˆgvUvgywU wbwøZ, i‚webv ˆgGqUv wbG`Ævl| Zvi Õ¼vgxi Õ¼vfvweK g†ZzÅ nGqGQ|

wfGmiv wiGcvGUÆ AiMÅvGbv dmdivm cvIqv ˆMGQ|

wiGcvUÆ fzj nGqGQ| Avevi cixÞv Kivi eÅeÕ©v KGiv|

ˆ`Lv hvK|

ˆ`Lv hvK bv| eÅeÕ©v KiGZB nGe| ‰KUv wbG`Ævl ˆgGq duvwmGZ SzjGe bvwK?

Lwjj ejj, ‰B cÉmãUv ^vK|

‰kv ejj, bv, ^vKGe bv| i‚webv ˆgGqUv wbøqB fqsKi KGÓ¡ AvGQ| Zzwg Zvi KÓ¡ `ƒi KGiv|

KxfvGe?

ˆUwjGdvb KGi eGjv ˆh Zzwg wbwøZ, Zvi Õ¼vgxi Õ¼vfvweK g†ZzÅ nGqGQ|

Avwg wbwøZ bv|

‰kv ejj, ZzwgI ‰Lb wbwøZ| gyGL ejQ, wbwøZ bv|

Avwg ejjvg, ‰kv, Zzwg ˆZvgvi Õ¼vgxGK eGjv, i‚webvi gGZv fvGjv ˆgGq Lye Kg RG¯ÃGQ| Zvi ˆPGq eo K^v, ˆm AmÁ¿e eyw«¬gZx| ˆm

hw` Zvi Õ¼vgxGK Lyb KiZ, ZvnGj ‰gbfvGe KiZ ˆh ˆZvgvi Õ¼vgxi mvaÅI nGZv bv LyGbi inmÅ D«¬vGii| ‰B K^vUv ZvGK eGj Zvici

Pv evbvGZ hvI|

‰kv DGV `uvovGZ `uvovGZ ejj, i‚webv ˆgGqUv AwZ eyw«¬gZx| ˆm Lyb KiGj ‰gbfvGe KiZ ˆh Zzwg aiGZ cviGZ bv|

i‚webv AwZ eyw«¬gZx, ˆZvgvGK ˆK eGjGQ?

ˆKD eGjwb| Avgvi gb ejGQ|

K^v mwZÅ| wk BR ˆfwi ÕÃvUÆ|


Lwjj Zvi Õ¨xGK wbGq eviv±`vq eGmGQ| ZvG`i mvgGb ‰K Kvc Pv| ˆmB KvGc ‰Kevi Lwjj PzgyK w`GœQ, ‰Kevi ‰kv PzgyK w`GœQ|

Zzwnb ivÞGmi Qwe wbGq eviv±`vq XzKj| Mvj dzwjGq ejj, ˆZvgiv nvZ aivawi KGi eGm AvQ ˆKb? nvZ QvGov| Avwg Lye ivM

KGiwQ|

Lwjj nvZ ˆQGo DGV `uvovj| ‰kv ejj, ˆKv^vq hvœQ?

Lwjj ejj, i‚webv gÅvWvgGK ‰KUv ˆUwjGdvb Kie|


i‚webv Zvi ˆgGqi NGi eGm AvGQ| cwjb nxiK msMÉGni ˆLjv ˆLjGQ| ‰KUv fqsKi RvqMv cvi nGZ cviGQ bv| `yUv mvc ˆQvej w`Gq

ˆgGi ˆdjGQ| cwjb ejj, evev ^vKGj ‰B mvGci RvqMvUv cvi KGi w`Z| evev cvGi, Avwg cvwi bv|

i‚webv ejj, ˆm ‰Lb ˆbB| mvcGLvGci RvqMv ˆZvgvGK ‰KvB cvi nGZ nGe| iex±`Ébv^ VvKzGii weLÅvZ Mvb AvGQ, ‰Kjv PGjv,

‰Kjv PGjv ˆi| iex±`Ébv^GK ˆPGbv bv?

// Original page 23
[[page-23]]

wPwb | mv`v `vwo AvGQ|

i‚webvi ˆUwjGdvb evRGQ| ˆm ˆUwjGdvb aij|

gÅvWvg, Avwg Lwjj|

i‚webv ejj, Rvwb| Avcbvi bvg DGVGQ|

AvcbvGK ˆUwjGdvb Kijvg ‰KUv K^v RvbvGbvi RbÅ| Avcwb mG±`Gni ZvwjKvq ˆbB|

ˆK AvGQ, cwjb?

ˆKD ˆbB| Avcbvi Õ¼vgxi Õ¼vfvweK g†ZzÅ nGqGQ| nvmcvZvj ˆ^GK ˆ`Iqv Wvî×vGii ˆW^ mvwUÆwdGKGU nvUÆ AÅvUvGK g†ZzÅi K^v ˆjLv|

wfGmiv wiGcvUÆ gGb nq wVK bq| wfGmiv cixÞv bZzb KGi Kivi eÅeÕ©v KiwQ|

i‚webv ejj, Avwg ‰Lb ˆLGZ hve| Avcbvi K^v wK ˆkl nGqGQ?

mvgvbÅ evwK AvGQ| AvR AvgvG`i gÅvGiR AÅvwbfvmÆvwi| ‰B DcjGÞ Avgvi Õ¨x cÉPzi Lvevi`vevi iv®²v KGiGQ| g†Z evwoGZ

e®¬zev®¬Gei Lvevi cvVvGbvi cÉvPxb ixwZ AvGQ| Avwg wKQy Lvevi cvVvGZ cvwi?

i‚webv ejj, cvGib| nÅvwc gÅvGiR AÅvwbfvmÆvwi|

nVvr ‰KUv avØv Abyfe Kijvg| me AÕ·Ó¡ nGq ˆhGZ ÷i‚ KGiGQ| ˆh cwiKÍ¸bvq AvgvGK wewf®² RvqMvq ˆNvivGbv nGqGQ, ˆm

cwiKÍ¸bvi mgvwµ¦ nGqGQ|

eySGZ cviwQ, AvgvGK PGj ˆhGZ nGe| ˆKv^vq hve? Rvwb bv| gvbyl ˆKvGïGK ‰GmGQ, Zv-B ˆm RvGb bv| ˆKv^vq hvGe, ˆmUv RvbGe

KxfvGe?

Bk&, Avgvi hw` kixi ^vKZ, Avwg i‚webvi nvGZ nvZ ivLGZ cviZvg| cwjGbi KcvGj ‰KUv Pzgy ˆLZvg| ˆgGqUv mvGci RvqMv wbGq

SvGgjvq cGoGQ, ZvGK mvGci RvqMvUv cvi KGi w`Zvg|

N¥Ÿvi kõ nGœQ| N¥Ÿv ˆeGRB ˆ^Gg hvGœQ bv, AGbKÞY aGi wibwib KiGQ| fqven ŠkZÅ AvgvGK MÉvm KiGZ ÷i‚ KGiGQ|

cwjGbi Avbw±`Z Mjv ÷bjvg| ˆh ejj, gv ˆ`GLv, Avwg mvGci RvqMvUv cvi nGq ˆMwQ|

i‚webv Kx ˆhb ejj, Zvi K^v ÷bGZ ˆcjvg bv| Avgvi kõ ˆkvbvi kwî× wK wbGq ˆbIqv nGqGQ? ZvnGj N¥Ÿva»wb ÷bwQ KxfvGe?

Pviw`K ˆKgb Rvwb àwUGq wmwj´£vGii gGZv nGq hvGœQ| wmwj´£vGii ˆkl cÉvG¯¦ AvGjvi ebÅv| ˆmB AvGjvi fqven ˆPŒÁ¼K kwî×| Avwg

QyGU hvwœQ| Avwg ˆcQb wdGi ejjvg, c†w^exi gvbyGliv! ˆZvgiv fvGjv ˆ^GKv| myGL ˆ^GKv! Avwg QyGU hvwœQ AvGjvi w`GK| Avwg Rvwb,

AvgvGK Amxg `ƒiZ½ AwZò×g KiGZ nGe| Amxg Klgbv ˆkl nq bv| ZvnGj hvòv ˆkl nGe KxfvGe?

ˆK eGj ˆ`Ge AvgvGK?


cwiwkÓ¡

wPiKvj ‰Bme inmÅ AvGQ bxie


i‚«¬ IÓ¤vai

R¯ÃvG¯¦i becÉvGZ ˆm nqGZv AvcbvGZ


ˆcGqGQ Dîi\

@iex±`Ébv^ VvKzi
